### ISSUE TITLE
Spring Setup and Mime type issue

### ISSUE THREAD

**Issue by dgeiselmanMOO** [gwtproject/gwt#10017]
**GWT version:** 2.11
**Browser (with version):**  Chrome 129.0.6668.101
**Operating System:** Windows 11

---

##### Description

I'm working on moving our GWT applications to cloud servers and having them run with Springboot.  When I try to run with Spring and load the page it is giving me the error 

`Refused to execute script from 'http://127.0.0.1:8888/healthunderwritingdashboard/healthunderwritingdashboard.nocache.js' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.`

The nocache file is definitely not a json file but it seems it is being detected as one.   What can be done to fix the content type of the nocache.js file so it isn't coming up as json but as javascript as it should be. 

##### Steps to reproduce

Running a GWT application with Springboot

**Comment by niloc132** [comment]
It sounds like this might be a better question for a Spring Boot forum? GWT doesn't provide any file-serving code for other server implementations, and I don't think you're reporting this issue for the Dev Mode server (implemented with Jetty)?

**Comment by dgeiselmanMOO** [comment]
Is there any good information on getting GWT and Spring to interact?

**Comment by jnehlmeier** [comment]
Have you checked the contents of the nocache.js file in browser dev tools / network tab? Maybe it contains a JSON formatted error produced by spring boot and thus spring boot uses JSON MIME type.

If the browser really receives JS content in the nocache.js file, then you should probably ask the springboot people why springboot provides a wrong mime type for JS files.

**Comment by dgeiselmanMOO** [comment]
Or maybe I need to figure out why it is saying the file doesn't exist.

**Comment by FrankHossfeld** [comment]
Thie maven archetype generates a working GWT + Spring Boot project: https://github.com/NaluKit/gwt-maven-springboot-archetype

I have several projects using Spring Boot and never ran into this error.   

Are you working with Windows?

**Comment by dgeiselmanMOO** [comment]
The reason is that the folder with the nocache.js is not being found which is leading to the nocache.js itself not being found.  When running from IntelliJ it isn't looking at my war file.  Have to look at some configurations and then figure out why Docker is not finding my main class

**Comment by niloc132** [comment]
If the file isn't being found, I'm not sure why you would get a json mime type back - unless maybe there is a servlet preventing loading any files from the filesystem (or the war), and is treating every call as a "rest" (or other json-over-http) call, just to a service/type that doesn't exist?

**Comment by dgeiselmanMOO** [comment]
How should the jar be setup for GWT with Spring?  We use gradle to build.  I can get things to build, but I don't think the files are in the right places.

**Comment by niloc132** [comment]
Without seeing the rest of your build or code, it is hard to make concrete suggestions - Gradle, with or without plugins, is extremely flexible, as you can run any code as part of the build process, so nearly anything could be produced as part of that build.

Instead of approaching it from this angle, I'd suggest you start with these questions to take a closer look at what is happening:
 * What is the actual response from the server when you try to load the .nocache.js file? Do you see JSON contents, or the expected JS file? You can test this either by checking the network tab of your browser's dev tools, or directly navigating to the URL you expect to work
 * What change did you make that caused this to start happening? From your initial question you said "moving our GWT applications to cloud servers and having them run with Springboot" - how much of that process is done, and exactly what changed? After which change were the files no longer able to be served? 
 * How is the host html file served, and where is it located on disk (in a jar/war/etc)? Before the project broke, was it located in the same place? Before the project broke, where was the compiled JS?

**Comment by niloc132** [comment]
Closing for now with no feedback - this would be a better topic to continue at the [mailing list](https://groups.google.com/g/google-web-toolkit) or the [gitter chat](https://gitter.im/gwtproject/gwt).
