### ISSUE TITLE
How to set up a Java IDE for this project - config or docs available?

### ISSUE THREAD

**Issue by ahumsolutions** [gwtproject/gwt#10050]
**GWT version:** latest
**Browser (with version):** Chrome
**Operating System:** Mac OS

---

##### Description

I'm new to this project and I'd like to set up a Java IDE for it - preferably Intellij. Are there any docs or config files available? I was trying to update the eclipse config but was very time consuming. Thanks!

##### Steps to reproduce

n/a

**Comment by FrankHossfeld** [comment]
This. is a great place to start: [https://www.gwtproject.org/gettingstarted-v2.html](https://www.gwtproject.org/gettingstarted-v2.html)

Best way to start:

* Choose between[gwt-maven-archetypes](https://github.com/tbroyer/gwt-maven-archetypes) (jetty as server) or [gwt-maven-springboot-archetype](https://github.com/NaluKit/gwt-maven-springboot-archetype) (Spring Boot as server) depending on the server you like to use 
* follow the instructions
* Import the macven project into your IDE

**Comment by niloc132** [comment]
@FrankHossfeld I think @ahumsolutions is asking about how to set up the IDE for the GWT repo itself? 

Assuming so, a different answer: 

We don't have a great way to do that right now, aside from setting up a project on the repo, defining the main and test source sets in user/, dev/core/, dev/codeserver/, and then pointing at all the jars referenced from the tools repo as needed. Historically I have usually had a 80%-correct setup for this, and relied on ant to actually build, run tests, and used the jvmargs options to debug running tests or the compiler to work out bugs. This approach requires that your IDE mostly exist as a code editor and remote debugger, which admittedly isn't great.

@jnehlmeier had a PR many years ago that tried to formalize a setup that managed a lot of this, and has considered updating it and submitting it, but I'm not sure what the state of that is.

I also have opened https://github.com/gwtproject/gwt/issues/10011 to focus efforts around dropping ant and rebuilding the project around Maven (or possibly Gradle, see the issue for discussion there) so that anyone could import the project and trust that updates to the build files will correctly inform their IDE about what it should do next. I have gotten far enough along that path that I'm convinced that this is worth doing, and am pursuing other refactor/deprecation projects to make this possible. See the various linked from there to see what that refactor work would look like - the finished product of #10011 itself should consist mostly of a commit that adds poms, removes build.xml files, and moves sources to new homes as needed. I'm tentatively hoping that we can get there in about 1-3 releases (depending on how you count), both in terms of time investment and in terms of offering a clear deprecation path away from using certain classes that might still be live in downstream projects.

**Comment by FrankHossfeld** [comment]
@niloc132 was too early ... you are right.

**Comment by ahumsolutions** [comment]
Ok thanks - I'll try setting up Intellil 🙏
