### ISSUE TITLE
macOS trackpad scrolls too fast wince GWT 2.12.0

### ISSUE THREAD

**Issue by jeanphil77** [gwtproject/gwt#10076]
**GWT version: 2.12.0** 
**Browser (with version): Safari 18.1.1, Chrome 131.0.6778.205** 
**Operating System: macOS 15.1.1** 

---

##### Description
Since GWT 2.12.0, the trackpad on macOS scrolls way too fast which makes it close to unusable.

##### Steps to reproduce
1. Load https://www.bestcrosswords.com/bestcrosswords/guestconstructor/GuestConstructorPuzzle.external?sp=S290463
2. Scroll the ACROSS or DOWN clues section with the trackpad.
3. Prior to 2.12.0, this used to scroll reasonably slowly allowing the players to preview available clues. Now it scrolls way too fast and jumps to the top or bottom of the list almost immediately.

##### Known workarounds

None so far. I will look at the code and see if it's possible to override some of the new methods introduced in the DOM relating to mouse wheel velocity e.g. user/src/com/google/gwt/dom/client/NativeEvent.java getMouseWheelVelocityY.

**Comment by zbynek** [comment]
Instead of `NativeEvent.getMouseWheelVelocityY` please use `NativeEvent.getDeltaY`.
Instead of `MouseWheelEvent.getDeltaY` please use `MouseWheelEvent.getNativeDeltaY`.

The 2.12 implementation is based on cross-browser standards and aims to fix the opposite of your problem -- velocity of some events was previously rounded to 0 in some browsers (https://github.com/gwtproject/gwt/pull/9971). I'm sorry if that change caused you trouble. If you can't find a simple fix, please share the related bits of your code so that we can help.

**Comment by jeanphil77** [comment]
Thanks @zbynek , I re-checked the code and found out that I had implemented custom code to tweak scrolling behavior  and I had forgotten about it. I've removed the code as it is no longer needed and scrolling works fine.

I will close the issue now, thanks for replying.
