### ISSUE TITLE
CellTable does not support resizable headers

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#6400]
Originally reported on Google Code with ID 6401

```
Found in GWT Release (e.g. 1.5.3, 1.6 RC):
2.3.0, 2.4.0 beta


Encountered on OS / Browser (e.g. WinXP, IE6-7, FF3):
WinXP IE8


Detailed description (please be as specific as possible):
The current CellTable implementation does not support resizable columns as was present
in the Incubator.
Our application can not be migrated since this and issue 188
http://code.google.com/p/google-web-toolkit/issues/detail?id=188
are required functionality.


Shortest code snippet which demonstrates issue (please indicate where
actual result differs from expected result):



Workaround if you have one:



Links to relevant GWT Developer Forum posts:

```

Reported by `david.nouls` on 2011-05-25 15:18:26

**Comment by frederikvanhoyweghen** [comment]
Bump, any updates on this? The workaround available works but has it's quirks.

**Comment by tbroyer** [comment]
This issue had been marked as `PatchesWelcome` more than 5 years ago (sorry the status didn't propagate when we migrated to GitHub), and I can't recall seeing any proposed patch.
There are third-party widgets that support column resizing (along with other features) if you really want it; e.g. https://vaadin.github.io/gwt-polymer-elements/demo/#vaadin/VaadinGridSample (Apache-licensed), http://examples.sencha.com/gxt/4.0.2/#ExamplePlace:basicgrid (GPLv3 or commercial).

Closing this issue now because it's been so long, but feel free to contribute a patch.
