### ISSUE TITLE
Super Dev Mode doesn't detect GWT applications running in iframes

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#7458]
Originally reported on Google Code with ID 7461
```
Symptom:

If you go to a web page and press "Dev Mode On", GWT modules that are in an iframe
aren't listed.

Diagnosis:

Part of the problem is that we keep a separate registry per window (in window.__gwtActiveModules).
If the iframes are same-origin, perhaps the bookmarklet could check for this in each
iframe.

For cross-origin it's harder; we need to actually set a property in sessionStorage
in a different origin.

Workaround:

Write your own button that triggers a recompile via a call to http://localhost:9876/recompile/{module
name}
and then sets the property in sessionStorage and reloads the page.

Possible solutions:

Perhaps the "Dev Mode On" bookmarklet should allow you to recompile modules even if
they aren't on the current page. But you would still need to navigate to a page in
the right origin, in order to set sessionStorage.

Alternately we could also provide people with a button to embed into their GWT app
(some apps have developer consoles), or provide browser extensions for specific browsers
(that way lies madness, though).

Current as of GWT 2.5 rc 1.
Ported from internal issue tracker: http://b/issue?id=6410666

```

Reported by `skybrian@google.com` on 2012-06-27 22:12:24

**Comment by danleahu** [comment]
Applied workaround but http://localhost:9876/recompile/{modulename} only finds the outer module ModuleA but not the one inside the iframe, ModuleB. 
I'm using CodeServer with the module param set to ModuleA, is it not seeing ModuleB because somehow I don't provide ModuleB as well to CodeServer? Is there something specific to make it see ModuleB? Thank you!

**Comment by tbroyer** [comment]
CodeServer accepts several modules as arguments.

Launching CodeServer with `-launcherDir` will enable "compile-on-load", meaning that you only need to refresh the page to trigger a recompile, with no need for bookmarklets anymore.
SDM with bookmarklets have been deprecated because they don't support a number of use-cases that `-launcherDir` enables.
