### ISSUE TITLE
LookupMethodCreator create too large method

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#8611]
Originally reported on Google Code with ID 8635

```
Found in GWT Release (e.g. 2.4.0, 2.5.1, trunk): <2.5.1


Detailed description (please be as specific as possible):
If you have a large properties file (~2000 entries) and use the LookupMethodCreator
the getString() is too large.


Workaround if you have one:
We have patched the LookupMethodCreator to create partition methods (see attached file)


Link to patch posted at http://gwt-review.googlesource.com


```

Reported by `mcmics84` on 2014-03-17 08:22:01

<hr>
- _Attachment: [LookUpMethodCreatorNew.java](https://storage.googleapis.com/google-code-attachments/google-web-toolkit/issue-8635/comment-0/LookUpMethodCreatorNew.java)_

**Comment by MCMicS** [comment]
Patch in Gerrit and needs Review ([Change 13680](https://gwt-review.googlesource.com/#/c/13680/))

**Comment by MCMicS** [comment]
Change need one review/vote

**Comment by PrimaMateria** [comment]
Hi, in which versions will be this bug fixed? Can you port it also to GWT 2.7.0?

**Comment by MCMicS** [comment]
Hi @PrimaMateria,
this Fix was merged today.

**Comment by manolo** [comment]
@PrimaMateria @MCMicS The merged patch was reverted because there were a couple of aesthetic style issues in code, and space missing before a bracket and the javadoc of a public class in the test package missing. Our CI didn't detect that because it doesn't run pre-commit checks on external contributors patches.
I have submitted a patch with this style fixes, but because 2.8.1 was already cut before the patch, it will not include the patch.   @PrimaMateria Porting the patch 2.7.0 and releasing is not an option. 
Is is acceptable for you guys to wait until 2.8.2?

**Comment by tbroyer** [comment]
> Our CI didn't detect that because it doesn't run pre-commit checks on external contributors patches.

Actually, it does; but only after we add the contributors to a whitelist or we give a CodeReview+2 to the change.

**Comment by manolo** [comment]
Codreview+2 didn't work, probably because I set verified flag?.

**Comment by tbroyer** [comment]
> probably because I set verified flag?

Yep.
Gerrit query can be found here: https://gwt.googlesource.com/buildglue/+/8e8c05e6a35344f5e57b91f86fe9862e2be6fc77/cmd/presubmitter/presubmitter.go#54

**Comment by MCMicS** [comment]
What is the ste of this issue?
The 2.8.1 is out.

**Comment by tbroyer** [comment]
Review: https://gwt-review.googlesource.com/c/gwt/+/18161
Test fix: https://gwt-review.googlesource.com/c/gwt/+/19340
