### ISSUE TITLE
Caching problem for nocache.js files.

### ISSUE THREAD

**Issue by dankurka** [gwtproject/gwt#9108]
Originally reported on Google Code with ID 9177
```
When running a production compile, I've had to restart my app server in order for the
nocache.js file's changes to be picked up.  This causes my app server to ignore the
changes in the content, serve the stale nocache.js, which then causes my cache.js files
to 404.

Looking at the output of the compiler, I noticed that the contents of the nocache.js
file are changing (new strongnames), but the timestamp is not.  Tracing this in the
compiler shows that the timestamp is set from the ModuleDef's lastModified timestamp,
which is based on the last modification to a gwt.xml file.  However, when my changes
are only to source files, this time never updates, and my nocache.js file looks stale.

Suggested fix: In SelecionScriptLinker.emitSelectionScript, instead of using the module's
last modified time, use -1 (OutputFileSet.TIMESTAMP_UNAVAILABLE), or the current system
timestamp.

Workaround: perform a touch on the nocache.js file after your Gwt compilation completes,
so your app server will pick up the changes.
```

Reported by `James@wetheinter.net` on 2015-04-07 20:11:52

**Comment by alt250** [comment]
Link to the original issue thread, with custom linker workaround code:
https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/q4BgTzs6PXw

**Comment by gkdn** [comment]
This is mostly affecting open source users and we are not sure exactly what you need.
@tbroyer Can you talk with @stalcup and explain the behavior you need here?

**Comment by gkdn** [comment]
cc'in @dankurka as he mentioned he hit this issue as well.

**Comment by gkdn** [comment]
Last call for suggestions. We will do a release pretty soon.

**Comment by jnehlmeier** [comment]
@gkdn there is already a patch that would restore the old (and more correct) behavior. However it was reverted, so I guess you should talk to @stalcup why it was reverted. 

Patch: https://gwt.googlesource.com/gwt/+/0bd86b8206ab475b5dc5aeb6bd4f5a2534dafd18

**Comment by gkdn** [comment]
It was reverted because somebody complained about the restored behavior. It might be possible that it didn't correctly restored the old behavior.

Anyway, here is another restore attempt: https://gwt-review.googlesource.com/#/c/13918/

Can you guys verify this?

**Comment by tbroyer** [comment]
@gkdn @stalcup The main issue currently (and in 2.7) is that in most cases the `nocache.js` file's mtime won't be updated whereas its content changes, because the mtime is based only on the `gwt.xml` files' mtime (so if you change a Java file and recompile, the content will changed based on changed permutation names, but the mtime will stay the same); and this causes issues with many configurations that rely on the mtime for HTTP conditional requests (`If-Modified-Since`): the server will reply with a `304 Not Modified` to the browser which will use its cached version that still links to the old permutation names, leading to `404 Not Found` and a broken app.

The current workaround is to _touch_ the `nocache.js` file after each compilation: https://github.com/tbroyer/gwt-maven-plugin/blob/1d9d1c67155e62982296abf4386888fb9198968d/src/main/java/net/ltgt/gwt/maven/CompileMojo.java#L230-L235 (note that this is my "non-final" plugin for Maven, most people still use the older plugin that doesn't do that).

**Comment by tbroyer** [comment]
Alternative fix: https://gwt-review.googlesource.com/13932 (see discussion in https://gwt-review.googlesource.com/13918 for more context)

**Comment by tbroyer** [comment]
John's change (rollback of previous change) has been submitted. I rebased mine on top of it (rollback of John's change, reapplying the original change but with a change in how the mtime is computed) but that bug is fixed by John's change anyway, so closing.

**Comment by fmisa** [comment]
Trying to understand here...  why are we relying on timestamps anyway ? 
nocache means nocache - regardless of timestamp.... or at least should.

Shouldn't the server instruct browser - not to cache - *.nocache.js files.
JETTY: cacheControl  no-cache
APACHE: <FilesMatch> Header unset Cache-Control
etc.

As a hack I'm seeing some use meaning parameters:
<script src="x.nocache.js?nocache=123" ></script>

or filters to control:
http://seewah.blogspot.ca/2009/02/gwt-tips-2-nocachejs-getting-cached-in.html

But at end of day - what's the point of these "no cache" directives to browser - if it's still going to consider timestamps on the files.

Any thoughts ?

**Comment by jnehlmeier** [comment]
@fmisa Ideally your browser should ask the server if a newer version of the *.nocache.js file is available, and if yes fetch it from the server. Otherwise the browser can used a cached version. So your browser should do an "If-Match" / "If-Modified-Since" request to save bandwidth. But that requires correct timestamps on the server.

http://www.gwtproject.org/doc/latest/DevGuideCompilingAndDebugging.html#perfect_caching

**Comment by fmisa** [comment]
Thanks very much for the feedback - really appreciate it.
From the thread though - not clear what option is for GWTv2.7 users - is there a patch/version - that @tbroyer refers to ? (i.e. "John's Change")  what is the version that resolves this issue.

**Comment by tbroyer** [comment]
GWT 2.8 contains the fix (incl. beta 1). `net.ltgt.gwt.maven:gwt-maven-plugin` has a workaround too, for 2.7.

**Comment by fmisa** [comment]
Thank You !

**Comment by vedsarkushwaha** [comment]
I'm facing this issue in GWT 2.8.
