### ISSUE TITLE
Showcase Sample App CustomDataGrid FieldUpdate.update doesn't fire "change" event of SelectionCell.

### ISSUE THREAD

**Issue by rezolve** [gwtproject/gwt#9176]
In the GWT Showcase sample app (I'm using GWT 2.6) the update method of the FieldUpdater for the categoryColumn in CwCustomDataGrid never fires. This is a SelectionCell which should fire "change" events and it never does. I tested it in SuperDev Mode. Development environment = Windows 7, Eclipse, GWT 2.6.0, tested in Chrome, IE and Firefox. I never get the alert (below) when changing the category column selection values. 

categoryColumn.setFieldUpdater(new FieldUpdater<ContactInfo, String>() {
      @Override
      public void update(int index, ContactInfo object, String value) {
    	Window.alert("update()!");
        for (Category category : categories) {
          if (category.getDisplayName().equals(value)) {
            object.setCategory(category);
          }
        }
        ContactDatabase.get().refreshDisplays();
      }
    });

**Comment by tbroyer** [comment]
It indeed looks like there's an issue in the CwCustomDataGrid: if you change the value in any other sample screen (CwCellTable, CwDataGrid), it is reflected in the others (including (CwCustomDataGrid); but that's not the case if you change the value in the CwCustomDataGrid sample.

**Comment by tbroyer** [comment]
OK so the bug is in the sample actually: it never adds the columns to the `DataGrid` so events aren't sunk correctly. It works for other cells because it happens that they only use events that are sunk anyway (focus, blur, click, keyup, keydown), whereas `SelectionCell` needs the change event (`CheckboxCell` also uses the change event, but in this case it's only used to trigger selection so the event is actually handled by the `CellPreviewEvent.Handler` associated with the `SelectionModel`, and the change event is not actually being used).

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/13400

**Comment by rezolve** [comment]
Thanks Thomas, it's working.
