### ISSUE TITLE
data type of calling parameters from JSNI method to Java method

### ISSUE THREAD

**Issue by bbbalabhaskar** [gwtproject/gwt#9177]
I am working on canvas elements, when I am calling Java method accepting integer as parameters from my JSNI code, I noticed that even when I pass double value from JSNI it is being accepted by my Java method

**Comment by tbroyer** [comment]
Can you show some code? I have troubles understanding your issue.

**Comment by bbbalabhaskar** [comment]
following is  the method I'm calling from JS, which is injected to $wnd variable, when I call the method it is passing variables which is of type double. and when I alert  x,y values it is getting floating-point values.

native void test(View view){
  $wnd.chvp=function(x,y){
    view.@in.bala.application.main.View::change(II)(x,y);
  };
}

public void change(int x, int y){
  ...
  ...
}

**Comment by tbroyer** [comment]
This is the expected behavior. JS has only one numeric type: `Number`, which is roughly equivalent to Java's `double`. GWT does not automatically rounds/truncates/coerce values when crossing JSNI boundaries as that would greatly impact performances; so it's your responsibility to ensure that your values are integers before passing them to your Java method, if it really matters.

---
BTW, you'll want to wrap your JS function into `$entry` for proper exception and entry/finally commands execution:

```js
$wnd.chvp = $entry(function(x, y) {
    view.@in.bala.application.main.View::change(II)(x|0 , y|0);
};
```

**Comment by tbroyer** [comment]
Duplicate of #8817
