### ISSUE TITLE
Different Bootstrap Sequence with xsiframe linker

### ISSUE THREAD

**Issue by WhiteTrashLord** [gwtproject/gwt#9188]
Here it's described that body.onload() will always fire after everything was loaded:

http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideBootstrap

It seems to be totally wrong with this linker setting:

add-linker name="xsiframe"

Maybe this is not a bug. But some better documentation would be nice. This shit cost me some time :(

**Comment by tbroyer** [comment]
I think you misunderstood the doc. `onload` will fire once everything in the initial HTML has been loaded (unless marked asynchronous, in modern browsers); that's how it's spec'd and how browsers implement it.

Your entry-point's `onModuleLoad` can fire anywhere between `DOMContentLoaded` and "just after `onload`". It's quite clear in the doc (though not as precise):

>  * The GWT selection script (i.e. `myApp/myApp.nocache.js`) will be fetched and evaluated like a normal script tag, but the compiled script will be fetched **asynchronously**.
>  * Once the GWT selection script has started, its `onModuleLoad()` can be called at any point after the outer document has been parsed.

The example could made it clearer that _“`<hashname>.cache.html` completes”_ happening at step 9 is just one possibility (it could happen at any later time). And it's true that with the `xsiframe` linker (which is now the default), with its default configuration, it could even happen after `onload` actually (maybe it was already the case before, with the `std` linker, I don't really remember).

But it's not "totally wrong".

Leaving the issue open as things could be improved (and the example needs to be updated now that `xsiframe` is the default, with `<hashname>.cache.js` instead of `<hashname>.cache.html`).

**Comment by WhiteTrashLord** [comment]
This point is definitely misleading:

The body.onload() event will only fire once all external resources are fetched, including images and frames.

To me also the GWT Javascript files loaded by *.nocache.js are external.

What's the recommended way to make sure that onModuleLoad() was loaded in the native Javascript code when you work with the xsiframe linker? I can only think of some dirty setTimeout approach.

**Comment by tbroyer** [comment]
The next two bullet points make it clear (to me) that this is not the case.

If you want to make a JS library, then you have 2 choices:

* collapse all permutations in a single "hard permutation", and use a custom linker based on the `sso` linker; that one produces a single JS file, but it still waits for scripts and styles and `DOMContentLoaded`, and can possibly call `onModuleLoad` after `onload`, so it would have to be modified.
* have `onModuleLoad` call a global JS function with a hardcoded name, e.g. `$wnd.onMyAwesomeLibLoaded()`. This is what most people do AFAIK.
