### ISSUE TITLE
Making RegExp thread safe on server side

### ISSUE THREAD

**Issue by happyhua** [gwtproject/gwt#9192]
RegExp object is currently not thread safe when the globalFlag is set due to the class variable lastIndex.

Can we just add an additional method like 
public MatchResult exec(String input, lastIndexHolder) { } in addition to original exec method.

**Comment by tbroyer** [comment]
The goal of `com.google.gwt.regexp.shared` is to be a thin wrapper around a JS RegExp object on client side, and propose an "emulation" for use in a Java VM. The proposed method would break that; `RegExp` is inherently stateful.

What you need is either a _regexp holder_ (rather than _last index holder_), or just use a `java.util.regex.Pattern` on the server-side.

**Comment by happyhua** [comment]
I believed that anything in a shared package is intended for using on both client and server, otherwise you can better put it in a gwt client package.

**Comment by tbroyer** [comment]
`RegExp` can very well be used on both client and server, that doesn't change the fact that it is inherently stateful. It happens that this is only the case with the global flag set, but that's a "side effect", and part of its contract.

Also please note that the stateful nature of `RegExp` make it a bad fit to reuse/sharing, whether on client or in a JVM, independently of thread safety.
This code for example can run in a GWT client app, and yet has the same issue than how you seem to be using `RegExp` on the server:

```java
boolean allMatch(RegExp re, Iterable<String> iter) {
  for (String str : iter) {
    if (!re.test(str)) {
      return false;
    }
  }
  return true;
}
```

It's not about thread-safety, it's about reuse/sharing, and this is part of `RegExp`'s contract.
Also, just because `RegExp` *can* be used in a JVM does not mean you *should* use it in a JVM; it's primarily usable in a JVM so you can share code between client and server, not to be used in replacement of `java.util.regex.Pattern` when `Pattern` would be usable.

You can share a global `RegExp` if you reset its `lastIndex` before use (what your proposed API would have to do on the client-side anyway, taking advantage of the fact that JS is single-threaded), and that means being careful with concurrent accesses and guarding against them:
```java
MatchResult m;
synchronized(re) {
  int lastIndex = re.getLastIndex();
  re.setLastIndex(startSearchIndex);
  m = re.exec(input);
  re.setLastIndex(lastIndex);
}
return m;
```
That can create contention that your proposed API would prevent, but that's about it. I can see it being useful in some cases, but IMO that's not enough to justify changing the API (and contract) of `RegExp` to "if you pass a _last index holder_ then the `RegExp`'s _last index_ is ignored and the _last index holder_ is used instead; if you use the one-argument overload, then the `RegExp` itself holds the _last index_."

Feel free to bring the topic in https://groups.google.com/forum/#!forum/google-web-toolkit-contributors to further discuss whether it would be a good idea to augment `RegExp`'s API. We can still reopen the issue if there's consensus that it would be (IMO, that'd be best as a "fork").

**Comment by happyhua** [comment]
Thanks for the long reply, Thomas.

I agree that the original contract has to be obeyed, that's why I prefer adding an extra exec method.

I can show you my specific case the benefit of an extra exec method of RegExp.

I have a shared Util class, which contains a static method to parse CSV input data and return the result as a list.
<pre>
private static final RegExp REG_EXP_CSV = RegExp.compile(csvPattern);
public static List<String[]> parseCSV(String data) {
	...
	LastIndexHolder lastIndexHolder = new LastIndexHolder();
	while (REG_EXP_CSV.exec(data, lastIndexHolder ) != null) {
		// Either add a new row to List or add a new column to String[].
	}
	...
}
</pre>

You see that here I can eliminate the use of synchronized key if I have self the control of lastIndex. And it also removes the performance penalty, since the input data can be any size, so in theoretically a large text.

That's why I suggest an extra exec method here, which allows developer taking the control of lastIndex if they like. And in my example case it guarantees the thread safe use of parseCSV method.

Sure that I can manipulate the RegExp class by myself, add it to my classpath loader, and my problem is solved in 5 minutes.

I put it as a feature request, because I think that I am not the only one, who needs the control of lastIndex and keep gwt code customizations as less as possible.

And I stick on the use of RegExp, not using java Pattern, simply because the last one is not emulated on the client side. Using it will introduce additional code.
