### ISSUE TITLE
JettyLauncher enforces 1.6 compiler so JSPs with 1.7 features won't compile.

### ISSUE THREAD

**Issue by mrfrag** [gwtproject/gwt#9215]
Default [com.google.gwt.dev.shell.jetty.JettyLauncher](https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/shell/jetty/JettyLauncher.java) enforces Java 6 compiler. 

``` java
/**
   * Ant compiler adapter for Eclipse Java compiler, but with default
   * target and source compatibility set to Java 6.
   */
public static final class JDTCompiler16 extends JDTCompilerAdapter {
    @Override
    public void setJavac(Javac attributes) {
      if (attributes.getTarget() == null) {
        attributes.setTarget("1.6");
      }
      if (attributes.getSource() == null) {
        attributes.setSource("1.6");
      }
      super.setJavac(attributes);
    }
  }
```

This causes errors when trying to compile JSP files with 1.7 features. 
For ex. while using diamond operator you'll get 

```
'<>' operator is not allowed for source level below 1.7
```

error, even with -sourceLevel explicitly set to 1.7 and compilerSourceVM=1.7, compilerTargetVM=1.7 declared in web.xml

**Comment by tbroyer** [comment]
Hmm, that code was actually added two years ago to accommodate #3562

Maybe it should use `System.getProperty("java.specification.version")` instead of being hard-coded to `"1.6"`? (`sourceLevel` is –and should only be– about client code).

Mind trying that (as you might have seen in the source, you can set the compiler class with the `build.compiler` system property; that `JDTCompiler16` is only the default value, so you don't even *have* to patch GWT to test) and eventually [contribute a patch](http://www.gwtproject.org/makinggwtbetter.html#contributingcode)?

**Comment by niloc132** [comment]
It appears that specific code was removed in https://github.com/gwtproject/gwt/commit/e01c5dc24043eb86ad2a17c11094c04973c8a5ce (by Thomas no less), so even if it was a concern, it shouldn't be any more.
