### ISSUE TITLE
GWT 2.7 stopped support IE6/7

### ISSUE THREAD

**Issue by FeyFre** [gwtproject/gwt#9221]
Well, this is The Problem. 
Embeddable Internet Explorer Web Control works in IE6 mode. And that cannot be changed unless command user to edit windows registry. There is no API that container application can use to specify control mode. And definitely such default will not be changed by MS in nearest future.

So only solution I see - revert back support of IE6/7 (into 2.8 or 2.7.1 preferred!)

**Comment by jDramaix** [comment]
If you want support for IE6/& use GWT 2.6 (where you can reenable IE6/7 permutation)

**Comment by tbroyer** [comment]
Apparently, you can use a `<meta htt-equiv=X-UA-Compatible>` in a WebControl: http://blogs.msdn.com/b/patricka/archive/2015/01/12/controlling-webbrowser-control-compatibility.aspx

**Comment by FeyFre** [comment]
I want support of whole range IE6-IE11. Does GWT2.6 provide me that support?

**Comment by FeyFre** [comment]
@tbroyer, I well aware of that kind of "solution". I spent half year to try it. No result.

**Comment by tbroyer** [comment]
2.6.1 should support IE11 but there were bugs that have been fixed in 2.7 (looking at commit logs).

In any case, given that Microsoft is going to cut support for all IE versions except IE11 starting January 12, 2016 [1], what you're asking is never going to happen. So your solutions are (AFAICT):

 * have your application (or its installer) update the Windows registry to trigger the appropriate behavior of the WebControl for your application. AFAICT this is the approach recommended by Microsoft.
 * fork GWT; either using 2.6.1 and backporting the IE11 fixes (and possibly others; for example, if you need to support Firefox you'll have to backport the changes to `com.google.gwt.user.client.History` too), or using 2.7 and trying to port IE7 support back.
 * somehow compile your app with GWT 2.6.1 and 2.7.0 and have some code (in the native application or in the HTML host page) to choose the appropriate one depending on the environment.

If you want to discuss further, I suggest moving the discussion to https://groups.google.com/d/forum/google-web-toolkit

[1] https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
