### ISSUE TITLE
Passing Arrays#asList via GWT-RPC throws IncompatibleRemoteServiceException (2.8.0-beta1)

### ISSUE THREAD

**Issue by kevinfahy** [gwtproject/gwt#9224]
It appears that passing a list created via `Arrays#asList` from the client to server via GWT-RPC will throw an `IncompatibleRemoteServiceException`, e.g.:
```
Exception: com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException: java.lang.ClassNotFoundException: http:
Error: This application is out of date, please click the refresh button on your browser.
```

I've only tested this on lists of strings. One workaround is to wrap lists in an `ArrayList` before calling the GWT-RPC method.

Example:
```
// GWT-RPC method
void emailNotes(List<String> addresses, String message, AsyncCallback<Void> asyncCallback);

// Throws exception
List<String> addresses = Arrays.asList("foo@bar.com");
rpc.emailNotes(addresses, message, callback);

// Does not throw exception
rpc.emailNotes(new ArrayList<>(addresses), message, callback);
```

**Comment by tbroyer** [comment]
Which version of GWT are you using?

Serialization of `java.util.Arrays.ArrayList` (the internal implementation used by `java.util.Arrays.asList()`) has changed in 2.8.0-beta1, but otherwise hadn't changed for nearly 5 years (and serializability of that class was originally added in April 2008)

The error message talking about a class supposedly called `http:` makes me think this is not even a possible regression in 2.8.0-beta1 but something entirely different (maybe using 2.8.0-beta1 on the client side and 2.7.0 on the server)

**Comment by kevinfahy** [comment]
Brilliant, thanks for the help, @tbroyer. You were right - our server was referencing `gwt-servlet` versions of `2.6.0` and (!) `1.4.60`. After updating to `2.8.0-beta` and performing a clean build, the type became serializable.
