### ISSUE TITLE
JsInterop: Return values and arguments of type List should be handled as arrays in JS

### ISSUE THREAD

**Issue by freytagusu** [gwtproject/gwt#9243]
List<T> getValues() should return an array in JavaScript, instead it wraps the array into an object.

void addValues(List<T> values) should accept an array as argument in JavaScript, instead the array needs to be wrapped into an object.

**Comment by cristcost** [comment]
I do need the same behaviour, maybe there could be a special annotation to be added on the method or the parameter to mark it to be managed this way?
i.e.
@JsArray List getValues() 

or 
void setValues(@JsArray List values)

**Comment by gkdn** [comment]
See @JsConvert in the original JsInterop doc. Though it will not make it to the 2.8 release.

**Comment by freytagusu** [comment]
Lists should always be converted to arrays. The current implementation outputs the follwing warnings, when Lists are unsed in exposed Objects:

[unusable-by-js] Return type of 'List EAP.getTodos()' is not usable by but exposed to JavaScript.
[unusable-by-js] Type of parameter 'todos' in 'void EAP.addTodos(List)' is not usable by but exposed to JavaScript.

This implies the user has to implement its own Lists to expose a readable API.
As far as i know the Dart API converts List interfaces to JS arrays by default. I expect this to be the default behavior for gwt too.

**Comment by okrasz** [comment]
When can we expect the @JsConvert to appear? 3.0 or somewhere in between?

**Comment by niloc132** [comment]
Looks like this should have been closed many years ago, JsConvert never made it into the final jsinterop-annotations jar (and the document is gone https://docs.google.com/document/d/1tir74SB-ZWrs-gQ8w-lOEV3oMY6u6lF2MmNivDEihZ4/edit).

JsArrayList has an asList() to return an immutable List instance that reflects the contents of the underlying js array. There is no analogous concept of asking an arbitrary List instance for its backing array, since not all Lists have an array (and those that do won't want the instance to be potentially manipulated from JS).
