### ISSUE TITLE
CSS to GSS conversion seems to treat uppercase identifier in CSS as if they were GSS references

### ISSUE THREAD

**Issue by GwtarPlayer** [gwtproject/gwt#9271]
This is related to and is another aspect of:

https://github.com/gwtproject/gwt/issues/9270

The CSS to GSS conversion causes some uppercase identifiers in CSS to be treated as GSS references. This ultimately fails as they are not this. Note that developers may be able to resolve this in their own stylesheets but not in the (third party) libraries they use. Our problem comes from using g-leaflet (a wrapper for Leaflet.js). Leaflet has the following bit of CSS:

    .leaflet-oldie .leaflet-popup-tip {
           width: 24px;
           margin: 0 auto;

           -ms-filter: literal('"progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)"');
           filter: literal('progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
           }

This causes the conversion to fail with the following error:

         Computing all possible rebind results for 'org.peimari.gleaflet.client.resources.LeafletClienBundle'
            Rebinding org.peimari.gleaflet.client.resources.LeafletClienBundle
               Invoking generator com.google.gwt.resources.rebind.context.InlineClientBundleGenerator
                  Initializing ResourceGenerator
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 56]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 72]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 88]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 504 column: 105]: GSS constant not defined: M22
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 52]: GSS constant not defined: M11
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 68]: GSS constant not defined: M12
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 84]: GSS constant not defined: M21
                     [ERROR] Error in [auto-converted gss files from : [jar:file:...jar!/org/peimari/gleaflet/client/resources/leaflet.css]][line: 505 column: 101]: GSS constant not defined: M22
         [ERROR] Errors in 'org/peimari/gleaflet/client/resources/LeafletResourceInjector.java'
            [ERROR] Line 11: Failed to resolve 'org.peimari.gleaflet.client.resources.LeafletClienBundle' via deferred binding
         [WARN] For the following type(s), generated source was never committed (did you forget to call commit()?)
            [WARN] org.peimari.gleaflet.client.resources.LeafletClienBundle_default_InlineClientBundleGenerator

Obviously, M11, M12, M21 and M22 are viewed as GSS constants, which they are not. In this very case they are defined here:

https://msdn.microsoft.com/en-us/library/ms533014(v=vs.85).aspx

... and have to stay that way.

CSS should be treated as CSS, not as GSS.

**Comment by tbroyer** [comment]
I think the issue here is that GSS has no equivalent to `literal()`, and the conversion simply puts it "literally" in the stylesheet. When it's used to workaround CSS2.1 limitation of the CSS parser to be able to use CSS3 features (such as gradients), it Just Works™ (because GSS supports CSS3); but in the case of the old/broken/non-standard `filter` property, it breaks.

That said, there's no reason nowadays to use `filter`. It's been deprecated when IE8 was introduced with `-ms-filter` support (which doesn't need `literal()`); and btw `-ms-filter` was deprecated as soon as IE9 and removed in IE10. Given that GWT no longer support IE6/7 (for some time now), one can use `-ms-filter` with the equivalent `filter`.

**Comment by GwtarPlayer** [comment]
Yes, that is correct. However, even though, in this case, we do not care about the old IE, that is is entirely irrelevant. We need a third party library for the new browsers. That third party library, which we do not control and cannot control, is based on a JavaScript+CSS library that does care about that support. Hence, even though we don't care about it, we do not have a resolution for this problem:

1. We cannot require third party libraries to drop their support for whatever browsers we want. This is always true in the general case. In the specific case of Leaflet, we actually contacted them and tried.

2. This is specifically inside literal(), which should not be parsed out. As you point out, GSS puts it "literally". This means that the lack of literal() is actually a defect, not merely a missing feature. This could be used elsewhere for other reasons with other libraries that the GWT developer has no direct control of.

**Comment by gxtUser** [comment]
I'm having the same issue as gwtarPlayer.

**Comment by tbroyer** [comment]
@GwtarPlayer You need to talk to the people who added those `literal()` to the original LeafletJS pure-CSS stylesheets and packaged them as a CssResource for GWT. They have to update their library so it works with the latest GWT version(s), and that means being "compatible" with GSS. Put simply, they have to:

 * either remove the `filter` entirely (and stop supporting IE6/7 in this GWT wrapper)
 * or provide a GSS equivalent to the CSS that's wellformed CSS3 (and GWT will simply pick the appropriate one), i.e. run the Css2Gss utility (which you can find online at https://css2gss.appspot.com/), fix the `-ms-filter` for IE8 (Css2Gss appears to remove the quotes around the value) and remove the `filter` property, and save the result as a `.gss` file next to the existing `.css`.

It is known (and I believe documented) that not everything can be automatically translated to GSS, and that manual tweaking might be needed, and that's why you can have both files and GWT will pick the appropriate one.

Actually, I see that @gxtUser already opened an issue on the g-leaflet project at mstahv/g-leaflet#25 (crosslinking here so the author can find the instructions above by following the backlink)

**Comment by GwtarPlayer** [comment]
Well, as I said above, "In the specific case of Leaflet, we actually contacted them and tried."

The truth is that they didn't have literal() previously, they added that later. Their CSS is correct. From, their perspective all is fine and as it should be. They have the right to want to maintain whatever compatibility they desire and we have no right forcing them to drop it.

Leaflet is not the issue here. I referenced it as a single (but likely not only), easy, example. There are many GWT projects using GWT libraries that are wrappers of JavaScript libraries. These are all perfectly valid. The trouble is that GWT+GSS treats their CSS as if it was something else, which it isn't, was never intended to be and may never be. It boils down to the inability of GWT+GSS to work with proper CSS, actually, because the GSS isn't able to abstract it fully and/or the conversion process does not shield/escape or otherwise treat the CSS concepts in GSS such that they don't get picked up as GSS.

The end result is that anyone developing GWT projects using third party libraries may never be able to start using GSS:

a) They cannot unilaterally change those libraries - in fact, they would have to jump through two separate approval and licensing shields (wrapper and the original library)

b) They wouldn't want to do modify these libraries themselves as that creates library update/maintenance nightmares.

c) The third party wrapper libraries will be in the similar spot with respect to (a) and exactly the same with respect to (b).

d) Original JavaScript libraries cannot switch to GSS as they don't have GSS so wrapper libraries,, then, cannot switch to GSS because of that - they cannot advertise GSS safety as that may break at any moment.

Note that there are multiple issues here, that I filed as #9270 and #9271:

a) Attempting to apply GSS concepts to what is not GSS but CSS - this must not be done. CSS is CSS, not GSS.

b) Ignoring the meaning of CSS "literal()" functions.

**Comment by GwtarPlayer** [comment]
In other words, GSS cannot be presently safely used by anyone who has third party libraries that are not pure GWT (i.e. not wrapper of JavaScript libraries) and do not themselves guarantee GSS compatibility. All else is risky and may stop working with any version update, unannounced. It may also be very hard to impossible and costly to test for this compatibility as users of libraries may not be able to enumerate all the edge cases that those libraries may end up in.

**Comment by tbroyer** [comment]
You're wrong on one crucial point: the issue is totally independent of leaflet of any other non-gwt library; it has to do with GWT libraries that provide CssResources. In the case of g-leaflet, the author chose to turn the leaflet css into a CssResource, and then that breaks with GSS. But as a library author, he had one full year (since the release of GWT 2.7) to ensure gss compatibility. You cannot blame GWT for that, we let people plenty of time to update, and afaict the change was announced (correct me if I'm wrong).
Now you should bug the g-leaflet author, and in the mean time you can provide the gss yourself (just put it the appropriate package, with the appropriate name.

**Comment by GwtarPlayer** [comment]
I am not blaming GWT for not notifying. However, GWT attempts to convert CSS into GSS incorrectly, such that constructs that are purely CSS get interpreted as something else in GSS. The conversion process is flawed in that sense.

Again, the concern isn't just about Leaflet. Leaflet is one example. The problem is generic, as I described above.

**Comment by tbroyer** [comment]
I can't tell for sure but that specific example is not about "purely CSS" but "broken CSS" (the filter value).

As for GWT failing to transform CSS to GSS, as I said, it's a known limitation, and there are ways around it (namely, don't use automatic translation at build time, instead provide a curated GSS stylesheet).

Finally, it's not as generic as you said: it's very specific to CSS written (or transformed/copied) for GWT CssResource and nit uodated for GSS in newer GWT version.
In the case of g-leaflet, the author chose to use CssResource but could have used a TexrResource instead with a very similar result. It's a matter of developer choice and preparing for future GWT releases (I.e. being future-proof).
(note that I'm not blaming the g-leaflet author either)

Very last point: the conversion has limitations and apparently a small bug around literal() (removed the quotes in `-ms-filter` value, where literal() wasn't actually needed BTW), thus is true. But automatic translation is supposed to be an aid during migration, not the way people are supposed to use it in production. Just do the conversion once, fix the errors and provide the GSS (alongside the CSS for backward compat)

**Comment by jnehlmeier** [comment]
@GwtarPlayer The following CSS rule
```css
filter: progid:DXImageTransform.Microsoft.Matrix(M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678);
```
is invalid CSS 2 and invalid CSS 3 syntax. The only way to make that work with Closure Stylesheets (GSS) is to add quotes. However when doing so I am pretty sure that IE6/7 will not apply the filter anymore. So it is impossible to convert that CSS rule to something that continues to "just work". Also the conversation process would need to check if the value of the filter rule is valid or invalid CSS in order to decide to add quotes or not which adds unnecessary/useless complexity.

Because of that the conversation process of GWT assumes that all input (also the input contained in `literal(...)`) is valid CSS syntax. If its not valid syntax it is better to produce an error and let the library maintainer decide whats best to do (e.g. releasing as second version of that library without IE6/7 support but with support for newer GWT versions that use GSS, or generally rewriting the CSS to avoid the problematic CSS rules).

The only valid point you have is that the conversation process incorrectly removes quotes while "unpacking" the content of `literal(...)`. In case of Leaflet that happens with the `-ms-filter: literal('"..."')´ rule. That is something we can and should fix, but still you would have the error for the invalid CSS rule mentioned above.

I hope that is clear now.

**Comment by GwtarPlayer** [comment]
@jnehlmeier:

Yes, that is/was invalid. They fixed/replaced that with literal(...), which makes it valid.This valid syntax is not handled by GWT. 

I'd be OK with filter/progid stuff not working as it is not a supported browser. That is fine. The problem is that nothing works at all. There should be no errors at all with the litera(...) wrapper.

**Comment by gkdn** [comment]
I didn't follow all the conversation but just want to emphasize that our automatic conversion is best effort though we usually avoid doing unsafe stuff if not in lenient mode.

@jDramaix Can you check the thread and see if we need any improvements here? We should not go out of our way but if there are some quick fixes that will improve the experience we can consider those.

**Comment by GwtarPlayer** [comment]
We would be happy (happiest, in fact), to move on with "strict". However, like many, we do use third party libraries. As it stands right now, there is too much risk to enable GSS with any third party library of any kind. Even if it may seem to work, a problem may be lurking somewhere and/or upgrade path is compromised.

Ideally each module could independently choose whether they are CSS or GSS. I personally don't need (or believe in) "lenient".

**Comment by mstahv** [comment]
Not sure if I should be sorry for the hassle I have caused by using CssResource in https://github.com/mstahv/g-leaflet or proud about bringing up the issues with the new changes :-) Some comment from me:

 * I'm personally using g-leaflet only through v-leaflet, its [Vaadin wrapper](https://vaadin.com/directory#!addon/v-leaflet). I hadn't noticed the backwards incompatibility and haven't recently followed GWT development that actively that I could haven noticed this kind of breaking change.
 * Yes, it really is nasty when backwards compatibility is broken. Not every users want to upgrade for each and every release, and in some cases, it is not even possible. Backwards compatibility is important, especially for stuff that is used by library developers. Still, as an old GWT and Vaadin contributor, I think some backwards incompatible changes must be done not to stall the development. This may or may not be such a case. I have to admit, I have never used GSS and don't know the value it brings in over the old GWT's own CSS stuff, but intuitively, I think I would have brought in GSS support in the way suggested by @GwtarPlayer, so that those who know they want GSS get the good parts of it and no nasty regressions for existing users.
 * @tbroyer, I couldn't have used plain text resource. I also embedded some small images used by Leaflet to the GWT module.
 * Any change I'm willing to pull in to g-leaflet, *must be backwards* compatible, as I'm personally using it only through a Vaadin integration library called v-leaflet and Vaadin is not using the latest version of GWT.
 * Dropping IE6 (filter function) support form g-leaflet project is just fine for me if it makes g-leaflet compatible with the latest version of GWT. @GwtarPlayer or @gxtUser, can you try and give me a pull request?

**Comment by GwtarPlayer** [comment]
I understand the need to sacrifice some compatibility when moving forward and it is necessary. In this case I don't see this as a necessity at all, as GSS is just an enhancement around CSS anyway, so passing some CSS through should not be an issue at all - we just need to have a way to do so. Right now that is not possible. As we only have the ability to declare the entire product (combination of modules, libraries) to be GSS or not (and is planned to default to GSS in GWT 2.8) we do depend on GSS being able to work with all the modules/libraries we have in that product. GSS is not safe in this respect. 

a) GSS is unable to safely import/embed "old" CSS without risk of it being interpreted as something it isn't, thus breaking it.

b) There is no way that a module/library publishes the fact that it is CSS or GSS so that it can be treated properly. This, could, however, simply be done via filename extension.

c) There is no way to declare an imported module/library compatible or not so that the clients can control this.

d) There is no way to guarantee ability to change 3rd party library.

@mstahv: Thank you for your offer. That *could* help but you need to tell me in more detail what you want me to do. However, that would not solve the actual problem.

**Comment by tbroyer** [comment]
@GwtarPlayer: @jDramaix will correct me if I'm wrong but:

 * GSS needs to be in `.gss` files. You can have GWT automatically convert `.css` to `.gss` but there are limitations.
 * you can provide both a `.css` and a `.gss` and GWT will pick the appropriate one depending on which "mode" it's asked to use.

There there **is** a way to solve your problem: simply provide a `.gss` of the stylesheet, and you can do that in your own app (given that GWT loads things from the classpath) so you're not even forced to wait for a new release of g-leaflet.
As to how to create that `.gss` to begin with, as I said above, use Css2Gss (from gwt-user.jar or online) and then tweak the result if/as needed (in the case of g-leaflet, re-add quotes around the `-ms-filter` value and remove the `filter` property entirely).

**Comment by GwtarPlayer** [comment]
@tbroyer: That is a workaround, not a fix. We can't do that for every library we use, every time we update it. The reason we use libraries is to avoid doing extra work, not to make more of it. Again, don't get hung on the specific example of Leaflet. That is just one example. The concern is that, with GSS in place, there can be no easy wrapping of ANY non-GWT JavaScript library are all. This is not just about backwards GWT compatibility. It is about ANY past, present pr forward compatibility with JavaScript+CSS libraries.

**Comment by tbroyer** [comment]
> The concern is that, with GSS in place, there can be no easy wrapping of ANY non-GWT JavaScript library are all. This is not just about backwards GWT compatibility. It is about ANY past, present pr forward compatibility with JavaScript+CSS libraries.

I don't get how you can conclude this.

The concern is about `CssResource`, which:
 * is an opt-in for any "wrapper"  (they can use `TextResource`, or put the resources in the "public path", or just ask users to include the stylesheets in the HTML host page by themselves, either directly or through `StyleInjector`)
 * already wasn't "easy" with GWT-CSS given the limitation to CSS2 syntax; so it required modifications to the stylesheet to add `literal()` here and there; doing the same with GSS amounts to only making sure the stylesheet uses CSS3 syntax (i.e. delete any `filter`)

The concern is also only about a migration period between the old GWT-CSS syntax and the GSS one. Libraries could be future-proofed starting a year ago by providing both CSS and GSS versions of the stylesheet, and users of those libraries that would like to opt into using GSS without waiting for library updates can workaround it by providing the GSS version themselves (and hopefully contribute it upstream).
The migration period started a year ago and will not end with GWT 2.8's release as, even if GSS is made the default, it could still be disabled. This means the migration period will last at least 18 months from GWT 2.7's release (as I don't expect a new GWT release removing the old GWT-CSS syntax before at least 6 months).

> We can't do that for every library we use, every time we update it.

Unless the library author is a jerk, you would only have to do it once (and contribute the fix upstream so you get it the next time the library has a new release; this is how OSS works, or at least should work). Relying on third-party dependencies is relying on other people's good will to keep their work up-to-date (or at least accept patches); this has indeed strong implications to your codebase.

**Comment by GwtarPlayer** [comment]
Coming back to a simple example - Leaflet.js is not subject to GWT timelines. It is a JavaScript library. It is valid. "Migration period" does not apply to them. There is nothing for them to "future proof" more than they already did. Again, this is just one example.

With respect to: "Unless the library author is a jerk, you would only have to do it once (and contribute the fix upstream so you get it the next time the library has a new release; this is how OSS works, or at least should work)." ... that is NOT how it works.

a) We cannot simply "contribute" things - they need to be welcome and approved.

b) They may not welcome or approve the change, which is exactly the case with the Leaflet example.

c) Such changes require understanding and certain level of expertise that may not be there. This is one of the reasons why we use libraries.

d) None of the above prevents a problem from being reintroduced at any point, as development and testing is not done with GWT in mind.

**Comment by tbroyer** [comment]
Why would you contribute anything to Leaflet.js?!
The "issue" is in g-leaflet, **not** in Leaflet.js "the original". To build g-leaflet, @mstahv makes a copy of Leaflet.js and adapts it as a `CssResource` (for instance adding `literal()`, but not only).
There's no valid reason the author of a GWT library (whether it's a wrapper or other "adaptation" of a pure-JS lib, or a pure-GWT lib, or anything in between) would reject a contribution that makes it compatible with new GWT features without breaking backwards compatibility; at least not on the ground of what it brings to the table (there are many other reasons to reject a contribution, but I can't see any valid reason to reject the enhancement request)

**Comment by GwtarPlayer** [comment]
@tbroyer: Because authors of wrapper libraries are in the same boat. They would want to make the fix at the source and not have to re-make it with every new update. So moving the hot potato just half way is not really the solution.

**Comment by tbroyer** [comment]
> Because authors of wrapper libraries are in the same boat.

You're raising an issue about automatic conversion of old GWT-CSS syntax to GSS failing in some cases (which is not unexpected to begin with). This is very GWT-specific, and only happens if you (or whoever) choose to use `CssResource`. And as I said, it should be much easier to wrap any third-party CSS as GSS than as GWT-CSS, simply because GSS is CSS3 whereas GWT-CSS was CSS2 only.
You'd have the same problem with any CSS-processing tool that only accepts valid/wellformed CSS as input and would thus reject the `filter` property. For example, if you'd like to use the Leaflet CSS as an input to LESS, [you'd have an error too](https://github.com/less/less.js/issues/734) and would have to modify the CSS (either removing the `filter` property or use the `~""` notation which is equivalent to the GWT-CSS `literal()`); same with [Stylus](http://stylus-lang.com/docs/literal.html)
And once again, that tool is an opt-in that you're (a library author in this context) absolutely free to **not** use.
So no, author of wrapper libraries are not "in the same boat"; they make a conscious choice to use `CssResource` with a third-party stylesheet as input and that has a few consequences.

**Comment by gkdn** [comment]
The main goal of the tool is *not* to keep long term backwards compatibility; just to help out with the GWT-CSS to GSS migration.
The tool converted all Google GWT-CSS with small amount of interference and we are releasing it with GWT together with a doc that describes the migration approach that worked for us. We are thinking this will help other developers on their migration as well. However, for any reason if the auto-migration tool or the steps doesn't work for you, don't use it; it is *not* mandatory.

- If you have some CSS that you don't want to make any changes and doesn't work with GSS based CssResource; you can keep using GWT 2.8 which will the last version that will support old GWT-CSS syntax as a CssResource input.

- If you have a library that you want to keep support with multiple versions of GWT, you can supply both CSS and GSS files (assuming cannot supply a single file that is compatible with both).

- If somebody has a 'simple' patch that will make any of these steps/tools work better (e.g. expose ), feel free to send the patch.

- In this particular case, I saw only one real issue which is not providing a configuration property to allow undefined constants in GSS which will help more CSS to be used as-is. Please feel free to send a patch for that. To get you started, looks like the option should be passed to ReplaceConstantReferences (GssResourceGenerator.java:915).

**Comment by jDramaix** [comment]
Sorry, I'm late in this thread. 

- it would have taken less energy and time to simply fix the css and remove the "filter" lines that are useless now. The automatic conversion doesn't work because the resulting css contains invalid CSS3 syntax. By fixing the library, you make things moving forward. 

- As @gkdn mentioned it, you can decide to continue with the old GWT-CSS syntax in GWT 2.8. GSS is not turned on by default and the main reason was to provide a smooth transition to GEWT 2.8. In terms of backward compatibility, we cannot do more.

- GSS introduced recently a concat() function that could be potentially used to replace the literal() function in this case.

> In this particular case, I saw only one real issue which is not providing a configuration property to allow undefined constants in GSS which will help more CSS to be used as-is. Please feel free to send a patch for that. To get you started, looks like the option should be passed to ReplaceConstantReferences (GssResourceGenerator.java:915).

That could be indeed a good contribution.

**Comment by GwtarPlayer** [comment]
It is less energy in one instance. I am not worried about that. My concern is ongoing risk of trouble with other libraries. Note that we can't "fix" the source in this case (Leaflet library) - they don't want it modified in this manner as it is valid for them. Changing this in g-Leaflet is also possible but that places the responsibility on g-Leaflet developers to keep the change up-to-date. Whereas g-Leaflet may legally do this, depending on licencing details, developers of other wrapper libraries may not be able (allowed) to.

I am not sure that treating "undefined constances" as-is would be helpful:

a) They may truly be undefined and should indicate an error. Instead, this may hide an error and it may be hard to find (i.e. may go unnoticed for a while)

b) It sounds like it would also continue treating things that look like constants but aren't (because they come from a file that knows not of them) and hit an existing constant.

**Comment by jDramaix** [comment]
>  Changing this in g-Leaflet is also possible but that places the responsibility on g-Leaflet developers to keep the change up-to-date.

They must already keep the change up-to-date as they opt for a CSSResource interface and introduce the `literal()` function in the css.

**Comment by jDramaix** [comment]
> I am not sure that treating "undefined constances" as-is would be helpful:
a) They may truly be undefined and should indicate an error. Instead, this may hide an error and it may be hard to find (i.e. may go unnoticed for a while)
b) It sounds like it would also continue treating things that look like constants but aren't (because they come from a file that knows not of them) and hit an existing constant.

What @gkdn meant, is to add the ability to define a property configuration in the gwt.xml files in order to ignore several undefined constants:

```xml
<set-configuration-property name="CssResource.undefinedConstants" value="M11,M12,M21,M22" />
```

**Comment by gkdn** [comment]
I was thinking about the configuration property but actually my last comment was to introduce an on/off flag to stop complaining about it. Such a flag is already available in GSS and is couple of lines to add in GWT as well.
Even the flag is set, the parser may still generate a warning (somebody needs to check that). Yes, it is unsafe and should be off by default but it provides a way out for people who would like to use some old CSS "as it is" as you requested earlier.

**Comment by GwtarPlayer** [comment]
May I ask, why is it a problem to treat things coming from CSS as literals - if not all of them then at least those that are literal(...) already? I understand that there really are three versions of "CSS":

a) Pure CSS
b) GWT-enriched CSS with@def, @eval , etc.
c) GSS

The way I see this is:

Stuff from (a) should always be treated quite literally. If CssResource is used for this it may be the cause of confusion, as per above discussion. In that case it would be nice to give something that behaves like a CssResource with the exception of constant references and related. Libraries that use pure CSS can be updated when needed - i.e. when a problem is discovered. This would be OK.

Stuff from (b) may be a constant reference, I will leave it up to you to decide whether it is better for those to be scoped to just the CSS stuff or can it reference GSS constants too (and vice versa).

Stuff from (c) is just stuff from (c) - nothing to it.

**Comment by dankurka** [comment]
If you are unhappy with processing of invalid CSS in GSS do not use it. We want GSS to be strict and fail compile if you have invalid CSS, its as simple as that. If you want to use invalid CSS use a link tag (or a Textresource instead)
