### ISSUE TITLE
Eclipse Project => Deployment Assembly or Equivalent for GWT Web Application?

### ISSUE THREAD

**Issue by gwtuser** [gwtproject/gwt#9276]
We use Eclipse for GWT development.  We have several existing projects that are defined as GWT Web Applications and are run via the GWT Plugin in either Super or Classic Dev Mode.  We've found a problem which is that our project build path (.classpath) refers to JARs at various locations outside the WEB-INF/lib directory, but running (Super)DevMode via the plugin doesn't copy those JARs to WEB-INF/lib.  The result is that the app fails out with ClassNotFound exceptions.

In a "normal" Eclipse Java Project, say one defined as a "Dynamic Web Module," you can configure part of the project properties called "Deployment Assembly" to copy the JARs you want to WEB-INF/lib.  Indeed, if I define and run the GWT CodeServer separately, and deploy the app to Tomcat or Jetty manually using a Dynamic Web Module project I can solve it that way.

However, I'd like to use the built-in jetty server for GWT SDM since that's what our customers will do.  How can I achieve what I need?  Obviously, the files can be copied by hand in the OS, and that's what we do now, but I'd like a better solution.  I'm also aware that Maven and/or IvyDE have the potential to solve this, but I'm not interested in adding Maven or Ivy to the equation just to solve this issue.

Can someone tweak the GWT Plugin source defining a Web Application to enable "Deployment Assembly," and make sure it's triggered when the GWT Plugin is used to run (Super)DevMode?

Note, I've already tried manually adding the appropriate configuration to the .classpath XML file that gets added when you tinker with the Deployment Assembly page, but it doesn't work.  I assume this is because the "run" button of the GWT Plugin doesn't trigger the critical logic that reads and acts upon the extra .classpath config data.  This critical logic, however, clearly does run if you tell Eclipse to deploy a Dynamic Web Module to Tomcat (for example).

Thanks.

**Comment by branflake2267** [comment]
If you're defining a dynamic web module, I think you'll find it's better to use the CodeServer entry point and use the web server separately. (See video in link, on how to do this). The code server will run as a separate instance next to your web server instance. Well, that is if you're running the web server with Eclipse too. Since the code server doesn't have to be restarted, both the web server and code server can run in parallel. There isn't a need to stop and start the instance like classic dev mode. Running the WTP web server, should be able to do more than running the internal jetty instance that is booted up in Dev Mode. 

Running a tomcat web server with a code server. I think this also shows using -src for adding external source entries as well. 
http://gwt-plugins.github.io/documentation/gwt-eclipse-plugin/servers/Tomcat.html

If you watched the video in the link I provided you'll find that you can run the server and it automatically runs the code server as a separate instance.

**Comment by tbroyer** [comment]
@gwtuser As you yourself noted, this is not an issue with GWT proper, but the plugin for Eclipse. There are two versions, and each has its issue tracker (but only gwt-plugin is actually maintained I believe) @branflake2267 will direct you where appropriate (issue tracker, forum, gitter, whatever)

**Comment by gwtuser** [comment]
As I mentioned in the original report, I'm aware CodeServer can be run separately, and know how to do that, but I'd prefer not to.  Our customers want to launch using the integrated jetty server provided by the GWT Plugin.  Our customers also use Classic Dev Mode on a regular basis (yes, even though it requires an old browser), and I'm guessing that will require a separate solution under such an approach.

I guess the issue can't be reassigned - I have to create a new one under the plugin, and then copy & paste?

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/137
