### ISSUE TITLE
Wrong Math.expm1 

### ISSUE THREAD

**Issue by jufeel** [gwtproject/gwt#9331]
Line 148 of gwt/user/super/com/google/gwt/emul/java/lang/Math.java

I think we should return 
`exp(d) - 1.0d`

instead of
`exp(d) + 1.0d`

**Comment by tbroyer** [comment]
Want to provide the patch? (ideally with unit tests too)
http://www.gwtproject.org/makinggwtbetter.html

**Comment by jnehlmeier** [comment]
Hmm isn't the method broken anyways? 
```java
public static double expm1(double d) {
    if (d == 0.0 || Double.isNaN(d)) {
      return d; 
    } else if (!Double.isInfinite(d)) { // strange negation? Will match any finite input
      if (d < 0.0d) {
        return -1.0d;
      } else {
        return Double.POSITIVE_INFINITY;
      }
    }
    return exp(d) + 1.0d; // should be - 1
  }
```
The `else if (!Double.isInfinite(d))` and the implementation of that `else if` block doesn't really make sense, does it? That would give me `+infinity` for any positive, finite input and `-1` for any negative input which is wrong. It would make more sense to delete the negation as these are the special cases for infinite input. However `exp(d) - 1.0d` will handle that as well because `exp(+Infinity) - 1 => +Infinity` and `exp(-Infinity) - 1 => -1`. So overall I think the `else if` should be deleted (or corrected if we want to give GWT compiler a bit more room for optimization)

**Comment by gkdn** [comment]
NaN check is also not needed. Final code could be as simple as:

```java
  return d == 0.0 ? d : (exp(d) -1));
```

**Comment by jnehlmeier** [comment]
https://gwt-review.googlesource.com/#/c/14874/
