### ISSUE TITLE
MethodReference type/method collision due to generics

### ISSUE THREAD

**Issue by niloc132** [gwtproject/gwt#9333]
Fails as of 5be1d83, I'm surprised by this, since this kind of code surely has worked before now.

A simple test case that reproduces this runtime bug:

```
public class MethodReferenceBug implements EntryPoint {
    @Override
    public void onModuleLoad() {
        createAndAdd(ArrayList::new, MethodReferenceBug::addAll);
        createAndAdd(HashSet::new, MethodReferenceBug::addAll);
    }
    private static <T, C extends Collection<T>> C createAndAdd(Supplier<C> ctor, BiFunction<C, Collection<T>, C> append) {
        return append.apply(ctor.get(), ctor.get());
    }

    private static <T, C extends Collection<T>> C addAll(C collection, Collection<T> items) {
        collection.addAll(items);
        return collection;
    }

    public interface Supplier<T> { T get(); }

    public interface BiFunction<A, B, C> { C apply(A a, B b); }
}
```

Run it, and you get a ClassCastException.

Compiling to PRETTY results in the following snippets:

```
function init(){
  $wnd.setTimeout($entry(assertCompileTimeUserAgent));
  $onModuleLoad();
  createAndAdd(new sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_ArrayList$$ArrayList__V$Type);
  createAndAdd(new sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_HashSet$$HashSet__V$Type);
}
//...
function createAndAdd(ctor){
  return $apply(ctor.get_1(), ctor.get_1());
}

function $apply(a, b){
  return addAll(castTo(a, 13), b);
}

function sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_ArrayList$$ArrayList__V$Type(){
}
defineClass(25, 1, {}, sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_ArrayList$$ArrayList__V$Type);
_.get_1 = function get_2(){
  return new ArrayList;
};
//...
function sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_HashSet$$HashSet__V$Type(){
}
defineClass(26, 1, {}, sample2_client_MethodReferenceBug$$__$$sample2_client_MethodReferenceBug$Supplier$$__$$static$$java_util_HashSet$$HashSet__V$Type);
_.get_1 = function get_3(){
  return new HashSet;
};

//...

var Ljava_util_ArrayList_2_classLit = createForClass('java.util', 'ArrayList', 13);

```

Apparently in `MethodReferenceBug.addAll`, `<C extends Collection<T>>` `C`'s `Collection.addAll` gets specialized for just `ArrayList` (aka `13`), and so subsequent use by a HashSet breaks it.

**Comment by niloc132** [comment]
Any more detail required here?

For those running into this, as with the other method reference bugs, it works to just replace the method reference with a lambda that does the same thing. However, this is not a very satisfactory solution in general, since we won't see this exception until runtime to know where it must be applied.

        createAndAdd(ArrayList::new, MethodReferenceBug::addAll);
        createAndAdd(HashSet::new, MethodReferenceBug::addAll);

to

        createAndAdd(ArrayList::new, (a, b) -> addAll(a, b));
        createAndAdd(HashSet::new, (a, b) -> addAll(a, b));

**Comment by ibaca** [comment]
Relates to https://github.com/gwtproject/gwt/issues/9307

**Comment by niloc132** [comment]
I'm not sure how related it actually is, since #9307 was about referencing methods that have overrides, whereas this is about a method being specialized even though at least one reference should forbid this.

**Comment by axls** [comment]
Some investigation...
when I changed line 1878 in com.google.gwt.dev.jjs.impl.GwtAstBuilder.AstVisitor.endVisit(ReferenceExpression, BlockScope)
from 
`destParam = referredMethodBinding.parameters[paramNumber];`
to
`destParam = referredMethodBinding.original().parameters[paramNumber];`
error described here are gone.
This change leads to use of the declared type (Collection) instead of concrete (ArrayList) in method's call. So next generated code:
```
function $apply(a, b){
  return addAll(castTo(a, 13), b);
}
```
will be changed to:
```
function $apply(a, b){
  return b.addAll(a), b;
}
```

I didn't check other paths with referredMethodBinding.parameters, but probably they need to be reviewed too.

I can create PR with tests if this change is reasonable.

@rluble, @gkdn 
What do you think?

**Comment by rluble** [comment]
I think the problem is more general, but I have to think about it more
deeply. In principle the two instances of MethodReferences that appear in
the example are typed differently, so one semantically correct
implementation would create 2 different implementations. Each
implementation would do the appropriate cast, as it is done when bridging
generics. I'd have to think whether the solution you propose, where no
casts are performed, is sound.

**Comment by rluble** [comment]
Could you check if this still happens at head?

**Comment by axls** [comment]
I'm still getting CCE for this case.

**Comment by rluble** [comment]
Review at https://gwt-review.googlesource.com/#/c/15000

**Comment by rluble** [comment]
The actual problem was not an optimization (tightening) bug (and was present in -draftCompile as well). 

The main issue is that method references to the same method (with the same qualifier situation) would be implemented by a single anonymous inner class (in an attempt to share implementations). But it turns out that generics instantiation might require different implementations as this case illustrates.

**Comment by axls** [comment]
Thanks for the patch. I can confirm, that this one fixes the issue.
And maybe it will be helpful... next snippet could be used to test issue when placed in `<gwt>/user/test-super/com/google/gwt/dev/jjs/super/com/google/gwt/dev/jjs/test/Java8Test.java`:
```java
...
import java.util.function.BiFunction;
import java.util.function.Supplier;
...
  static class Issue_9333 {

    public List<Object> foo() {
      List<Object> collection = new ArrayList<>();
      collection.addAll(createAndAdd(ArrayList::new, Arrays.asList("1"), Issue_9333::addAll));
      collection.addAll(createAndAdd(HashSet::new, Arrays.asList(2), Issue_9333::addAll));
      return collection;
    }

    private static <T, C1 extends Collection<T>> C1 createAndAdd(Supplier<C1> ctor, C1 items,
        BiFunction<C1, Collection<T>, C1> append) {
      return append.apply(ctor.get(), items);
    }

    private static <T, C1 extends Collection<T>> C1 addAll(C1 collection, Collection<T> items) {
      collection.addAll(items);
      return collection;
    }
  }

  public void testMethodReference_issue_9333() {
    List<Object> list = new Issue_9333().foo();
    assertEquals(list.size(), 2);
    assertEquals(list.get(0), "1");
    assertEquals(list.get(1), 2);
  }
...
```
