### ISSUE TITLE
Problem with index.html path using Jetty

### ISSUE THREAD

**Issue by BenDol** [gwtproject/gwt#9350]
Currently when I run a project using `mvn gwt:run` which starts the codeserver then close that instance and open a new project using the same command I receive this problem:

`http://127.0.0.1:8888/gwtmaterialdemo/gwtmaterialdemo.nocache.js Failed to load resource: the server responded with a status of 404 (Not Found)`

In this case I started by running `gwtmaterialdemo` project, then closed it and opened a new project called `jsinteropissue`. For some reason its trying to invoke the previous projects index.html rather than the new project I am starting. The way I have been working around this is removing the `/index.html` from the end of the URL and it will start compiling the new project and loads it correctly.

Using GWT 2.8.0-SNAPSHOT

Not sure what is wrong but it seems like an issue. Thanks!

**Comment by BenDol** [comment]
Any light can be shed on this issue? Keep having the problem and sometimes removing the `index.html` doesn't solve it and I have to spam the refresh button until it loads the correct html for the project. Seems like a super dev mode issue?

**Comment by jnehlmeier** [comment]
Maybe the browser simply caches your index.html page because the URL is the same for both projects, e.g. `http://127.0.0.1:8888/index.html`?

**Comment by BenDol** [comment]
Happens even if i change browsers, so I assume that isn't the case.

**Comment by tbroyer** [comment]
Could you somehow confirm it's not a caching issue?
(open browser dev tools, look at the request; if it goes out with a `If-Modified-Since` and the server responds with a 304, then it's a caching issue; if the server responds back with the wrong page then it's a GWT issue; also try disabling cache in the browser dev tools, or –with browser dev tools open– hit Ctrl+R to do a "force refresh" bypassing the browser cache)

**Comment by BenDol** [comment]
Yeah seems it is a cache issue:
```
Request URL:http://127.0.0.1:8888/index.html
Request Method:GET
Status Code:304 Not Modified
Remote Address:127.0.0.1:8888
Response Headers
view source
Date:Wed, 09 Nov 2016 04:39:15 GMT
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:JSESSIONID=227o6e1d1n171szym4pui0qv8; _gat=1; color=brown; _ga=GA1.1.1125996845.1478665961
Host:127.0.0.1:8888
If-Modified-Since:Mon, 07 Nov 2016 23:55:20 GMT
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1
```
How do I resolve this? My index.html doesn't have any meta tags to determine caching.

**Comment by tbroyer** [comment]
> How do I resolve this?

Some suggestions:
 * "touch" your `index.html` to update its mtime and defeat the `If-Modified-Since`
 * force-refresh in your browser
 * disable caching in your browser
 * set an `initParam` in your `web.xml` with name `org.eclipse.jetty.servlet.Default.etags` and value `true` to turn on ETags in Jetty's default servlet; the ETag is computed from the mtime and length of the file, so is unlikely to be equal between projects, and it is matched by equality comparisons (contrary to `If-Modified-Since` which, as its name suggests, determines whether the header value is before the mtime)

**Comment by BenDol** [comment]
Perhaps this should be a default behavior for the default Jetty server?

**Comment by tbroyer** [comment]
It could (feel free to provide the patch, it should be a one-liner in `JettyLauncher`), but you'd also face it if you use any Jetty server with its default configuration (including `mvn jetty:run`), so…
