### ISSUE TITLE
Using lambdas in JsOverlay methods produces 'lambda$0 is not a function' error

### ISSUE THREAD

**Issue by vtsaplin** [gwtproject/gwt#9354]
When using lambdas in overlay methods in native JsTypes I am getting this error:

> SEVERE: (TypeError) : $wnd.GoldenLayout.lambda$0 is not a function
> com.google.gwt.core.client.JavaScriptException: (TypeError) : $wnd.GoldenLayout.lambda$0 is not a function

This method works:

```
    @JsOverlay
    public static final void test1() {
        int[] a = new int[1];
        Scheduler.get().scheduleDeferred(new Scheduler.ScheduledCommand() {
            @Override
            public void execute() {
                a[0] = 2;
            }
        });
    }
```

But this doesn't:

```
    @JsOverlay
    public static final void test2() {
        int[] a = new int[1];
        Scheduler.get().scheduleDeferred(() -> a[0] = 2);
    }

```

**Comment by rluble** [comment]
code review at https://gwt-review.googlesource.com/#/c/15020/

**Comment by rluble** [comment]
The issue here is that lambdas are implemented in the following way. The code for the lambda function is implemented by a static method in the declaring class and then the lambda itself is an anonymous inner class where the SAM method delegates to the static method in the declaring class.

When the declaring class is Native such method is defined in an inconsistent way. The fix in the current review is marking that method as a JsOverlay but this is far from ideal. A better implementation would be to define the static method in the anonymous inner class itself.
