### ISSUE TITLE
Finalize JsOptional vs. JsNotNull

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9370]
If we decide to drop JsOptional in favor of JsNotNull, we should decide that before 2.8 so we can remove references from JsInteropRestrictionChecker.

**Comment by gkdn** [comment]
Ok, decided to remove the restriction checking so when (if) the annotation is removed, GWT will not be broken.

**Comment by jnehlmeier** [comment]
Just curious: why do you favor JsNotNull? Isn't it more practical to assume every parameter is not null unless marked to be optional/nullable?

Even in normal Java code I would always use `javax.annotation.@ParametersAreNonNullByDefault` on a package and then add `javax.annotation.@Nullable` here and there.

**Comment by cromwellian** [comment]
Null and optional aren't the same unless you implement a heuristic that
trailing nulls are optional, e.g.

/**
  * @param {!Object} a
 * @param {Object=} b
  */
function foo(a,b) {
}

foo(a) and foo (a,b) accepted

/**
  * @param {!Object} a
 * @param {?Object} b
  */
function foo(a,b) {
}

foo(a) rejected, foo(a, null) accepted

// with trailing nulls are automatically optional heuristic
/**
  * @param {!Object} a
 * @param {?Object} b
  */
function foo(a,b) {
}

foo(a) accepted, foo(a, null) accepted

but this example

// with trailing nulls are automatically optional heuristic
/**
  * @param {?Object} a
 * @param {!Object} b
 * @param {?Object} c
  */
function foo(a,b,c) {
}

must be called as foo(null, b), since 'a' can't be optional

**Comment by gkdn** [comment]
@jnehlmeier we haven't decided if we will have JsNullable or JsNotNull (I think that this your question?).

I favored JsNotNull initially because I want people to understand the code when they look at the code. In Java, the developer needs to assume that everything could be null (everything is nullable by default) since there are no guarantees (unless they use a framework that enforces different semantics). I think it is confusing to flip the default when you switch to a @JsType class and consider everything is non-null by default.

Also keep in mind in Java; every other framework comes with their own semantics and there is no common way to change nullability default for all. For example, checker framework assumes non-nullable by default for fields and parameters but then use different rules for local variables, casts, generics etc and not all of them configurable.

Anyway, there are two camps for this and we haven't finalized it yet.

**Comment by rluble** [comment]
@cromwellian, your assumption is correct @JsNotNull would be sufficient if we treat trailing nullables as optional. We are still discussing whether this simplification makes sense or not.

**Comment by gkdn** [comment]
Verified that removal of JsOptional from jsinterop package doesn't break GWT. Closing the bug.
