### ISSUE TITLE
SymbolMaps are missing in war file after superDev mode compilation

### ISSUE THREAD

**Issue by YuryVedeev** [gwtproject/gwt#9374]
It is standard for GWT to have symbolMaps if compiler.useSourceMaps flag is enabled in gwt.xml.  Please see http://www.gwtproject.org/javadoc/latest/com/google/gwt/core/server/StackTraceDeobfuscator.html : 
"By default, the final symbolMaps directory is war/WEB-INF/deploy/yourmodulename/symbolMaps/". 

Required symbolMaps are generated during gwt superDev mode compilation, e.g. I observe required symbolMaps in somePath\extras\someModule: 
"Compilation succeeded – 45,054s 
Linking into C:\Users\someUser\AppData\Local\Temp\gwt-codeserver-7806153466341912339.tmp\someModule\compile-2\war\nsdescriptorview; Writing extras to C:\Users\someUser\AppData\Local\Temp\gwt-codeserver-7806153466341912339.tmp...\compile-2\extras\someModule 
Link succeeded 
Linking succeeded – 1,371s" 
At this point everything is OK.

But after compilation, when jetty local server is started its WEB-INF\someModule\symbolMaps folder is empty. 
But required symbolMaps should be placed there.

I suspect that problem is in https://gwt.googlesource.com/gwt/+/master/dev/codeserver/java/com/google/gwt/dev/codeserver/LauncherDir.java in update method: I don't see any symbolMaps copying routine  there.

**Comment by jnehlmeier** [comment]
Thats a known issue: https://github.com/gwtproject/gwt/issues/7690

During development with SDM I usually use a different UncaughtExceptionHandler that does log the exception into the browser console instead of remote logging it on the server. 

With GWT 2.8 beta1 or SNAPSHOT you will see understandable stack traces in Chrome console with source maps applied by Chrome. You can even click on the stack frame and Chrome will jump to the (source mapped) Java file.

With GWT 2.7 a lot of conditions must apply in order to see the same understandable stack traces (compiler.stackMode must be the default value of "native", you must not inherit Logging.gwt.xml nor LoggingDisabled.gwt.xml, but still you must use java.util.Logger to log the exception). Because of this I copied the code from GWT: https://gist.github.com/jnehlmeier/cddbc476fd330b1d4999 (only works with GWT 2.7 !)

To detect wether or not you are in SuperDevMode you can use
```
public static boolean isSDM() {
  return GWT.isScript() && !GWT.getModuleBaseForStaticFiles().equals(GWT.getModuleBaseURL());
}
```
