### ISSUE TITLE
java.lang.NullPointerException during string compare

### ISSUE THREAD

**Issue by smitzkus** [gwtproject/gwt#9386]
Commit fc52b53df925608884b27b8c12490818771d69ff by @nordligulv added null checks to String methods, e.g.

```
  @Override
  public int compareTo(String other) {
    return JsUtils.compare(checkNotNull(this), checkNotNull(other));
  }
```
Because of this change, my compare methods build with the guava ComparisonChain don't work anymore, e.g.

```
    @Override
    public int compareTo(User o) {
        return ComparisonChain.start().compareFalseFirst(this.internal, o.internal).compare(this.login, o.login).result();
    }
```
If login of a user is null, the method ends up with a java.lang.NullPointerException. 
I think that many people who make use of the ComparisonChain will get the same problem. Are there any workarounds?

**Comment by jnehlmeier** [comment]
Your code is broken anyway. 

If your `login` variable can be `null` then `ComparisonChain` will already fail with NPE as it calls `left.compareTo(right)` for `Comparable` types. `left` might be `null` and the `Comparable` type might not support `null` as input, e.g. when `right` is `null`. So you can not use `ComparisonChain.compare(Comparable, Comparable) with nullable variables. You have to provide a comparator that knows how it should treat `null`. Using Guava you could do
```java
    @Override
    public int compareTo(User o) {
        return ComparisonChain.start()
            .compareFalseFirst(this.internal, o.internal)
            .compare(this.login, o.login, Ordering.natural().nullFirst())
            .result();
    }
```

The change in GWT now better reflects the behavior of JRE. Your code only worked accidentally, because GWT compiler most likely has inlined `left.compareTo(right)` and GWT emulation did allow `String.compareTo(null)` to succeed.
