### ISSUE TITLE
Unexpected internal compiler error: java.lang.AssertionError

### ISSUE THREAD

**Issue by ruslansennov** [gwtproject/gwt#9406]
It seems something wrong with GWT compiler.
[Here](https://github.com/ruslansennov/gwt-test) is showcase to reproduce the problem  (also output of `mvn test`).
And this is results of @tbroyer's investigations:

> Apparently, the problem is that GWT doesn't detect that `Function1::curried` overrides/implements `λ::curried`. The problematic type is a synthetic type generated for the `List::ofAll` method reference, which is final; so it's specific to using a lambda or method reference to represent a `Function1`, whose curried method is not seen as overriding `λ::curried` (note: this is dependent on the order of the methods in λ; moving `memoized` before `curried` would change method causing problem; but note that `arity` is not a problem, so it's either related to generics, or covariant return types, or both)

**Comment by tbroyer** [comment]
@rluble: to reproduce without Maven, use the following commands on the repro case repository:
```sh
$ javac src/main/java/javaslang/*.java
$ javac -cp src/main/java:$GWT_ROOT/build/lib/gwt-user.jar:$GWT_TOOLS/lib/junit/junit-4.8.2.jar src/test/java/client/GwtTestCollections.java
$ java -ea -cp src/main/java:src/main/resources:src/test/java:src/test/resources:$GWT_ROOT/build/lib/gwt-user.jar:$GWT_ROOT/build/lib/gwt-dev.jar:$GWT_TOOLS/lib/junit/junit-4.8.2.jar junit.textui.TestRunner client.GwtTestCollections
```

Without `-ea` it works with no error or apparent side-effect.

**Comment by rluble** [comment]
Thanks for the repro instruction. I'll take a look.

**Comment by rluble** [comment]
The issue here is that GWT is not creating bridges for the classes that implement lambdas and method references.

Without -ea the resulting program might or might not work depending on whether the missing bridge is hit by a call site.

IMO fixing this issue can be quite convoluted. We currently rely on JDT for bridge creation but JDT (and javac) implement lambdas and method references by runtime factories instead of anonymous inner classes.

The fix probably can be done by making ComputeOverridesAndImplementDefaultMethods.computeOverrides(..) aware of this and create the bridges in this case.

**Comment by rluble** [comment]
Minimal repro case:

```java
interface I {
  I m();
}

@FunctionalInterface
interface J extends I {
  void apply();
  // Overrides I.m() and specializes return type
  default J m() { return this; }
}

class Main {
  static void main() { 
      J j = () -> {};
  }
}
```

The lambda in Main is implemented in GWT by a anonymous inner class that implements J and 'inherits' the default method implementation J.m. But since J.m and I.m have different signature (different return type), these two methods are not overrides of each other after erasure so there should be a bridge in the anonymous inner class:

```java

  // pseudo java;
  I m'() { return m(); }

```


This particular situation could be handled in ComputeOverridesAndImplementDefaultMethods.computeOverrides(..), however bridges might be needed for different reasons, e.g. generic types with bounds, e.g.

```java
interface I<T> {
  void m(T t);
}

@FunctionalInterface
interface J<T extends Comparable> extends I<T> {
  void apply();
  // Overrides I.m() and specializes return type because T here is bounded by Comparable
  default void m(T t) { }
}

```

And in this case our Java AST does not have enough information (because by design JDT does erasure for us and creates these bridges for uses but does not represent lambdas and method references as anonymous inner classes), so the fix should be done in GwtAstBuilder where the classes for lambdas and method references are synthesized.

There is a workaround, which is to avoid the need for bridges. In the first example this could be done by declaring (not specializing the return type):
```java

@FunctionalInterface
interface J extends I {
  void apply();
  // Overrides I.m() and specializes return type
  default I m() { return this; }
}

```

**Comment by ruslansennov** [comment]
@rluble Is there chances to obtain this fix in next release candidate? Because suggested workaround is not appropriate to me.

**Comment by rluble** [comment]
https://github.com/gwtproject/gwt/issues/9406 is up for review addressing creating bridges for the SAM methods (a different scenario than the one described here but with exactly the same effect).

**Comment by rluble** [comment]
https://gwt-review.googlesource.com/16701 is up for review addressing the scenario described here.

**Comment by ruslansennov** [comment]
Works fine with these two patches.
Thank you
