### ISSUE TITLE
PopupKeyPanel - .gwt-PopupPanel is useless because of inline styling

### ISSUE THREAD

**Issue by gasserkl** [gwtproject/gwt#9407]
The DEFAULT_STYLENAME = "gwt-PopupPanel" is pretty useless, since later on some inline stylings are being applied (like in line 215, the position: absolute stylings).

It would be nice if you could get rid of these inline-styles because then people would be able to override the .gwt-PopupPanel class stylings in their .gss if needed, like I would do right now.
Unfortunately the inline-stylings prevent me from doing so and I therefore I need to do some dirty additional inline-styling myself in my Class that is extending the PopupPanel.

**Comment by tbroyer** [comment]
What kind of styling do you want to do? AFAICT inline styles are limited to the bare minimum to make the widget behave correctly. I can only think of `position: fixed`, and while it might be a good addition to make it possible for a `PopupPanel` to use `position: fixed` instead of `position: absolute`, this is a different issue. Also, `gwt-PopupPanel` is definitely **not** useless: in many cases you'll want to at least set a `background`, and possibly a `z-index`, then also maybe the `overflow`, `border`, `box-shadow`, etc.

**Comment by jnehlmeier** [comment]
Just add `!important` to your CSS rule to override inline styles.

**Comment by gasserkl** [comment]
Thanks for you quick replies! I have to apologize, .gwt-PopupPanel is of course not useless, the mistake was on my side! Proper sleep + coffee fixed the problem! ;)
