### ISSUE TITLE
GWT 2.8 RC2 - An internal compiler exception occurred

### ISSUE THREAD

**Issue by vjay82** [gwtproject/gwt#9411]
When switching my working GWT 2.7 project to 2.8 RC2 I get this:

      [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
	at com.google.gwt.dev.jjs.ast.JReturnStatement.traverse(JReturnStatement.java:40)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:92)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:785)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:777)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1379)
	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:875)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
	at com.google.gwt.dev.codeserver.Recompiler.doCompile(Recompiler.java:362)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:175)
	at com.google.gwt.dev.codeserver.Recompiler.recompile(Recompiler.java:134)
	at com.google.gwt.dev.codeserver.Outbox.recompile(Outbox.java:135)
	at com.google.gwt.dev.codeserver.JobRunner.recompile(JobRunner.java:113)
	at com.google.gwt.dev.codeserver.JobRunner.access$000(JobRunner.java:37)
	at com.google.gwt.dev.codeserver.JobRunner$2.run(JobRunner.java:90)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: java.lang.Object.Object(I) <init>
	at com.google.gwt.dev.jjs.impl.UnifyAst.translate(UnifyAst.java:1595)
	at com.google.gwt.dev.jjs.impl.UnifyAst.access$1000(UnifyAst.java:131)
	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:405)
	at com.google.gwt.dev.jjs.ast.JVisitor.visit(JVisitor.java:683)
	at com.google.gwt.dev.jjs.ast.JNewInstance.traverse(JNewInstance.java:73)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
	... 41 more
            [ERROR] at Stream.java(762): new Object(arg0)
               com.google.gwt.dev.jjs.ast.JNewInstance
            [ERROR] at Stream.java(762): return new Object(arg0)
               com.google.gwt.dev.jjs.ast.JReturnStatement
            [ERROR] at Stream.java(762): {
  return new Object(arg0);
}
               com.google.gwt.dev.jjs.ast.JBlock
            [ERROR] at Stream.java(762): {
  return new Object(arg0);
}
               com.google.gwt.dev.jjs.ast.JMethodBody
            [ERROR] at Stream.java(762): java.util.stream.Stream$StreamSource$0methodref$ctor$Type.apply(I)Ljava/lang/Object;
               com.google.gwt.dev.jjs.ast.JMethod
      [ERROR] Compiler returned false
      [WARN] recompile failed
      job's progress set to ERROR:

I don't use Maven for reasons, maybe I forgot to download a required jar? ... I would expect another error message then. What I did was: I replaced all GWT files with their new counterparts, switched guava/-gwt to git-master and updated their dependencies as far as I can see.

**Comment by rluble** [comment]
The error seems to points to a classpath issue. Reopen it if/when you can create a small repro case.

**Comment by rsertelon** [comment]
Hi, got the same problem here. Can't figure out what would cause the issue yet.

**Comment by tbroyer** [comment]
@rluble It looks like, for some reason, the compiler maps `Object[]::new` (at https://github.com/gwtproject/gwt/blob/2.8.0-rc2/user/super/com/google/gwt/emul/java/util/stream/Stream.java#L762; taking an `int` argument) to `Object::new` (which does not exist, hence the `NoSuchMethodError`).

@rsertelon Is this is the exact same error? Can you create a small repro case? or maybe it's in an opensource project?

**Comment by rsertelon** [comment]
@tbroyer Same error yes. However, not sure I can create a simple reproduction case. What would generate such confusion for the compiler? Another implementation of Stream.java ?

**Comment by rsertelon** [comment]
I've just checked another thing or two.

* When compile with maven (gwt-maven-plugin with gwt:compiler), it compiles without error.
* When running codeserver with maven (gwt-maven-plugin with gwt:run-codeserver), it starts, but complains on first compilation with above error.

I've compared the classpaths, they are identical for the call to gwt-maven-plugin (be it with compile or run-codeserver).

So, AFAIC, it does not seem to be a classpath problem.

**Comment by rsertelon** [comment]
Just tried to isolate the problem for the last hour, but couldn't. I'm afraid I can't really spend more time on this issue, hope it will not be there in GA!

**Comment by vjay82** [comment]
I saw in your profile that you have a lot of OS projects. As tbroyer asked, is this one? If yes, in my opinion how small small is, is debatable. If I were you I would zip it together and attach it.

**Comment by rluble** [comment]
I'll have a look. BTW If you are using the snapshot you should be seeing a different error. UnifyAst no longer throws NoSuchMethodException (see f4ce942).

**Comment by rsertelon** [comment]
Hi, I've tried today with rc3, and no more luck, although it's not the same method that is missing now:

```
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3944)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1567)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1021)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MessageSend.traverse(MessageSend.java:1018)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:373)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
[INFO] 	at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3887)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3918)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.ast.MessageSend.binding()Lorg/eclipse/jdt/internal/compiler/lookup/MethodBinding;
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.isUncheckedGenericMethodCall(GwtAstBuilder.java:4167)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.access$1400(GwtAstBuilder.java:249)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:1560)
[INFO] 	... 26 more
[INFO]    [ERROR] at ListBox.java(246): getSelectElement().getOptions().getItem(index)
[INFO]       org.eclipse.jdt.internal.compiler.ast.MessageSend
```
And this time it appears at compilation time.

I'm using ECJ in my build for our JSP compilation, could it be linked? I can't see any dependency on ECJ in GWT (in maven dependencies), do you have a dependency on ECJ, and if so, which version?

Thanks,

**Comment by tbroyer** [comment]
> I'm using ECJ in my build for our JSP compilation, could it be linked?

Probably.
This is one reason you should separate client-side and server-side code into separate Maven modules; though in the short term there may be ways around it using `<scope>` (setting your ECJ to `<scope>runtime</scope>` for example to exclude it from GWT's classpath); and if you use the `org.codehaus.mojo:gwt-maven-plugin` plugin, possibly with [`gwtSdkFirstInClasspath`](http://gwt-maven-plugin.github.io/gwt-maven-plugin/compile-mojo.html#gwtSdkFirstInClasspath) (to make sure you'll use GWT's ECJ)

**Comment by rsertelon** [comment]
It compiles fine with the runtime scope (still don't know how I could let it slip ;)). Both with gwt-maven-plugin and SDM via Eclipse. Thanks for your help @tbroyer !

**Comment by jeslinedias** [comment]
Hi I have a very similar error but on a different class, I dont use any explicit ECJ. Do i have to disable it ? how ? What might be the rootcause of my issue ?
`
Public resources found in...
[INFO] Translatable source found in...
[INFO] Persistent unit cache dir set to: C:\Jesline\Project_Linux\target\gwt-unitCache
[INFO] Opening cache file: C:\Jesline\Project_Linux\target\gwt-unitCache\gwt-unitCache-f160a61272c5ebe805cd2d3d3256ed3ecf14893f-0000015CD0B5FBB0
[INFO] Looking for previously cached Compilation Units in C:\Jesline\Project_Linux\target\gwt-unitCache
[INFO] Compiling module com.citi.sevi.web.SEWeb
[INFO]    Found 0 cached/archived units.  Used 0 / 5180 units from cache.
[INFO]    Compiling...
[INFO] [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3944)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.getInternalCompilerException(GwtAstBuilder.java:4351)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMembers(GwtAstBuilder.java:4043)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMembers(GwtAstBuilder.java:4039)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.processImpl(GwtAstBuilder.java:3883)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3918)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:129)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
[INFO] 	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
[INFO] 	at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:1092)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:325)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
[INFO] 	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
[INFO] 	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.compiler.lookup.MethodBinding.isDefaultMethod()Z
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMethod(GwtAstBuilder.java:4138)
[INFO] 	at com.google.gwt.dev.jjs.impl.GwtAstBuilder.createMembers(GwtAstBuilder.java:4033)
[INFO] 	... 22 more
[INFO]    [ERROR] at CustomDateTimeFormat.java(41): public @interface Pattern
[INFO]       org.eclipse.jdt.internal.compiler.ast.TypeDeclaration
[INFO]    [ERROR] at CustomDateTimeFormat.java(28): public interface CustomDateTimeFormat extends com.google.gwt.i18n.shared.CustomDateTimeFormat
[INFO]       org.eclipse.jdt.internal.compiler.ast.TypeDeclaration
[INFO] Closing cache file: C:\Jesline\Project_Linux\target\gwt-unitCache\gwt-unitCache-f160a61272c5ebe805cd2d3d3256ed3ecf14893f-0000015CD0B5FBB0 (0 units written)
[INFO] Deleting empty file: C:\Jesline\Project_Linux\target\gwt-unitCache\gwt-unitCache-f160a61272c5ebe805cd2d3d3256ed3ecf14893f-0000015CD0B5FBB0
[INFO] Shutting down PersistentUnitCache thread
[INFO] Shutting down PersistentUnitCache thread
`

**Comment by tbroyer** [comment]
Check your classpath (`mvn dependency:tree`), this is a similar issue.

**Comment by tbroyer** [comment]
`org.eclipse.jdt.core.compiler:ecj:jar:4.3.1:compile` most probably.

As said above, split your client and server code into separate modules to avoid such clashes. (there might be workarounds, as suggested above, but they're just that: workarounds)

Ask on the Google Group (or Stackoverflow) if you need help doing so.
