### ISSUE TITLE
2.8 SNAPSHOT: JsInterop generates wrong JS code for native types using JsPackage.GLOBAL

### ISSUE THREAD

**Issue by jnehlmeier** [gwtproject/gwt#9423]
Using elemental2 and a fresh project having `<div id="hello">world</div>` in it's host page and the following EntryPoint
```java
public void onModuleLoad() {
  Global.window.alert("Element found: " + (Global.document.getElementById("hello") != null));
}
```

GWT 2.8 RC2: shows true
```java
_.onModuleLoad_4_g$ = function onModuleLoad_3_g$(){
  ($clinit_Global_0_g$() , $wnd.window.window).alert('Element found: ' + jsNotEquals_0_g$(($clinit_Global_0_g$() , $wnd.window.document).getElementById('hello'), null));
}
```

GWT 2.8 SNAPSHOT (09.09.2016): shows false
```java
_.onModuleLoad_4_g$ = function onModuleLoad_3_g$(){
  ($clinit_Global_0_g$() , window).alert('Element found: ' + jsNotEquals_0_g$(($clinit_Global_0_g$() , document).getElementById('hello'), null));
}
```
I think the output of 2.8 SNAPSHOT would be correct if elemental2 would use `namespace = "window"` as of commit https://github.com/gwtproject/gwt/commit/c511029eaae4ec66ff874d7e69efd9516ccc78db , however it uses `JsPackage.GLOBAL` and the JS output should be the one of RC2.

Also see: https://groups.google.com/d/msg/google-web-toolkit-contributors/Tnl3A4Kw0hI/NWybjWmjBAAJ

**Comment by rluble** [comment]
Can you share the definition for Global? This behavior change was introduced by https://gwt-review.googlesource.com/#/c/16720/ (commit c511029e) but this case is an unintended consequence, makes references to a namespaces starting with "window" refer to the iframe window instead of $wnd.window

Changing the definition of Global (in elemental2) from 

@JsType(isNative = true, name = "top", namespace = JsPackage.GLOBAL)
public class Global {
}

should work around your issue for now.

**Comment by tbroyer** [comment]
For reference, `Global` from elemental2-experimental 16-06-30 is

```java
@JsType(isNative = true, name = "window", namespace = JsPackage.GLOBAL)
public class Global {
  …
  public static Window window;
  …
}
```

It looks as if GWT (erroneously) uses `name` instead of (or in addition to?) `namespace` when looking for the special token `window`.

**Comment by tbroyer** [comment]
Wondering: would `name = "$wnd", namespace = "window"` work as a workaround?

**Comment by jnehlmeier** [comment]
Kind of interesting when debugging the code a bit.
```
Global.window
Global.document
```
results in `GenerateJavaScriptAST.createGlobalQualifier(member)` being called with a member of type `JField` for the static window / document property access. This member has a `jsNamespace = null` variable which causes `JField.getJsNamespace()` to ask its enclosing type (`Global`, with `jsName = "window"` and `jsNamespace = "<global>"`) for its qualified JS name, which is "window".
```java
  public String getJsNamespace() {
    return jsNamespace == null ? enclosingType.getQualifiedJsName() : jsNamespace;
  }

```

So the code in GenerateJavaScriptAST
```java
  private static JsNameRef createGlobalQualifier(JMember member, SourceInfo sourceInfo) {
    if (isWindow(member.getJsNamespace())) {
      return JsUtils.createQualifiedNameRef(
          member.getQualifiedJsName().substring(WINDOW.length() + 1), sourceInfo);
    }
    return createGlobalQualifier(member.getQualifiedJsName(), sourceInfo); // generates the usual $wnd. ...
  }
```
enters the if branch for both the window and document access, because `member.getJsNamespace()` returns "window". Looks odd to me. Shouldn't the members (`window`, `document`) have a `jsNamespace = "<global>"` instead of `null` just like `Global` does? In that case the if would not be triggered.

**Comment by gkdn** [comment]
We didn't intended $wnd.window.xxx to return window.xxx but the fix might be ugly. @rluble lets talk today.

**Comment by tbroyer** [comment]
IIUC, `jsName` can have dots (see change in `NativeString` in the linked change), so how about accumulating into `jsName` instead of `jsNamespace`?

**Comment by rluble** [comment]
The problem is that the name of the enclosing class is the namespace of the properties/method/nested classes.

And the semantics is that if the namespace of the item is "window" or starts with "window." then it means that is on the iframe.

All we would want is that if the namespace was specified as "window"  then it is in the iframe, but to implement those semantics we need to refactor the code quite a bit. Very early on the namespaces get computed and after that there is no distinction between a namespace that was specified in that member and an "inherited" one.

Anyhow, here https://gwt-review.googlesource.com/#/c/16881 is the relevant test with the failing scenarios commented out.

**Comment by gkdn** [comment]
I think we should add GLOBAL to namespace early (i.e namespace becomes <global>.blah) and replace it with $wnd at the very end, when we generate the output. We probably need to strip it for jsinterop checking purposes but other than that I hope that's not too bad?

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/#/c/16881
