### ISSUE TITLE
@JsProperty generated variable name misnamed with trailing _0

### ISSUE THREAD

**Issue by jandsu** [gwtproject/gwt#9431]
With a class defined as 
```
@JsType
public class MyWorkerMessage
{
    @JsProperty
    public String code;
    @JsProperty
    public GwtUint16Array payload;
}
```
I would expect the generated JavaScript to have a class with 2 fields named 'code' and 'payload'.
And this is what I get with GWT 2.8.0-beta1

With GWT 2.8.0-rc1 and GWT 2.8.0-rc2, the fields are named 'code_0' and 'payload_0' which makes them unusable from an external JavaScript code.

---

To reproduce:
- Clone https://github.com/jandsu/gwt-webworker
- Run the instructions
- open the dev mode console and observe how when you click on the button, you receive a correct message
- Edit build.gradle to change `gwtVersion = '2.8.0-rc2'`
- Build GWT again

==> observe how clicking on the button now fails.
- Open the generated source by clicking on the error,
- set a breakpoint
- click on the button again
==> see how the variable are misnamed

I am unsure what the cause is, it seems odd that I am the only one hitting the issue, as this simply breaks the purpose of JsInterop

**Comment by jnehlmeier** [comment]
You either have to use `@JsType(isNative = true)` if you want to consume external JavaScript / Browser API or you have to use `@JsType` together with `-generateJsInteropExports` Compiler/SDM parameter to export your Java class to JavaScript so that external JS can use your "Java" class.

In 2.8beta1 you must also use `-generateJsInteropExports` for non-native JsTypes in a production compile. Only SDM had a bug that accidentally allowed it to work without the parameter.

**Comment by tbroyer** [comment]
See #9369
