### ISSUE TITLE
JsInterop: look at scalar constants (static final primitive types) as if they are JsOverlay

### ISSUE THREAD

**Issue by kirillp** [gwtproject/gwt#9438]
It should be possible to declare numeric and string constants in JsType interface declarations. 

Now it requires JsOverlay  annotation, however it can be relaxed.
For example WebGL API has more then 100 numeric constants in WebGLContext interface.
There is no need to write JsOverlay  100+ times.

**Comment by tbroyer** [comment]
@gkdn for triaging. See also https://groups.google.com/d/topic/google-web-toolkit/ghW6Jv54Hp0/discussion for context.

The thing is: fields in interfaces are necessarily `static final` (and as such need an initializer, so can't be mapped to JS constants), so `JsOverlay` could be assumed when the interface is annotated with `@JsType(isNative=true)`.

**Comment by jnehlmeier** [comment]
I guess in `@JsType(isNative = true)` classes, not just interfaces, GWT could assume the same for static final constants.

**Comment by rluble** [comment]
I'll let @gkdn expand. With JsInterop we preferred an explicit set of annotations so that the meaning is clear rather than having many implicit rules where the meaning is more "magical". In the case of API provided by browsers (like WebGL), the idea is to have tools to synthesize them from their descriptions.

IMHO the burden of explicit descriptions is outweighed by clarity of meaning.

**Comment by kirillp** [comment]
I don`t think it is some kind of "implicit rule".
This is about to allow something. 

And to simplify the code, to write

@JsType(isNative = true) interface A { int N = 100; .... };
instead of 
@JsType(isNative = true) interface A { interface Const { int N = 100; } .... };

To extend the idea, it would be nice to have auto JsOverlay for default interface methods as well.

You can use tools to translate W3C IDL`s but what about number of js libraries written by people and simplicity of writing JsInterop declarations for it.

**Comment by gkdn** [comment]
Is the "A.N" here refers to "N" field defined in JavaScript object A?

**Comment by gkdn** [comment]
What if the A is a class instead of interface?

@JsType(isNative = true) class A { public static final int N = 100; .... };

**Comment by kirillp** [comment]
> Is the "A.N" here refers to "N" field defined in JavaScript object A?

No, this is equivalent to 100, a numeric constant. Visible only for java.
The same answer for Java8 default interface methods.

> What if the A is a class instead of interface?

The only reason for "isNative=true class" I see today is to be able to declare some @JsOverlay helper methods. This is exactly what default interface methods is suitable for.
Is there any other reason of "isNative=true class" declaration ?
Are we going to add fields ? Override methods ?  
What if I override @JsOverlay ( will it have virtual call ) ?

**Comment by gkdn** [comment]
Actually we use native classes much more than interfaces. You cannot have constructors or native static methods with interfaces. And yes you can have fields with classes as well. Also classes are type-checked at the runtime. And no, you cannot override an overlay method, no matter where it is defined.

For WebGL context, in Elemental we generate a native class that lists all the constants as fields such that no value is actually hard coded in Java instead refers to JavaScript:

@JsType(isNative = true, namespace = JsPackage.GLOBAL)
public class WebGLRenderingContext {
  public static double ACTIVE_ATTRIBUTES;
  public static double ACTIVE_TEXTURE;
  ...
}

**Comment by gkdn** [comment]
Going back to my previous example, assuming the same rule apply for classes (otherwise it would be an inconsistent design):

@JsType(isNative = true) class A { public static final int N = 100; .... };

Then A.N refers to Java field.

What if you remove final:
@JsType(isNative = true) class A { public static int N = 100; .... };

Does it still refer refer to A.N in Java? I assuming the answer is yes otherwise it will be surprising for the the user.

Then the next question is: What if you remove the initialization as well:
@JsType(isNative = true) class A { public static int N; .... };

Now it is referring to JavaScript A.N.

So the way I interpret the behavior that is requested in the bug; "if you initialize the field assume the field is defined in Java object and if the field is not  initialized then assume it is defined in underlying JavaScript object". This is very error-prone and will be source of many bugs where people initialize by accident.

So instead of going such path, we chose a more explicit approach; "whenever the member is not part of original JavaScript, it needs to be marked with @JsOverlay". I think this is a sane design choice.

**Comment by rluble** [comment]
Well native JsType classes are just a way to surface JS classes to Java. As opposed to interfaces native JsType classes allow you to create instances and map Java instanceof to Js instanceof operator (e.g see https://github.com/gwtproject/gwt/blob/48e3ba9e67f4b0d4ba25af5263d552f8f03ece9f/user/super/com/google/gwt/emul/java/lang/NullPointerException.java#L44). Interfaces only provide a way to access a JS API. Other than that native classes and native interfaces are pretty much the same.

Isn't the whole argument here that <tt>final static </tt> fields in native JsTypes can be "automatically" considered @JsOverlay, because there is no other option (omitting @JsOverlay will result in a compilation error)?

**Comment by kirillp** [comment]
> Isn't the whole argument here that final static  fields in native JsTypes can be "automatically" considered @JsOverlay

Yes, initial request was for that. And I don`t see any argument above. Nice conversation.
Personally I'm ok writing interface Const or @JsOverlay all constant declarations, however it looks not so nice for me.

> And yes you can have fields with classes as well.
If you don't mind I have a question here. 
Will the field be visible for JS ? Under which name ? 
Can it  accidentally override undeclared JS field ? 

Must all the methods be @JsMethod(JsProperty) or @JsOverlay ? 

> native JsType classes allow you to create instances 
And a question here : 

>  NativeTypeError(String msg) { }
Should the native constructor be native ? or JsConstructor here ? 

> JsType classes allow you to create instances and map Java instanceof to Js instanceof operator 
Can I see test for that ?

**Comment by rluble** [comment]
> Must all the methods be @JsMethod(JsProperty) or @JsOverlay?

In a native JsType yes. All methods are either JsMethod, JsProperty or JsOverlay.

> Should the native constructor be native ? or JsConstructor here?

Constructors on native JsTypes are always native JsConstructors (they must be empty, since Java does not have a syntax for native constructors.

Note that declaring a native JsType all its methods and fields are considered JsMethod/JsConstructor and JsProperty respectively, they do not need to be annotated. Only need annotation for JsOverlays

In the case of non-native JsType only public methods/constructors and fields are implicitly JsMethod/JsConstructor/JsProperty.

> JsType classes allow you to create instances and map Java instanceof to Js instanceof operator. Can I see test for that ?

https://github.com/gwtproject/gwt/blob/adb428eeb25f8114b9990859030ea745288a2ec2/user/test/com/google/gwt/core/interop/JsTypeTest.java (Line 187)

In that folder there a quite a few tests showing uses of native JsType classes and interfaces.

**Comment by jnehlmeier** [comment]
> What if you remove final:
@JsType(isNative = true) class A { public static int N = 100; .... };

That would be a compile error. Only `static final` should be allowed as implicit `@JsOverlay` as there is no other option, you must initialize it in Java, so its a Java constant.

As noted in some cases JavaScript provides constants and you can reference them directly using a native type, e.g. WebGLRenderingContext. I have no idea if there are lots of APIs that do not provide JS constants, but one example coming to mind is XMLHttpRequest's `readystate`. 

I can see the point of being explicit, but in some cases (static final fields in classes/interfaces, default methods in interfaces) it feels repetitive without a lot of value, especially once you understand how JsInterop works and you are comfortable with it. 

I don't have a strong opinion wether to allow it or not.

**Comment by kirillp** [comment]
> And yes you can have fields with classes as well.

It is unclear how can I add a java field to native class. And I did not find any test for that.
What if I declare a field and use it ? 
What if the field declaration overrides some hidden JS native field ?

**Comment by tbroyer** [comment]
@kirillp See https://docs.google.com/document/d/10fmlEYIHcyead_4R1S5wKGs1t2I7Fnp_PaNaa7XTEk0/edit#heading=h.b1boa8c235km and https://github.com/gwtproject/gwt/blob/030a9a29c8362a988ba88fcc3a40a6b8f0025526/dev/core/src/com/google/gwt/dev/jjs/impl/JsInteropRestrictionChecker.java#L415-L422

You can have a Java field in a `JsType(isNative=true)` class, and it'll map to a JS property. That means the field cannot be `final` nor have an initializer.

**Comment by slavap** [comment]
Still did not get - how to add Java field to native class? I don't want it to be mapped to JS property of course, it's "pure" overlay. Why @JsOverlay cannot be used for marking non-static fields?

**Comment by niloc132** [comment]
Revisiting this as I go over old issues that can be closed: the question doesn't really make sense as I understand it @slavap. Thomas's answer above was to explain that a JS type in Java can simply have a field to represent the native type - but you can't have a non-native field (or method) in a native type. 

What you can have is a `JsOverlay` method in a native type - that will translate as "effectively static and final" so that the compiler can let that method exist even though it doesn't live in the real native type. The same can't be said of fields, (unless you make the field static of course). Consider instead a `JsWeakMap` - this can't be iterated, but effectively lets external code add "hidden fields" to another instance, and let those "fields" be GC'd when the instance itself is.

In doing this, you could build a "non-native property in a native feature":
 * static overlay field of `JsWeakMap<MyNativeType, MyFieldType>`
 * instance getter/setter overlay methods, which interact with the weak map

```
@JsType(isNative=true)
public class MyNativeType {
  // native members:
  // implicit @JsMethod
  public native String readName();
  @JsProperty
  public native int getParentId();
  // implicit @JsProperty
  public JsArray<Double> numbers;

  // Non-native members must be overlays, which means they are "effectively static"
  // but we can "cheat" with JS weakmap to make a per-instance field not present
  // in the native type, and use these as if they were instance fields.
  @JsOverlay
  private static final JsMap<MyNativeType, List<String>> TAGS;
  @JsOverlay
  public final List<String> getTags() {
    return TAGS.get(this);
  }
  @JsOverlay
  public final void setTags(List<String> tags) {
    TAGS.set(this, tags);
  }
}
```
We wouldn't want to automatically generate this code - it is better to be explicit about this kind of thing, since it isn't really a part of the native type. It would be very confusing to accidentally define a non-native field on a type that suddenly was not present in any JS that interacted with the instance...

Alternatively, be aware that you can always just add a native field to a native type and just use the field from Java. It isn't a very "polite" thing to do, and can cause conflicts when multiple codebases are rewriting fields of objects they didn't define...

Closing as this issue is long since resolved and jsinterop finalized and under its own repository.
