### ISSUE TITLE
Defender method bridges causes JsInterop checking errors

### ISSUE THREAD

**Issue by gkdn** [gwtproject/gwt#9440]
Repro:

```java
@JsType(isNative = true, name = "ArrayLike", namespace = JsPackage.GLOBAL)
public interface ArrayLike<T> {

  @JsProperty
  int getLength();

  @JsProperty
  void setLength(int length);

  @JsOverlay
  default T getAt(int index) {
    return (T) JsUtils.getAt(this, index);
  }

  @JsOverlay
  default void setAt(int index, T value) {
    JsUtils.setAt(this, index, value);
  }
}

public abstract class JsArray<T> implements ArrayLike<T> {
}
```

   Errors in jsinterop/base/ArrayLike.java
      [ERROR] Line 21: JsOverlay method 'Object JsArray.getAt(int)' cannot be non-final nor native.
      [ERROR] Line 26: JsOverlay method 'void JsArray.setAt(int, Object)' cannot be non-final nor native.

Note that also the error refers to JsArray.get listed under ArrayLike.

**Comment by rluble** [comment]
You missed an important piece of info out. <tt>JsArray</tt> is also native.  The issue here does not have to do with traditional bridges but with the implementation strategy of default methods. 

There is an assertion in JsInteropRestrictionChecker but the test might not be running with -ea.

I'll have a look.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/17140
