### ISSUE TITLE
Feature Request: Being able to externally define @JsType types without annotations

### ISSUE THREAD

**Issue by ainslec** [gwtproject/gwt#9459]
Hello,

I *think* this is the right place to raise a feature request, but if not, then feel free to inform me of the correct location, and close this issue.

Moving on.

I recently attended GWTCon and asked a question about being able to externally define \@JsType annotations such that the 2.8.x compiler would be aware that the types should be exported, but *without* requiring the GWT annotations on the classpath. Dan suggested we take the issue offline and I think perhaps this is the right place to do that.

A bit of background. I'm working on a framework that emits quite large and very portable PoJo models, together with some utility classes. The emitted code is entirely free of dependencies on GWT, but emits in a GWT compiler friendly format such that GWT modules are also emitted so the emitted code can work in GWT applications when included in GWT projects, and referenced by other (typically UI specific GWT models).

This works very well (in my own opinion). I can leverage GWT without being dependent on GWT for those particular projects. I can even add super-src classes that depend on GWT APIs without those classes being processed traditionally by the Javac compiler in non GWT projects. The GWT module files and super-src files are simply ignored if used in Android or plain old Java projects.

So, that brings me to the feature request. The simplest requirement I have is to be able to define packages or patterns of packages in which all types should be \@JsType s, without requiring the annotations on the classes explicitly.

A suggestion for the simple case might be:

```xml
<source path="model" exportjstype="true" />
```

(where the exporting of jstype is an optional attribute on the "source" node).

The above may be the simplest way to define it, but it may be worth considering more granular ways to define it, and I'm not advocating that the above approach is the best approach.

Ultimately, I would like the ability to overlay the JsInterop annotations over certain packages, classes, and even methods, based upon an external xml definition that can be linked to via the .gwt.xml file. I am aware that J2CL is upcoming so it makes sense to make sure that whatever approach is used is easily portable to J2CL too, but for now, for my own requirements, being able to apply the annotation at package level via a snippet.

Now, if we can reach consensus on the simple requirement, I am happy to add it into the GWT compiler myself if it can be added in a future 2.8.x release. After I sign the CLA of course. With regard to the larger requirement, I may be able to do that work too but that very much depends on how deep the rabbit hole goes on that requirement,

Please let me know if what I'm suggesting sounds reasonable, unreasonable, or otherwise.

Chris

**Comment by gkdn** [comment]
There is a separate maven target that just consists of jsinterop annotations (com.google.jsinterop/jsinterop-annotations). You don't need to depend on GWT.

**Comment by ainsley** [comment]
It's good that the annotations are packaged separately, but there is still an issue that if we have a library/package/class that is GWT compatible, but not annotated, then we require to modify the source of that library/package/class in order to export the interoperability, rather than being able to flag it external to the source itself.

The current 'module' system that exists within GWT already solves this problem. We can flag GWT compatible sourcecode without modifying the source itself; without annotating the source itself. The module can be defined external to the project itself. 

Annotations are useful if you have full control over the sourcecode, but if you don't have control over the source then you simply cannot use JSInterop.

Code generation *could possibly* modify the source, and then take on the annotation boilerplate classes, but if your project is targetting Android and GWT is not on your radar, why would you want to pollute your sourcecode with GWT annotations? If I want to annotate that library, I have to either fork the library, or convince the library owner to add in the GWT JSInterop annotations and pre-requisites. Or, if there were a way to externalise the JSInterop annotations, I don't need to modify the core library nor persuade the library author to add in a dependency (no matter how small).

I understand the reluctance to add a feature that is worked around by adding in a jar dependency but I hope I have persuaded you that it is more than just aversion to adding in dependencies. Sometimes it's about being able to use an existing library without modifications.

**Comment by dankurka** [comment]
I think the argument of using a certain library as JsTypes without modifying the source will not work on practice. JsTypes have higher restrictions than normal Java classes (constructors, method and field name collisions, etc.). So any person that wants types to be JsTypes needs to be aware and structure their code in a way that works with JsTypes. So splitting this up does not sound like a good idea.

**Comment by ainsley** [comment]
Thanks for the thoughts on this.

I understand the argument that there are additional restrictions that you typically need to be aware aware of for GWT compatibility. That said, these restrictions are typically *accidentally* adhered to as part if exporting a well-structured pojo model using simple java types (String, int, double, java.util.Date, collections, maps, Arrays). Admittedly, it would be extremely unusual for non-pojo code to be accidentally compatible with the GWT subset of emulated classes. But there is still a case to be made for the PoJo decoupling.

For my sins, I'm a model purist. My preference is for data models to be free of annotations, and be entirely portable without *any* external dependencies. If the model is entirely for a GWT project, I prefer the current approach, obviously.

If I'm forced to generate annotations on exported model code, then this introduces an additional permutation in (my own) code generation. Up until now, I could export a single permutation of code that had no dependency on GWT, but would work in GWT without modification.

WIthout decoupling, I will have to generate code that is usable in interops, or generate code without interops. Plus, sometimes I may wish to toggle those elements that are exported, and those which are not, which means that I can't switch on different interops from a single location.

For example, some users may wish to obfuscate the entire model and not be usable from JavaScript libraries, some users may wish to export nothing or a subset of model elements. 

I guess this isn't a high priority for a perceived edge use-case. For my own benefit, I will look at implementing this on a fork, but I accept that the chances of a pull request being accepted into the mainline are slim to none based on this thread, so on my own head be it.

**Comment by gkdn** [comment]
There is always in per module based configuration. Some user might have differently configured modules in the code paths (or multiple modules including same source). So ideal solution to configurability around exporting is at compile level. We have a bug for handling that.
So that means assuming that is fixed, your code generation should always generate with jsinterop and then let users decide if they want exporting or not at application level.

**Comment by tbroyer** [comment]
2.8.1 has `-includeJsInteropExports` and `-excludeJsInteropExports` (added in 9eda5dc418f9bdfef2fd21c6113e48dd10672beb) so I think this can now be closed.
