### ISSUE TITLE
Incorrect optimization of floating point expressions like !(a < b) into (a >= b).

### ISSUE THREAD

**Issue by Draspax** [gwtproject/gwt#9463]
Originally reported https://groups.google.com/forum/#!topic/google-web-toolkit/JSq-ra6m3fg

Encountered a situation where the following Java:

if (!(Math.abs(x - y) < 0.0001))

gets converted to:

if (Math.abs(x - y) >= 0.0001)

When Math.abs(x - y) results in NaN the if will always result in false whereas in Java NaN would result in true because of the not operation.

Before 2.8 this worked as expected.

**Comment by rluble** [comment]
The code responsible for this optimization is in Simplifier.java:370 and has been there for quite a while (since 2008). This optimization does not preserve Java semantics (IEEE 754 to be more precise) and a fix for this would be to exclude the case where the comparison operation is done on floats/doubles (could be applied if the operands are deemed not to be NAN, which can be done easily if only constants are involved).  

A possible explanation why this started showing in 2.8 in this particular example might be the fact that other optimizations transform the code and might have enabled this transformation here.

If someone sends a patch for this with the relevant tests I'd be happy to review it.

**Comment by rluble** [comment]
Code review at https://gwt-review.googlesource.com/#/c/17680/
