### ISSUE TITLE
Support JsType on non static inner classes

### ISSUE THREAD

**Issue by TDesjardins** [gwtproject/gwt#9468]
When trying to use JsType on non static inner classes the compile fails with message: 
Non static inner class 'x' cannot be a native JsType.
In Java non static inner classes are not common but there are js libs which creating objects by calling constructor on an instance:

var foo = new Foo();
var bar = new foo.Bar();

How can this be achieved with JsInterop? Why is JsType on non static inner classes not allowed?

**Comment by rluble** [comment]
Using an instance property as a constructor? Is that from a JS library? Very unusual JS pattern.

You can model this with an JsType native interface to model the interface of Foo() and a JSNI factory method to create the instances.

**Comment by tbroyer** [comment]
@TDesjardins Are you sure the `Bar` function is on the `foo` object and not on its `prototype`? You could then probably use a static inner class and `Foo.prototype.Bar` as the `JsType` name (or put `Foo.prototype` in the `namespace`).
If this is a used as a kind of “abstract factory” (where you don't know which exact kind of object `foo` is), I don't think you could ever map it to Java (`instanceof` in JS works with a constructor function and looks at its `prototype` and the prototype chain of the object being tested; where the constructor can be assigned to any variable: it's just an instance of a `Function` object; whereas in Java you use a statically-defined type name. the JS `instanceof` would better map to Java's `Class#isInstance`, except that again a `java.lang.Class` knows its _identity_ –name– whereas in JS a function can only have a _simple name_ –no _package_ or _scope_–)

In JS, if you call `foo.Bar()` as a function (method), the `this` inside the function will be `foo` (or whatever has been [_bound_](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind) to the function), but if you use `new foo.Bar()` then the `this` will be the object being constructed, whose `constructor` will be `foo.Bar` and whose _prototype_ will be `foo.Bar.prototype`.
So the “constructor on an instance” thing in JS is widely different from a non-static inner class in Java, and could be worked around by first assigning the constructor to a global variable and use that to construct the object (e.g. as a `JsType`). That would however break all `instanceof` operations…

So, this is the kind of things that I don't think could ever be fully mapped to Java. Maybe JsInterop (or the small interop lib that'll come with Elemental 2) could provide a way to `new` an object and use `instanceof` on it too? (similar to `java.lang.Class#newInstance` and `java.lang.Class#isInstance`) The `new` would be problematic due to the variable arity of the function being passed as argument, so maybe it'd have to be special-cased by the compiler?

**Comment by TDesjardins** [comment]
@rluble 
I thought as much that this is also unusual in JS!
Yes, with the JSNI factory method I already created instances, but with this approach I can't extent the types with non native JSTypes. I also tried a hack and put a instance of `Foo` on the `window`-Object. I can then create `Bar`-instances directly with the Java constructor. But extending the native types (with non JSTypes) also doesn't work. The interesting thing is that then the native constructor will be executed before `onModuleLoad()`. And at this time there is no Foo instance on the `window`-Object, yet.

@tbroyer 
I am very sure that it is on the `foo` object. I first thought that `foo` is only the namespace but it isn't. The prototype namespace is an interesting idea. I can also see your concerns about `instanceOf`- and `this`-problem.

I see a lot of more problems to use this lib with JsInterop and I don't wanna waste your time. Maybe in this case it is better to use plain JS or choose another library/framework.

If you are interested, the js lib is a lightweight OO HTML5-Game Engine:
http://www.html5quintus.com/
