### ISSUE TITLE
Support the tilde key

### ISSUE THREAD

**Issue by BenMcLean** [gwtproject/gwt#9478]
I do not see "Tilde" or "Grave" on [this list](http://www.gwtproject.org/javadoc/latest/com/google/gwt/event/dom/client/KeyCodes.html).

Why is it not on the list?

It should be supported for its [use in games](https://en.wikipedia.org/wiki/Grave_accent#Games).

**Comment by tommyettinger** [comment]
It's an odd omission in general, since the grave/backtick as a solitary character (not as a a diacritic over a letter) has been part of ASCII for longer than JS has existed. I'm wondering if there's some browser compatibility reason that's preventing this from being accurately detected? Or some keyboard layout quirk? I seem to recall certain keyboard layouts caused problems for users who needed to enter the grave accent character as a command prepend for an IRC bot, so even though US English keyboards can enter it with one keystroke, other layouts might require some cumbersome combination. As far as I can tell, the only way to create an [ECMAScript 6 template literal](http://es6-features.org/#StringInterpolation) is with grave characters, so a code editor for JavaScript written with GWT would need to handle that character in some way (not to mention the frequent use of the tilde character in JavaScript code, especially in pairs to coerce JS numbers to the 32-bit integer range). The GitHub flavored Markdown I'm writing right now uses the grave to mark `a block of code`. It seems like using browser-native widgets allows grave and tilde characters to be entered without issue, but shortcut-style keypresses outside a text entry field seem unable to handle them. So what's the deal here?

**Comment by tbroyer** [comment]
FWIW, I tested (using http://unixpapa.com/js/testkey.html, which is oldish but still useful) and, in Chrome for Android, I get keydown and keyup events with keyCode=229 (and a "legacy" textinput event with ``data=` ``), while in Chrome or Firefox on Linux with a French keyboard layout (which means the backtick is on the same key as the é and 7, and reachable using AltGr) I get two pairs of keydown and keyup events with keyCode=225 and keyCode=55 respectively (for the AltGr and è/7 keys), and a keypress event with ``charCode=` ``. FWIW, the tilde with a French layout is at AltGr+é (which is the key where I can also get the 2, with Shift+é)

**Comment by BenMcLean** [comment]
Why is this "wontfix"? A button doesn't have to be on every keyboard layout in the world to be supported does it?

**Comment by tbroyer** [comment]
A constant does not have to be defined for apps to handle keys. If a constant is defined, users will expect it to work, and it'll fail for a good number of them.

Mozilla [says](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode):
> Web developers shouldn't use the `keyCode` attribute for printable characters when handling `keydown` and `keyup` events. As described above, the `keyCode` attribute is not useful for printable characters, especially those input with the `Shift` or `Alt` key pressed. When implementing a shortcut key handler, the [`keypress`](https://developer.mozilla.org/en-US/docs/Web/Events/keypress) event is usually better (at least when Gecko is the runtime in use).

and of course, [that last link](https://developer.mozilla.org/en-US/docs/Web/Events/keypress) then says:
> Chrome does not fire the `keypress` event for known keyboard shortcuts. Which keyboard shortcuts are known depends on the user's system. Use the `keydown` event to implement keyboard shortcuts.

Keyboard handling on the web is a mess (and it keeps changing: the `keypress` event has been deprecated and replaced by the `input` event, but that one's not suitable for keyboard shortcuts; `keyCode`, `charCode` et al. are deprecated too, and replaced by `key` and `code` whose behavior is easier to predict).

Ideally, you'd use `event.code == "Backquote"` for your use-case, except that it isn't widely implemented yet: http://caniuse.com/#feat=keyboardevent-code (missing Safari, IE and Edge; ignoring mobile); so you should fallback to using `keyCode`. On my French keyboard layout, the key just below the Escape key (labeled `²`) has keyCode=222 in Chrome and keyCode=0 (sic!) in Firefox, but according to [Mozilla's Developer Network wiki](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), it'll have keyCode=192 on many other keyboards.

It had been decided years ago that keyboard events wouldn't be given more love in GWT until there's a reliable and cross-browser way of handling them; or that new APIs specific to keyboard shortcuts should be created.

**Comment by BenMcLean** [comment]
Thank you for this information.

I hope the browsers will finally get their act together some day.
