### ISSUE TITLE
missing name after . operator

### ISSUE THREAD

**Issue by padisah** [gwtproject/gwt#9490]
GWT version: 2.7.0
Browser n/a
Operating System: ubuntu 14.04

Compilation error client side code generation:
I have a JSNI code snippet, inside a Widget class, which contains a JS promise, with a catch callback

this is the code:
 $wnd.navigator.mediaDevices.getUserMedia({video: {deviceId : deviceInfo.deviceId}})
                       .then(play)
                       .catch(errorCallback);

         [ERROR] Line 66: missing name after . operator
         .catch(errorCallback);
##### other
I am using Vaadin 7.7 actually, and the error happens during WidgetSet compilation, however that is based on the GWT compilation. According to dependency file names, i guessed that the GWT version in use is 2.7.0, but this may not be accurate.

##### Known workarounds
I will skip the error handling right now

##### Links to further discussions
this was the closest error i have found on the net:
https://github.com/yui/yuicompressor/issues/203

**Comment by tbroyer** [comment]
It looks like a Rhino issue: https://github.com/mozilla/rhino/issues/127

Apparently, a workaround would be to use `['catch'](errorCallback)` instead of `.catch(errorCallback)`.

See https://github.com/gwtproject/gwt/blob/2.8.0/dev/core/src/com/google/gwt/dev/js/rhino/TokenStream.java#L485-L520 (we're using a modified version, forked from a very old Rhino version)

**Comment by padisah** [comment]
Thank you very much for your hint!
:+1:

**Comment by tbroyer** [comment]
JsInterop is replacing JSNI, and allows using `@JsMethod(name="catch")` (see https://javadoc.io/doc/com.google.elemental2/elemental2-promise/1.0.0-beta-1 for an example)
