### ISSUE TITLE
GWT compiler generates erroneous code for invoking method references pointing to varargs methods

### ISSUE THREAD

**Issue by nfekete** [gwtproject/gwt#9497]
**GWT version:** 2.8.0 & 2.8.1-SNAPSHOT
**Browser (with version):** doesn't matter
**Operating System:**  doesn't matter

---

##### Description
Best shown with an example:
```
public class Test {

    public static void test() {
        String[] array = new String[] { "1", "2" };
        first(array);
        Function<String[], String> fn = Test::first;
        fn.apply(array);
    }

    static String first(String... strings) {
        return strings[0];
    }
    
}
```
The above code will execute without problems in the JVM, but it will generate a `ClassCastException` on 
`fn.apply(array);`. The method reference actually gets invoked with the array unnecessarily wrapped in another single element array, which will trigger the `ClassCastException` whenever an element of the `strings` array gets dereferenced. It expects a `String` but finds an array.

This only happens with varargs methods, if I change the method's signature to `static String first(String[] strings)`, the generated code is correct.

##### Steps to reproduce
[varargsmethodreference.zip - small maven project to reproduce the problem](https://github.com/gwtproject/gwt/files/832658/varargsmethodreference.zip)

 * unzip attached zip file
 * `mvn clean package gwt:run`
 * open browser with: http://127.0.0.1:8888/VarargsMethodReferenceTest.html
 * open browser console to see exception

**Comment by rluble** [comment]
Thanks for the clear repro case. 

Depending on the functional interface signature and the method reference signature there might or might not be a need to introduce an array, e.g.

```java
Function<String[], String> f = Test::first; // no array introduction, GWT erroneously introduces one
Function<String, String> f = Test::first;  // needs an array introduction
```

The bug is in how the decision is made (in GwtAstBuilder), where it looks at the declaration of the functional interface, in this case `Function<T,U>` and decides that `Function.apply(T t)` takes a scalar of type T and decides to add the array creation. Where the correct behaviour is to look at the parameterized type `Function<String[], String>` whose functional method is  `Function.apply(String[] t)`.

When there are no type variables the code is correct e.g.

```java
interface StringArrayStringFunction  {
  String apply(String[] s);
}

StringArrayStringFunction f = Test::first;   // no array is introduced by GWT
```

The fix shoud be straightforward.

**Comment by rluble** [comment]
Code ready for review at https://gwt-review.googlesource.com/#/c/17840
