### ISSUE TITLE
Creating late binding generator works on dev mode but fails in production because of obfuscation

### ISSUE THREAD

**Issue by haydus** [gwtproject/gwt#9498]
**GWT version:** 2.7.0
**Browser (with version):** irrelevant
**Operating System:** irrelevant

---

##### Description
I'm trying to build a GWT compiler generator that creates a factory class for doing Java 1.4 Class.forName() like reflection (for class instantiation only).
The generator works great in super dev mode, but when compiling for production with obfuscation it doesn't, and this is because the generator i built doesn't have access to the obfuscated class names.

Here is my generator: (sorry for the mess, for some reason the code annotation does't work well)
```
package generator;

import java.io.PrintWriter;

import com.google.gwt.core.ext.Generator;
import com.google.gwt.core.ext.GeneratorContext;
import com.google.gwt.core.ext.TreeLogger;
import com.google.gwt.core.ext.UnableToCompleteException;
import com.google.gwt.core.ext.typeinfo.JClassType;
import com.google.gwt.core.ext.typeinfo.NotFoundException;
import com.google.gwt.core.ext.typeinfo.TypeOracle;
import com.google.gwt.user.rebind.ClassSourceFileComposerFactory;
import com.google.gwt.user.rebind.SourceWriter;

public class ClassGenerator extends Generator
{
	public String generate(TreeLogger logger, GeneratorContext context, String typeName) throws UnableToCompleteException
	{
		logger.log(TreeLogger.INFO, "ClassGenerator generate " + typeName, null);
		
		TypeOracle typeOracle = context.getTypeOracle();
		JClassType clazz = typeOracle.findType(typeName);

		if (clazz == null)
		{
			throw new UnableToCompleteException();
		}

		try
		{
			JClassType[] reflectableTypes = new JClassType[]{
				typeOracle.getType("com.test.LateBindClass")
			};
			SourceWriter sourceWriter = getSourceWriter(clazz, context, logger);
			if (sourceWriter != null)
			{
				sourceWriter.println("public Object forNameAndNew(String className) {");
				JClassType[] types = typeOracle.getTypes();
				int count = 0;
				for (int i = 0; i < types.length; i++)
				{
					for (int j = 0; j < reflectableTypes.length; j ++)
					{
						JClassType reflectableType = reflectableTypes[j];
						if (types[i].isInterface() == null && types[i].isAssignableTo(reflectableType) && !types[i].equals(reflectableType))
						{
							logger.log(TreeLogger.INFO, "ClassGenerator found " + types[i].getQualifiedSourceName(), null);
							if (count == 0)
							{
								sourceWriter.println("	if (\"" + types[i].getQualifiedSourceName() + "\".equals(className)) {" + " return new " + types[i].getQualifiedSourceName() + "();" + "}");
							}
							else
							{
								sourceWriter.println("	else if(\"" + types[i].getQualifiedSourceName() + "\".equals(className)) {" + " return new " + types[i].getQualifiedSourceName() + "();" + "}");
							}
							count++;
						}
					}
				}

				sourceWriter.println("	return null;");
				sourceWriter.println("}");
				sourceWriter.commit(logger);
				logger.log(TreeLogger.INFO, "ClassGenerator Done Generating source for " + clazz.getName(), null);
				return clazz.getQualifiedSourceName() + "Wrapper";
			}
		}
		catch (NotFoundException e)
		{
			e.printStackTrace();
		}

		return null;
	}

	public SourceWriter getSourceWriter(JClassType classType, GeneratorContext context, TreeLogger logger)
	{
		String packageName = classType.getPackage().getName();
		String simpleName = classType.getSimpleSourceName() + "Wrapper";
		ClassSourceFileComposerFactory composer = new ClassSourceFileComposerFactory(packageName, simpleName);

		composer.setSuperclass("com.test.ClassFactory");

		PrintWriter printWriter = context.tryCreate(logger, packageName, simpleName);
		if (printWriter == null)
		{
			return null;
		}
		else
		{
			SourceWriter sw = composer.createSourceWriter(context, printWriter);
			return sw;
		}
	}

}
```

My issue could be resolved in either 2 ways, which i've made great efforts to find but couldn't:
1. Cherry pick the class names i want to exclude from obfuscation - i failed to find how to do that.
OR
2. Getting the final obfuscated full class names in the generator - with this idea i have 2 issues:
2.a I couldn't find a way to get my hands on the obfuscated class names.
2.b The GWT compiler seems to run my generate 5 times for some reason , from which only the first time really generates code, where the rest of the times context.tryCreate() returns null, which means the code was already generated. If i can't get the obfuscated names in the first run, i would have to re-create my class so i would need to get my hands on the PrintWriter and overwrite the code.

##### Steps to reproduce
1. Include the generator in your project:
```
<generate-with class="generator.ClassGenerator">
    <when-type-assignable class="com.test.ClassFactory" />
</generate-with>
```
2. Create the class com.test.LateBindClass in your code - this is the public interface to the late bound classes.
3. Create com.test.ClassFactory. This is the class that my generator extends, and the code inside forNameAndNew check for the given class name and creates the appropriate class:
```
package com.test;

public class ClassFactory
{
	public Object forNameAndNew(String className)
	{
		return null;
	}
}
```

**Comment by tbroyer** [comment]
Your problem likely lies in the values you actually pass to the `ClassFactory`.
The code you generate will look like:
```java
public Object forNameAndNew(String className) {
  if ("foo.bar.Baz".equals(className)) { return new foo.bar.Baz(); }
  else if ("foo.bar.Qux".equals(className)) { return new foo.bar.Qux(); }
  return null;
}
```
so if you call if like `forNameAndNew("foo.bar.Baz")` there's no reason it wouldn't work. But if you use `forNameAndNew(foo.bar.Baz.class.getName())` or `forNameAndNew(foo.bar.Baz.class.getCanonicalName())` then it'll break because it receives the obfuscated name. Generating the code with `foo.bar.Baz.class.getName().equals(className)` should then fix the problem.

Regarding your 2.b.: you have 5 permutations, so the generator is called 5 times, and because the name of the generated class does not depend on the permutation's properties, the 5 calls will try to generate the same class (same name), so the first succeeds and the others are told that the class already exists.

Now to general observations:
 * generators relying on the list of all known types are "fragile" (this is one of the issues with GWT-RPC, the **only** generator in GWT that makes use of this list, even though indirectly through queries like "give me all classes assignable to X, but that's actually what you're doing here, just without using the dedicated API; see http://blog.daniel-kurka.de/2016/07/gwt-rpcs-future.html for more on GWT-RPC)
 * now is not a good time to start writing generators; the next major version of GWT won't have them, and the current version is expected to be supported for a few years (2 or 3) but not that long. You should try to find other approaches (e.g. an "out of band" generator that would scan a classpath and generate the class, prior to invoking JavaC and the GWT Compiler; and/or possibly coupled with an annotation-processor to be able to process types from the current project at JavaC time, prior to invoking the GWT Compiler)

In any case, generators aren't going to evolve to support your use-case. It has been determined a long time ago that this was a bad idea and that GWT-RPC probably shouldn't have been designed that way (even though Daniel only wrote it up last summer); and generators are on the way out anyway (`com.google.gwt.core.ext.typeinfo` hasn't even evolved to Java 8 static and defender methods in interfaces; they're instead hidden to generators! see #9371).
