### ISSUE TITLE
Instantiating ES6 class using JsInterop requires assign class to the window object

### ISSUE THREAD

**Issue by andersforsell** [gwtproject/gwt#9500]
**GWT version:** 
2.8
**Browser (with version):** 
Chrome 57
**Operating System:** 
Windows 7

---

##### Description

I am trying to use JsInterop to create an object from a JS ES6 class.
In JS I have something like:
  
```
  class MyStorage {
  }
```

.. and in Java I have:

 ```
 @JsType(isNative = true, namespace = JsPackage.GLOBAL)
  public class MyStorage {
  }
```

Now when I try to instantiate the JS class in Java with:

`MyStorage storage = new MyStorage();`

... it fails in Chrome:

Uncaught TypeError: $wnd.MyStorage is not a constructor

I have to assign my ES6 class to the window object for it to work:
`window.MyStorage = MyStorage;`

Can this be fixed without having to pollute the window global object?

##### Known workarounds

`window.MyStorage = MyStorage;`

##### Links to further discussions

https://plus.google.com/+AndersForsell/posts/jRKdZ6zftrq

**Comment by tbroyer** [comment]
There's nothing that can be done; this is behaving as intended per spec.

See http://www.2ality.com/2015/02/es6-scoping.html (also https://stackoverflow.com/a/30322216/116472 and https://stackoverflow.com/a/37711826/116472): ES6 `let`, `const` and `class` don't create properties of the global object (`window` in a browser), so there's no mean to access them cross-window (which is how GWT works, running in a hidden iframe) without explicitly making them available as properties of the global object (i.e. `window.MyStorage = MyStorage`).

It might be possible to do it by using the `sso` linker (which won't run in an iframe) and using the undocumented `@JsType(namespace = "<window>")` (which won't add the `$wnd.` qualifier), but it comes with severe limitations (no dev mode, must generate a single permutation, uses undocumented feature).

**Comment by TDesjardins** [comment]
@tbroyer This is behaving as intended but this is not the point. The question is how will JsInterop will handle this in future. Don't know if JS-Libs (which uses ES6 classes) will put all the API-classes to the window-object. Can't believe that because this is a bad practice and therefore classes are not in the global scope. I couldn't imagine to put all the classes to the window object before wrapping with GWT.

**Comment by tbroyer** [comment]
> The question is how will JsInterop will handle this in future.

It won't, because it can't. This is not a limitation of JsInterop per se, this is due to how GWT sandboxes its code inside an iframe (with the default linker).

As I said, if you want to make it work, you'll have to make GWT code execute in the main window (like with the `sso` or the (deprecated) `xs` linkers; this poses questions of global scope pollution vs. being able to use code-splitting vs. being able to load scripts cross-origin), and use `namespace = "<window>"`.

The real answer I believe is to build everything together, and this is what GWT 3.0 will (likely) try to achieve, thanks to the J2Cl transpiler + Closure Compiler (transpile Java to JS, then compile the translated Java/JS **plus** the libs' JS into a single, optimized bundle).

All that being said, I'd expect most libs to "namespace" their classes, so it's likely that this is actually a non-issue.

**Comment by andersforsell** [comment]
@tbroyer Thanks for the explanation. I have migrated away from GWT UiBinder to using JS/Web Components/Polymer, so would the "GWT running in hidden iframe issue" be solved when using say J2CL with JsInterop in the future?

**Comment by TDesjardins** [comment]
@tbroyer I agree. Thanks!
