### ISSUE TITLE
"Please use the 'new' operator" when extending native JsType and calling super() constructor

### ISSUE THREAD

**Issue by Distem** [gwtproject/gwt#9503]
**GWT version:** 2.8
**Browser (with version):** Google Chrome (56.0.2924.87)
**Operating System:** Win10

---

##### Description

Hi, I've created a simple wrapper for native Web Worker with JsInterop which seems to work fine -

```
@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Worker")
  public class WebWorker {
    @JsConstructor
    public WebWorker(String url) {}
```

but if I try to extend it and make a call to super constructor from my extended constructor - 

```
public class MyWorker extends WebWorker {
    public MyWorker() {
        super("some-url.js");
```
I get this error when creating MyWorker instances -

> Please use the 'new' operator, this DOM object constructor cannot be called as a function.

so it seems that through the super constructor it is created like ` = Worker(url);` instead of ` = new Worker(url);`

I can easily work around it, just wanted to see if I'm doing something wrong here or if it's an actual issue.

Thanks for any help.

**Comment by jnehlmeier** [comment]
Sounds like an issue. @gkdn @rluble

**Comment by tbroyer** [comment]
The issue here is that `Worker` cannot be subclassed (except with ES6 classes).

What you're trying to do, in ES6, would be:
```js
class MyWorker extends Worker {
  constructor() {
    super("some-url.js");
  }
}
```
and it would work (well, it works in Chrome at least).

When _desugared_ to ES5 though, it turns into something like this (see for example [how Babel does it](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015&targets=&browsers=&builtIns=false&experimental=true&loose=false&spec=false&code=class%20MyWorker%20extends%20Worker%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20super(%22foo.js%22)%3B%0A%20%20%7D%0A%7D), I simplified the code here):
```js
function MyWorker() {
  Worker.call(this, "some-url.js");
}
MyWorker.prototype = Object.create(Worker.prototype);
Object.setPrototypeOf(MyWorker, Worker);
```
and this will generate the error you're seeing, because the constructor's `super()` call needs to be _desugared_ into a function call: `Worker.call(this, "some-url.js")`.

I haven't looked what GWT actually generates when extending a native JS type, but it shouldn't be much different.

I don't think there's anything GWT can do here.

**Comment by gkdn** [comment]
Technically GWT could be replaced all constructor calls with Reflect.construct which of course will not work in old browsers so we also need to supply a polyfill. This could be optimized to be done only if there is a native type in the hierarchy. I don't know if anybody is willing to do that.

So you probably better go to the route of wrapping WebWorker vs. extending it.

**Comment by tbroyer** [comment]
@gkdn How would that work with J2Cl and Closure Compiler? AFAIK, J2Cl will generate an ES6 class, but then Closure might desugar it to ES5 (or even ES3) and introduce the same issue, right?

**Comment by gkdn** [comment]
Yes same issue.
This was discussed in length but there was no solution without updating the call sites.

**Comment by tbroyer** [comment]
I'd rather not introduce anything in GWT 2.x that wouldn't be supported by J2Cl+Closure Compiler (that will undoubtedly be the basis for GWT 3), and given that other ES6-to-ES5 transpilers (Buble, Babel, Closure Compiler, [TypeScript](https://www.typescriptlang.org/play/index.html#src=class%20MyWorker%20extends%20Worker%20%7B%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20super(%22some-url.js%22)%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Alet%20myWorker%20%3D%20new%20MyWorker(%22world%22)%3B%0D%0A)) introduce the same kind of code that fails at runtime (because, well, there's no other choice, so…), then I think we should just close this issue (as either "wontfix" or "BrowserQuirks").

WDYT?

**Comment by nfekete** [comment]
Do you guys have any info (or hint or prediction) on when the J2CL is going to be released to the public?

**Comment by gkdn** [comment]
@tbroyer Agreed.
