### ISSUE TITLE
sourcemap is disabled when bindAddress is diffrent than 127.0.0.1

### ISSUE THREAD

**Issue by achabahe** [gwtproject/gwt#9508]
**GWT version:2.7** 
**Browser (with version):firefox 51.0.2 & chrome  57.0.2987.110** 
**Operating System: Windows & Linux** 

---

##### Description
when i set the bindAddress to a value diffrent than the default for example 0.0.0.0 or 192.168.56.2 in my browser i can't find the sources under source tab in both firefox and chrome browsers but when delete the property bindAddress and leave it to the default value it works fine. and this behaviour happens even if i am accessing the server code from within same machine which means i am accessing the jetty server used by gwt using http://localhost:9876/ 

##### Steps to reproduce
add bindAddress property to the gwt 2.7 maven pluggin 

##### Known workarounds
use ssh port forwarding instead of changing bindAddress
bind the 9876 port of your machine to the port 9876 of the server machine which is running gwt server 
 
localhost:9876----->server:9876
localhost:8080----->server:8080
i know i haven't made a thorough description of how to solve the issue but just look up port forwarding using ssh. if this issue is not solved i will post the total description of the work arround

drawbacks :
-you should install ssh server in the machine that runs gwt code server
- you should install ssh in your client machine 
- lattency caused by encryption and decryption introduced by ssh protocols

**Comment by tbroyer** [comment]
Can you try with 2.8? there's been changes to how the sourcemaps URLs are computed. See #8467 and #8910 (that being said, using a non-wildcard `-bindAddress` should work the same… but please use the latest version, there won't be a 2.7.1 anyway so no need to waste time debugging an older version if things work with the latest)

**Comment by achabahe** [comment]
ok i will try the 2.8 version and see how it behaves !

**Comment by PBaranovskyi** [comment]
And will we have 2.8.1 soon?

**Comment by tbroyer** [comment]
FWIW, just tried setting `-bindAddress <my network IP address>` with GWT 2.8.1 and the JS files correctly reference the sourcemaps at `<my network IP address>`; also tried with `-bindAddress <my machine's name>` with similar results.

What “doesn't work” is using `-bindAddress 0.0.0.0`, where sourcemaps are looked up at `127.0.1.1` on my machine (which works locally, but would obviously fail if accessed from a different machine). This is pointed out as "non reliable" in the code, and result will be different depending on OS and machine configuration (in my case, probably because I have an entry in `/etc/hosts` that binds `<my machine's name>` to `127.0.1.1`).

**Comment by amaharana** [comment]
@achabahe : How are you generating the sourcemaps? Would you mind posting the relevant sections from your module.xml (and ANT build.xml?)?
