### ISSUE TITLE
Using @GwtIncompatible on inherited methods breaks SDM

### ISSUE THREAD

**Issue by dharezlak** [gwtproject/gwt#9526]
**GWT version: 2.8.1** 
**Browser (with version): Firefox 53.0.2 (64-bit) for Linux** 
**Operating System:Linux Mint 18.1** 

---

##### Description

SDM compilation breaks with a message similar to `The type B must implement the inherited abstract method A.hello()` when the `hello` method implementation is annotated with `@GwtIncompatible`. The compilation passes successfully for the production mode.

##### Steps to reproduce

Try to run the following code in SDM:

```
public interface A {
	void hello();
}
```

```
public class B implements A {

	@GwtIncompatible
	@Override
	public void hello() {
	}
}
```

```
//somewhere in the entry point:
B b = new B();
```

##### Known workarounds

Overwrite the implementation of the inheriting class, provide an empty implementation for the incompatible method and remove the `@GwtIncompatible` annotation. Keep in mind that this will break the class with regard to the overwritten method on the server side.

**Comment by jnehlmeier** [comment]
I am not entirely sure (@rluble can probably help out) but when you use `@GwtIncompatible` then your code must not be broken ("red" in eclipse) if you remove that annotated method manually from the source code. In your case `B` would be broken so GWT compilation fails as well because the GWT compiler does nothing else, it just ignores the annotated method as if you have never written it.

I think your production build should have failed also.

At least that is my experience with `@GwtIncompatible`.

**Comment by dharezlak** [comment]
Is it possible that after the optimization of production compilation kicked in the whole `B b = new B();` line was removed hence the offending class was not compiled and the whole process succeeded? That would explain the difference in behavior between SDM and production compilation.

**Comment by dharezlak** [comment]
I changed the code to:

```
B b = new B();
GWT.log(b.toString());
```

and the error is also present in production. I guess this solves it.
