### ISSUE TITLE
ServerSerializationStreamWriter: NumberFormatException` for input string `"0].concat([7"

### ISSUE THREAD

**Issue by brent777** [gwtproject/gwt#9536]
**GWT version: 2.8.1

**Browser (with version): Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Operating System: Arch Linux 4.11.9-1-ARCH

---

##### Description

We ran into a corner case bug with the GWT RPC deserialisation process. The code in question uses GWT portlets. `ServerSerializationStreamWriter` defines `MAXIMUM_ARRAY_LENGTH = 1 << 15`.

When the response payload exceeds `MAXIMUM_ARRAY_LENGTH` by 1, the payload looks something like `//OK["random data", 1,2,3,...,0].concat([7])`. The response is returned to the client successfully, however when the client tries deserialising this payload it throws a `NumberFormatException` for input string `"0].concat([7"`. See the stackstrace below. For arrays bigger than `MAXIMUM_ARRAY_LENGTH + 1` it successfully deserialises.

```

java.lang.NumberFormatException: For input string: "0].concat([7"

Unknown.ec(Throwable.java:67)

Unknown.Hc(Exception.java:29)

Unknown.uo(RuntimeException.java:29)

Unknown.rBe(IllegalArgumentException.java:29)

Unknown.$Ce(NumberFormatException.java:41)

Unknown._Ce(NumberFormatException.java:26)

Unknown.oye(Number.java:222)

Unknown.NBe(Integer.java:157)

Unknown.MBe(Integer.java:153)

Unknown.fDd(ClientSerializationStreamReader.java:148)

Unknown.WCd(ClientSerializationStreamReader.java:61)

Unknown.DDd(RemoteServiceProxy.java:259)

Unknown._Dd(RequestCallbackAdapter.java:214)

Unknown.MPi(SidRpcRequestBuilder.java:60)

Unknown.eQ(Request.java:250)

Unknown.UQ(RequestBuilder.java:412)

Unknown.anonymous(XMLHttpRequest.java:329)

Unknown.Gr(Impl.java:239)

Unknown.Jr(Impl.java:291)

Unknown.anonymous(Impl.java:77)

```

##### Steps to reproduce

This is difficult to reproduce in a open source demo given that I don't know how to deterministically produce a payload with an array of a specific length, as the serialisation process is not straightforward. Possibly someone that understands the gwt serialisation can give some input here.

**Comment by tbroyer** [comment]
Hopefully it shouldn't be hard to fix.

The issue is in isolating the last item of the "array" before actually parsing it (using either `eval()` or `JSON.parse()`, depending on the read value): https://github.com/gwtproject/gwt/blob/2.8.1/user/super/com/google/gwt/user/translatable/com/google/gwt/user/client/rpc/impl/ClientSerializationStreamReader.java#L145-L149

This code should look for the later of `,` or `[` instead of just `,` (or because it's rather an edge case, then for performance reasons, additionally look for a `[` in the `versionStr` and if found re-substring to the smaller `versionStr`).
It should be relatively easy to add a test for this specific case in either https://github.com/gwtproject/gwt/blob/2.8.1/user/test/com/google/gwt/user/client/rpc/impl/ClientSerializationStreamReaderTest.java (a specialized version of [`testRead_arrayConcats`](https://github.com/gwtproject/gwt/blob/2.8.1/user/test/com/google/gwt/user/client/rpc/impl/ClientSerializationStreamReaderTest.java#L60) with only one value in the last array) or https://github.com/gwtproject/gwt/blob/2.8.1/user/test/com/google/gwt/user/client/rpc/impl/WebModeClientSerializationStreamReaderTest.java (probably the latter rather than the former)

Do you think you could come up with such a patch?
http://www.gwtproject.org/makinggwtbetter.html

**Comment by niloc132** [comment]
Given the death of IE6/7 in gwt, we could likely nix that `eval` and array concats, and exclusively use `JSON.parse` as well. I know the eval causes memory leaks in IE9 anyway (someone from vaadin had a fix, but didn't pursue it iirc), so removing it serves multiple purposes.

**Comment by nsankaranarayanan** [comment]
We have this exact same issue.

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/19321
