### ISSUE TITLE
Bundled protobuf with CVE-2015-5237?

### ISSUE THREAD

**Issue by anderius** [gwtproject/gwt#9555]
It seems GWT bundles an old version of protobuf, which I suspect is affected by https://github.com/google/protobuf/issues/760.

Would it be possible to upgrade, or in some way comment on the relevance of this issue for GWT?

**Comment by dankurka** [comment]
TO my best knowlege protobuf is only used within the source mapping library (as a compile time dep) within GWT. No protobuf is used within GWT servlet which is what gets deployed server side by customers.

In general we do not worry about safety in the compiler itself since it is being run by developers on trusted inputs. The compiler itself is likely to be exploitable in several other ways.

**Comment by tbroyer** [comment]
FWIW, protobuf is actually used for the "remote UI" of DevMode in the IDE integrations (Eclipse mostly/only): https://github.com/gwtproject/gwt/tree/2.8.1/dev/core/src/com/google/gwt/dev/shell/remoteui

That doesn't change the outcome: this is something run by the developers, and enabled explicitly through a `-remoteUI` command line flag (see https://github.com/gwtproject/gwt/blob/2.8.1/dev/core/src/com/google/gwt/dev/DevModeBase.java#L277-L338; granted, using the Eclipse plugin means that the `-remoteUI` is automatically passed on your behalf, but still)

Also, that CVE seems to be related to the C/C++ version of protobuf.

**Comment by anderius** [comment]
Thank you very much for the clarification!

It was https://www.owasp.org/index.php/OWASP_Dependency_Check that reported
the problem in our project, but now I have added a suppression for our
project.
