### ISSUE TITLE
API report for Gwt User

### ISSUE THREAD

**Issue by lvc** [gwtproject/gwt#9556]
Hi,

I'd like to share the report on API changes analysis for the library: https://abi-laboratory.pro/java/tracker/timeline/gwt-user/

The report is generated by the https://github.com/lvc/japi-tracker tool for jars found at http://central.maven.org/maven2/com/google/gwt/gwt-user/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library to be aware of past and future API changes.

Please let me know if the tool should not check some parts of the API (it checks all public API methods and classes by default).

Thank you.

![gwt-user-2](https://user-images.githubusercontent.com/1517837/31481544-aa3fa42a-af2c-11e7-93ef-d03ef830c5a9.png)
![gwt-user-1](https://user-images.githubusercontent.com/1517837/31481545-aa5dfd58-af2c-11e7-989d-2d9c89d6557c.png)

**Comment by gkdn** [comment]
pls see include/exclude lists in tools/api-checker/config/gwt27_28userApi.conf

**Comment by tbroyer** [comment]
Hey Andrei,

As Goktug implied in his reply, we do have a tool to check backwards-compatibility already (forces us to whitelist changes). As you can see in our configuration files, we exclude a whole bunch of files from our "public API". Our tool also checks changes to our emulation of the Java Runtime Environment (files that are never compiled with javac, we're only interested in source compatibility). Due to the nature of GWT, we're only interested in source compatibility for many classes, and additionally with binary compatibility for others.

I still think it'd be interesting to see what your tool finds and if/how it differs from ours; so if you'd like to apply the include/exclude lists (even if not taking into account our Java runtime emulation), that'd be great. If you can't, or don't have time, then maybe you'd better remove GWT from your tool.

Please know that I really appreciate your effort with various open source projects! Those reports are likely to be very valuable to users before they upgrade to newer versions.

FWIW, the documentation for our tool has been archived from Google Code Hosting at https://github.com/gwtproject/old_google_code_wiki/blob/master/GwtJavaApiCompatibilityChecker.wiki.md and https://github.com/gwtproject/old_google_code_wiki/blob/master/ApiChecker_User_Guide.wiki.md (the tool itself hasn't changed in years)

**Comment by lvc** [comment]
Hello,

I've converted gwt-user's api-checker config to japi-tracker config and regenerated the report: https://abi-laboratory.pro/java/tracker/timeline/gwt-user/

Please let me know if there are still some packages/classes to exclude from the report.

Thank you.

![gwt-user-4](https://user-images.githubusercontent.com/1517837/31600551-985d7d28-b25f-11e7-9b9e-751a0cdead1f.png)

![gwt-user-3](https://user-images.githubusercontent.com/1517837/31600552-987cfbe4-b25f-11e7-985c-ea7eda80fb7c.png)

**Comment by tbroyer** [comment]
Great! Looks better.

You'll want to also exclude `com.google.gwt.thirdparty.` though (most "new" in 2.7.0 are due to the addition of of Closure Stylesheet, aka `com.google.gwt.thirdparty.common.css.*`)

Looking at the "big changes":
 * 2.7.0 removed `com.google.gwt.rpc.*`, so looks good; but the 1722 additions are mostly Closure Stylesheet
 * 2.6.0 changed many APIs from `com.google.gwt.user.client.Element` to `com.google.gwt.dom.client.Element`, and added several overloads taking  `SafeUri` instead of strings; which is why we have many added and removed methods.
 * 2.5.0 added big new APIs (typedarrays, ARIA, and DOM builder), and some `SafeHtml` overloads
 * 2.4.0 added the `DataGrid` widget (with many dependencies like `CustomScrollPanel` and the like) and drag'n'drop APIs, and had a couple big changes to i18n: https://github.com/gwtproject/gwt/commit/59138ff1cc0a9a7ea68176dbd541f7169bdfa101#diff-75f432e8c01e0babe65984f06d04743d and https://github.com/gwtproject/gwt/commit/ae7e82114b0b22480e15eaa7859303149ebd9517, along with changes to AutoBeans and RequestFactory.
 * previous versions added many APIs, and stabilized APIs added in 2.1 (RequestFactory, Editor, Cell widgets, SafeHtml, etc.), version 1.6.0 deprecated event "listeners" and introduced event "handlers", etc.

So it looks quite good overall (except for 2.7.0)

**Comment by lvc** [comment]
Thank you for the detailed review!

Removed `com.google.gwt.thirdparty.*`-related changes from the report: https://abi-laboratory.pro/java/tracker/timeline/gwt-user/

![gwt-user-5](https://user-images.githubusercontent.com/1517837/31648256-593ad29c-b315-11e7-930e-84e4a61ebb9f.png)

![gwt-user-6](https://user-images.githubusercontent.com/1517837/31648255-591f8a96-b315-11e7-8592-9bb0cfe0b599.png)

**Comment by lvc** [comment]
Profile for Gwt User library to run JAPI Tracker and JAPI Monitor (if someone would like to run it locally): https://github.com/lvc/upstream-tracker-4j/blob/master/profile/gwt-user.json
