### ISSUE TITLE
Missing erasure casts in lambdas

### ISSUE THREAD

**Issue by auke-** [gwtproject/gwt#9558]
**GWT version: 2.8.1 and 2.8.2** 
**Browser (with version): any** 
**Operating System: OS X** 

---

##### Description

The generated javascript contains various null references which results in runtime javascript errors (like. Uncaught TypeError: Cannot read property 'ac' of null).

It seems like this is the case for functional interfaces. In gwt-user this happens with  [PopupPanel.java#L366](../blob/master/user/src/com/google/gwt/user/client/ui/PopupPanel.java#L366):
`
function Qr(){var a,b,c,d;null.ac();...}
`
[TerminatableStream.java#L80](../blob/master/user/super/com/google/gwt/emul/java/util/stream/TerminatableStream.java#L80):
`
function dX(b){var c;try{null.ce()}catch(a){...}
`

 The same happens for some (but not all) custom lambda expressions.

##### Steps to reproduce

Create and compile a minimal project and inspect the optimised javascript for 'null.<method>':
mvn archetype:generate \
 -DarchetypeGroupId=net.ltgt.gwt.archetypes \
 -DarchetypeVersion=LATEST \
 -DarchetypeArtifactId=modular-webapp \
 -DgroupId=gwt.bug -DartifactId=gwt-bug -Dversion=0.0.1 \
 -DinteractiveMode=false
cd gwt-bug
mvn clean package
grep -o -E 'null\\.[^;]+' gwt-bug-client/target/gwt-bug-client-0.0.1/app/*.cache.js

**Comment by niloc132** [comment]
In your example project when I compile as PRETTY, I find two cases of null having methods called on it - both the "usual" kind:

```
defineClass(146, 262, {}, Window$ClosingEvent);
_.dispatch = function dispatch_10(handler){
  checkCriticalType(handler == null);
  null.$_nullMethod();
}
;
```
In this case, Window.ClosingEvent gets fired every time the page is closed, but no one is there to handle it, so the compiler "helps" to point this out. In reality, this method would never be called at all, since there would be no handler instance to even pass in.

```
function $onResize(){
  var height, width_0, winHeight, winWidth;
  null.$_nullMethod();
  winWidth = $getClientWidth($doc);
  winHeight = $getClientHeight($doc);
  null.$_nullMethod(($clinit_Style$Display() , 'none'));
  null.$_nullMethod(($clinit_Style$Unit() , '0.0px'));
  null.$_nullMethod('0.0px');
  width_0 = $getScrollWidth($doc);
  height = $getScrollHeight($doc);
  null.$_nullMethod($wnd.Math.max(width_0, winWidth) + 'px');
  null.$_nullMethod($wnd.Math.max(height, winHeight) + 'px');
  null.$_nullMethod('block');
}
```
This is in PopupPanel.glassResizer, an anonymous inner class implementing ResizeHandler. In this case, the null.null method represents any call to `PopupPanel.glass`, since it is never assigned to anything but null. That being the case, it shouldn't even be possible for onResize to be called, since the glassResizer isn't actually used.

So, these both seem very reasonable places for the compiler to replace with null.nullMethod, which would cause a null pointer exception if reached. This then lets the compiler remove some other dead code. To "fix" the first case, you would need to actually be using the closing event, and as soon as you add a handler, that case disappears. Likewise for the second case, just enable glass on the DialogBox in the sample.

Do you have a concrete example of this causing unexpected "TypeError" (aka NullPointerException) in real code? I have cases like this using lambdas, but haven't tried these specific methods. But at this time, it looks like this isn't a bug.

**Comment by rluble** [comment]
Yes, the mere presence of `null.someMethod()` in the code does not indicate an error. The compiler may replace an expression with `null` if it can statically determine that it will be always `null`at runtime.  

Please reopen with an example that actually fails at runtime.

**Comment by jnehlmeier** [comment]
@rluble Just because I am curious: In the example above with `onResize` shouldn't the compiler somehow come to the conclusion that it can prune the enclosing method that contains a null.nullMethod() call as well? 
Seems like the compiler is already pretty sure that the enclosing method will never be called, otherwise placing null.nullMethod() inside its body might cause an error at runtime.

**Comment by rluble** [comment]
The behaviour of the method is to throw an `NPE` (or `TypeError`), replacing by `null.$_nullMethod()` preserves the behavior.

In this particular case since the call is the first evaluation in the method and is not conditional, it could have been optimized further into removing the method. But in general a method could have a `null.$_nullMethod()`  that is executed after some other action or on only some paths.

**Comment by auke-** [comment]
I've narrowed it down to the use of JavaScript overlay classes with interfaces. We have split the interfaces from the implementations (in order to use the interface server side). I've create a small example (see https://gist.github.com/auke-/90ef1405346d89d958fd1d1438a79579), which generates:
```javascript
function $forEachRemaining(this$static, consumer){
  checkCriticalNotNull(consumer);
  while (this$static.hasNext_0()) {
    this$static.next_0();
    alert_0('c property: ' + null.$_nullMethod());
  }
}
```
for the following Java snippet:
```java
  a.getListOfC().stream()
    .forEach(c -> Window.alert("c property: " + c.getCValue()));
```

**Comment by auke-** [comment]
It does work when there is some reference to the overlay implementation:
```java
  public static final class AOverlay extends JavaScriptObject implements A {
    private static final BOverlay anyNameB = JavaScriptObject.createObject().cast();
    private static final COverlay anyNameC = JavaScriptObject.createObject().cast();
    ...
  }
```

```javascript
function $forEachRemaining(this$static, consumer){
  checkCriticalNotNull(consumer);
  while (this$static.hasNext_0()) {
    alert_0('c property: ' + castToJso(this$static.next_1()).c);
  }
}
```

**Comment by rluble** [comment]
Thanks for the repro. The compiler keeps track of liveness for types for code pruning. This allows to remove method body that seem reachable in the code but only called with null as a qualifier, in which case the method itself is not executed, but an NPE is thrown. For Java types the task is easy if a `new A` (or a sublcass) is reachable then the type is live. 

For JSOs, since the compiler does not have visibility to the JavaScript code that instantiates the said object, the idea is a bit trickier. If an object is seen to be flowing from JavaScript to Java with a type of the JSO or of its interface then it is considered live. This consists of reaching  a cast, a jsni (or native `@JsMethod`) that returns the type and an exported method that receives it has a parameter (the code for that is in `ControlFlowAnalyzer` if you care to see the exact rules).

The rules have been simplified for JsInterop, which BTW is the recommended way to handle JavaScript interaction.

**Comment by ibaca** [comment]
Oh, overlays and code-pruner, always fighting each other 😉!
FYI Not totally sure but seems to be the same or pretty same situation than:
https://groups.google.com/forum/#!topic/google-web-toolkit-contributors/x2q03VEEIf4
https://github.com/ibaca/gwt-instantiable-inference-bug/blob/master/src/main/java/com/bacamt/ibaca/client/Bug.java

**Comment by rluble** [comment]
This is actually seems like a missing erasure cast in our lambda handling code. If you use a method reference instead it should work.

Can you verify that changing the offending code to

        a.getListOfC().stream().map(C::getCValue).forEach(c -> Window.alert("c property: " + c);

also solves the issue?

**Comment by rluble** [comment]
Fixed in https://gwt-review.googlesource.com/c/gwt/+/19940
