### ISSUE TITLE
Update Jetty to address CVE-2017-9735

### ISSUE THREAD

**Issue by msymons** [gwtproject/gwt#9567]
GWT-Dev v2.8.2 uses Jetty version 9.2.14.v20151106 which is subject to vulnerability [CVE-2017-9735](https://nvd.nist.gov/vuln/detail/CVE-2017-9735)

> Jetty through 9.4.x is prone to a timing channel in util/security/Password.java, which makes it easier for remote attackers to obtain access by observing elapsed times before rejection of incorrect passwords.

From the [issue that implemented the fix](https://github.com/eclipse/jetty.project/issues/1556), the vulnerability is addressed in:

* jetty-9.4.6.v20170531
* jetty-9.3.20.v20170531
* jetty-9.2.22.v20170606

**Comment by tbroyer** [comment]
Thanks for the report, but Jetty is only used for development, so "remote attackers" aren't in our threat model.

Also, any Jetty configuration (that would be needed to make use of Jetty authentication mechanisms) is only support on a "best effort" basis (i.e. it might work, but we don't guarantee it); and that `Password` class is otherwise hidden from webapps (so they can't use it, unless they themselves include jetty-util in the webapp's `WEB-INF/lib`).
