### ISSUE TITLE
GWT compilation fails when code uses javax.annotation.processing.Generated (e.g. code generated by Dagger)

### ISSUE THREAD

**Issue by tbroyer** [gwtproject/gwt#9612]
**GWT version:** 2.8.2 and HEAD-SNAPSHOT (20180423.054422-445)
**Browser (with version):** n/a
**Operating System:** n/a (Windows)

---

##### Description

Code that uses `javax.annotation.processing.Generated`, such as that generated by Dagger when using Java 9+, does not compile.
This is not the case when `javax.annotation.Generated` is used instead (but that one is discouraged in Java 9+).
Neither is emulated in GWT.
See https://github.com/tbroyer/gwt-maven-archetypes/issues/54
```
[INFO] --- gwt-maven-plugin:1.0-rc-9:compile (default-compile) @ basic-client ---
[INFO] Compiling module it.pkg.Basic
[INFO]    Tracing compile failure path for type 'it.pkg.BasicModule_ProvideIsAdminFactory'
[INFO]       [ERROR] Errors in 'file:/…/gwt-maven-archetypes/dagger-guice-rf-activities/target/test-classes/projects/basic/project/basic/basic-client/target/generated-sources/annotations/it/pkg/BasicModule_ProvideIsAdminFactory.java'
[INFO]          [ERROR] Line 4: The import javax.annotation.processing cannot be resolved
[INFO]          [ERROR] Line 7: Generated cannot be resolved to a type
```

##### Steps to reproduce

See https://github.com/tbroyer/gwt-maven-archetypes/issues/54

Simplified:
 * create a basic GWT project
 * annotate any class with `@javax.annotation.processing.Generated`
 * compile the project using Java 9 or Java 10
 * if using GWT HEAD-SNAPSHOT, try with various values of `-sourceLevel`, this can be reproduced in every case.

##### Known workarounds

In the case of Dagger, and annotation processors that conditionally use `javax.annotation.processing.Generated` vs. `javax.annotation.Generated` (vs. nothing) depending on the `SourceLevel` and/or presence in the compile classpath (such as those relying on auto-common 0.10 or 0.9), passing `--release 8` (auto-common 0.9 or 0.10) or `-source 8 -target 8` (auto-common 0.10) to JavaC will have them generate `@javax.annotation.Generated` instead.

I couldn't find a workaround if you need to use Java 9 or Java 10 sources.

**Comment by niloc132** [comment]
Can we not simply emulate the new annotation?

**Comment by tbroyer** [comment]
I have no idea why it fails and what would be the best solution (or _a_ solution), all I can tell for now is that it doesn't fail with `javax.annotation.Generated` which is not emulated either. Will have to do more testing.

**Comment by rluble** [comment]
IIRC Java 9 modules messed up some of the javax.annotations, in particular jsr305 and Generated. I only know this in passing.

Internally we use a couple of workarounds:
1. java --add-modules=java.xml.ws.annotation
  - This is where javax.annotation.Generated is now I think but this is deprecated
2. add tomcat-annotations-api-8.0.5.jar  to the class path.
 - javax.annotation.Generated is repackaged here;
3. if you also need jsr305 annotations then we can do
  --add-modules=java.xml.ws.annotation --patch-module=java.xml.ws.annotation=jsr305.jar

See [related Guava issue](https://github.com/google/guava/issues/2960) for context

I am not familiar at all with how the module stuff works in Java 9.

**Comment by rluble** [comment]
BTW, we do something of that sort [here](https://gwt.googlesource.com/gwt.git/+/master/dev/core/src/com/google/gwt/dev/javac/JdtCompiler.java#433) for LambdaMetaFactory and SerializedLambda

to compile Java 8 code on a Java 7 vm

**Comment by tbroyer** [comment]
@rluble `javax.annotation.Generated` is ok (even with Java 9 or 10!); it's `javax.annotation.processing.Generated` (Java 9+) that's the problem.

**Comment by JamesXNelson** [comment]
@tbroyer is  `javax.annotation.Generated` okay in Java 9+ when using both classpath and modulepath?  It would make sense that classpath is okay, since it should be following java 8 semantics (and packaging, apparently), but once modulepath is used, it _should_ be using module visibility semantics (which will require depending on the right modules [i.e. --add-modules, or making user modules depend on the right jdk modules]).

**Comment by tbroyer** [comment]
Haven't tried the module path (because… why would I? 😉)

**Comment by JamesXNelson** [comment]
heh.  well, with java 8 EOL in January 2019, module path might start getting more attention, and users may wind up trying to use it and being surprised.  If we are going to explicitly not support module path, it would likely be best to break loudly.

**Comment by axls** [comment]
@tbroyer FYI: I had noticed that GWT compiler cannot see annotations from bootstrap classpath (rt.jar for Java8 or system modules for Java9/10), and the compiler can see annotations from the regular application classpath. I don't know, it is expected behaviour of the compiler or not, but that may be the reason why `javax.annotation.processing.Generated` doesn't work, and`javax.annotation.Generated` works. By default, `javax.annotation.Generated` is always in the application classpath (not bootstrap classpath). For SDK `javax.annotation.Generated` will be packaged into gwt-dev (I suspects this one comes from `${GWT_TOOLS}/lib/tomcat/tomcat-annotations-api-8.0.28.jar`). For the maven version of the `gwt-dev` `javax.annotation.Generated` comes from `javax.annotation:javax.annotation-api` which is a transitive dependency for `org.eclipse.jetty:jetty-annotations`.

To be more precise - the compiler will not see annotation from bootstrap classpath that are from package that are not presented in application classpath. Try to add package `javax.annotation.processing` (even empty, just for checking) in your application, and I suspect that `javax.annotation.processing.Generated` will work.
The code responsible for this behaviour: https://github.com/gwtproject/gwt/blob/a8304147686d611be6ee14aae3b6a752432f1d80/dev/core/src/com/google/gwt/dev/javac/JdtCompiler.java#L602 and corresponigly https://github.com/gwtproject/gwt/blob/a8304147686d611be6ee14aae3b6a752432f1d80/dev/core/src/com/google/gwt/dev/javac/JdtCompiler.java#L1086

Bootstrap class loader always returns `null` here.

**Comment by tbroyer** [comment]
Fwiw, super-sourcing the annotation fixes the problem. I think we should super-source annotations that we want to support and are provided by the JDK (this includes **both** `javax.annotation.processing.Generated` and `javax.annotation.Generated`, even though the latter will also be found in the classpath and is not required to be super-sourced)

**Comment by tbroyer** [comment]
https://gwt-review.googlesource.com/c/gwt/+/21062

**Comment by gkdn** [comment]
I don't think `javax.annotation.Generated` is provided by JRE. Are you sure?

**Comment by niloc132** [comment]
The javax.annotation-api jar (included in all gwt builds by virtue of gwt-dev depending on jetty-annotations depending on javax.annotation-api) includes the `javax.annotation.Generated` class.

**Comment by tbroyer** [comment]
> All non-Java EE JSR 250 annotations were added to the Java SE with version 6 (Generated, PostConstruct, PreDestroy, Resource, Resources). They are located in the package javax.annotation.

Source: https://en.m.wikipedia.org/wiki/JSR_250

The fact that it's also provided in a third-party lib is what makes it work, contrary to javax.annotation.processing.Generated. While we could supersource only the latter, I don't see any reason not to supersource the former too.
If one excludes the third-party dep that provides javax.annotation.Generated, there are good chances that code would still compile with javac, but would then fail with GWT.

**Comment by gkdn** [comment]
For some reason I thought javax.annotation.Generated was never provided in JRE so I didn't want to carry it over to J2CL. Probably that was a Google thing. If it is there, I don't have any problems of introducing it.
