### ISSUE TITLE
JsInterropt with lambdas, optimization level = 9, and OBF turned on breaks

### ISSUE THREAD

**Issue by cogman** [gwtproject/gwt#9628]
**GWT version:** 
2.8.2
**Browser (with version):**
All (tested chrome 68.0.3440.106 and firefox  61.0.2)

**Operating System:** 
Windows 10 (affects linux as well)
---

##### Description
See reproduction at https://github.com/cogman/brokegwt/blob/master/brokegwt/src/main/java/com/garbage/client/borked.java

Doing a detailed + draft compile works correctly.

##### Steps to reproduce
https://github.com/cogman/brokegwt

##### Known workarounds
Using draft compile or avoiding lambda and method references mixing with jsinteropt.   Doing "Optional.isPresent()" and "Optional.get()" works in this example.

**Comment by niloc132** [comment]
I think there is a mistake in your code, perhaps you can confirm?

```
package com.garbage.client;

import jsinterop.annotations.JsType;

@JsType(isNative = true)
public class Native {
	public String innerHTML;
}
```

You have no name or namespace on this, so GWT assumes this means that there exists a `com.garbage.client.Native` type in the browser (supplied by some other JS, which possibly could be from GWT or anything else). Since it cannot find this, the lambda `((v) -> v.innerHTML)` (or something else, i'm not quite sure which) can't be correctly checked. Here is that lambda, compiled to JS:

```
var Qb = yd(Vf, 'borked/0methodref$querySelector$Type', 26);
fd(27, 1, {}, u);
_.o = function t(a) {
    return q(),
    Gb(a, $wnd.com.garbage.client.Native).innerHTML
}
;

**Comment by cogman** [comment]
The exact case we had was a jwt_token from the "jwt_decode".  It would return an anonymous object back (json deserialization of the base64 decoded token).

So the return type would look something like

`function foo(){ return {username: "bob", otherField: "stuff" }; }`

It did catch us off guard because the draft compile doesn't have a problem without the global namespace but the OBF + optimized compile does.

**Comment by cogman** [comment]
I've updated the example with global everywhere and and a more clear example (not using the document.querySelector, but instead introduced a simple foo method) still broken on optimized/obf not on draft.

**Comment by niloc132** [comment]
Thanks for the update - this still doesn't make sense though, and for the same reason, you've said "There exists a type already in the JS environment when this GWT module loads: it is called Native, and lives in the global namespace." When GWT builds a lambda around that, it fails, since it needs to perform a cast (so that Optional's generics make sense).

I can't speak as to why this isn't breaking for you in PRETTY (and haven't confirmed that it works there myself, but only read the code this time without compiling), but the code doesn't make sense as written _unless_ you do one of these:

Add something like this to your JS to match the Native.java declaration:
```
function Native() {}
```

JS Functions can also act as constructors (and in turn, types), so now we have a type called Native as GWT has been told to expect. Optionally (especially if you are going to use the closure compiler later on...) add a username field inside of there (in the ctor, or on the prototype), so that a string username is expected. However, this is unlikely to work in your case of decoding JSON as you described in your last post. Alternatively...

Fix the JsType annotation to indicate that Native is just a way to describe a plain JS Object:
```
@JsType(isNative = true, namespace = JsPackage.GLOBAL, name = "Object")
public class Native {
```
Now GWT will actually find a matching JS object when you tell it to expect the Native Java type, and further, casts and instanceof checks will not fail. (As in my last answer, `*` or `?` could also work as well, see the closure compiler docs on those, but I personally would stick with `Object` here.)

**Comment by cogman** [comment]
Ok, That works for me.  Thanks.

I'm ok with closing this case unless you wanted to look into why the draft compile.
