### ISSUE TITLE
Implement Class.isAssignableFrom()

### ISSUE THREAD

**Issue by Jos31fr** [gwtproject/gwt#9630]
**GWT version:** 2.8.2
**Browser (with version):** All
**Operating System:** Windows

---

##### Description

The method Class.isAssignableFrom(Class<?> cls) is not implemented in GWT

##### Steps to reproduce

```java
System.out.println(Object.class.isAssignableFrom(String.class));
```

Error is :
[ERROR] The method isAssignableFrom(Class<String>) is undefined for the type Class<Object>

##### Known workarounds
Implement a static method to do the job
```java
public static boolean isAssignableFrom(Class<?> c1, Class<?> c2) {
		while (c2 != null) {
			if (c2.equals(c1)) {
				return true;
			}
			c2 = c2.getSuperclass();
		}
		return false;
	}
```

**Comment by tbroyer** [comment]
`Class` emulation is not designed to provide any kind of reflection, as this can (and should) be done at compile time (see http://www.gwtproject.org/doc/latest/FAQ_Client.html#What_is_Deferred_Binding%3f for instance)

Btw, your workaround doesn't consider superinterfaces (and `Class` doesn't emulate this).

Adding this information to `Class` will bloat applications, whereas 99.9% of them will never use it.

@rluble or @gkdn  could comment on this?

**Comment by niloc132** [comment]
Unfortunately, your workaround misses out on any possible interfaces which might be implemented in the hierarchy, and so could not be used as a possible implementation of this deliberately unimplemented method. While object instances do have type data attached to them (so that you can do instanceof or cast checks against some reference type), Class instances do not, presumably to keep compiled sizes down in the majority of applications when they are not required (maybe someone else can clarify further here).

**Comment by Jos31fr** [comment]
You're right this will not work on all case and is not the correct behavior of this method.
I'm closing the issue
