### ISSUE TITLE
ColumnSortList Can not push element that have same Column but ascending is different.

### ISSUE THREAD

**Issue by bxf12315** [gwtproject/gwt#9660]
**GWT version:** 
**Browser (with version):** 
**Operating System:** 

---

##### Description

as subject.

**Comment by tbroyer** [comment]
Because it makes no sense.

It's unclear what you're reporting though (there's a reason we ask you to fill in the issue template): the current behavior is clearly documented.

**Comment by bxf12315** [comment]
@tbroyer Now, if we add a ColumnSortInfo, it have same Column but it's ascending is not same, the ColumnSortInfo also will remove from ColumnSortList. So the issue let our get wrong behavior for sort event.

**Comment by tbroyer** [comment]
Can you then please explain what you're doing (steps to reproduce, can be code snippet, but a [minimal, complete project](https://stackoverflow.com/help/mcve) would be better), the behavior you're expecting, and the behavior you're seeing instead (and why it's a problem)?
Don't hesitate to "show" (code, screenshots, ascii art, markdown tables, etc.) rather than "describe" if you have difficulties with English (you could also try writing in Chinese –I see you're in/from Beijing– but I'm not sure about the accuracy of Google or Bing Translate or similar tools…)

I suppose all of this also depends on how you compare column values: are you using a `ListHandler` (see also #7880) or doing the sorting yourself?

**Comment by bxf12315** [comment]
@tbroyer 
''ColumnSortList list = new ColumnSortList();
    assertEquals(0, list.size());

    ColumnSortInfo info0 = createColumnSortInfo(true);
    ColumnSortInfo info1 = createColumnSortInfo(true);
    ColumnSortInfo info2 = createColumnSortInfo(false);

    list.push(info0);
    list.push(info1);
    assertEquals(1, list.size());

    list.push(info2);
    assertEquals(2, list.size());''

**Comment by tbroyer** [comment]
As I said, the current behavior is clearly documented, and that code snippet doesn't explain **why** the behavior should change.

You said:

> So the issue let our get wrong behavior for sort event.

What exact problem does it cause you that `info2` replaces `info1` in the list?

`ColumnSortList` alone is not enough to explain it; you need to show something with a `CellTable` or `DataGrid`, and a `ColumnSortEvent.Handler`.
You can attach a ZIP file, or link to a GitHub repository, of a GWT project demonstrating the problem; possibly with screenshots or whatever explains the actual problem you're seeing: "I want X, but it does Y" (you traced that Y comes from the `ColumnSortList` handling of `ColumnSortInfo`s for the same `Column`, but before tracing it there, you necessarily saw a behavior you weren't expecting, that's what we need to know; because changing `ColumnSortList`'s behavior might not be the solution, or the only solution, to your problem).

**Comment by jnehlmeier** [comment]
@bxf12315 @tbroyer The code snippet above is wrong anyways because `ColumnSortList` uses reference equality (==) on the column to find existing columns in the sort list. In the snippet above all three `ColumnSortInfo` instances will be pushed to the list and its size will be 3 at the end.

**Comment by bxf12315** [comment]
> As I said, the current behavior is clearly documented, and that code snippet doesn't explain **why** the behavior should change.
> 
> You said:
> 
> > So the issue let our get wrong behavior for sort event.
> 
> What exact problem does it cause you that `info2` replaces `info1` in the list?
> 
> `ColumnSortList` alone is not enough to explain it; you need to show something with a `CellTable` or `DataGrid`, and a `ColumnSortEvent.Handler`.
> You can attach a ZIP file, or link to a GitHub repository, of a GWT project demonstrating the problem; possibly with screenshots or whatever explains the actual problem you're seeing: "I want X, but it does Y" (you traced that Y comes from the `ColumnSortList` handling of `ColumnSortInfo`s for the same `Column`, but before tracing it there, you necessarily saw a behavior you weren't expecting, that's what we need to know; because changing `ColumnSortList`'s behavior might not be the solution, or the only solution, to your problem).

My situation is, sometime I want save column sort behavior, when I want recovery the situation, I need reload old Sorted Column and push it inito ColumnSortList, but if the ColumnSortList already have the Column(ascending is not same), so I will lose the info.
But I think you are right, behavior might not good approach. I need try to find some workaround way.

**Comment by bxf12315** [comment]
> @bxf12315 @tbroyer The code snippet above is wrong anyways because `ColumnSortList` uses reference equality (==) on the column to find existing columns in the sort list. In the snippet above all three `ColumnSortInfo` instances will be pushed to the list and its size will be 3 at the end.

@jnehlmeier Yes , you are right, but if it generate js code, it is working fine.

**Comment by jnehlmeier** [comment]
> My situation is, sometime I want save column sort behavior, when I want recovery the situation, I need reload old Sorted Column and push it inito ColumnSortList, but if the ColumnSortList already have the Column(ascending is not same), so I will lose the info.
> But I think you are right, behavior might not good approach. I need try to find some workaround way.

 A `Column` instance can only exist once in the `ColumnSortList` because a `Column` can not be ascending and descending at the same time. Thus when you make a copy of the information in `ColumnSortList` you should make sure that you keep the order the same in your copy. Then to restore the `ColumnSortList` you have to `push` your copied information backwards (`push` is the same as `insert(0, info)`) . That should give your the original sorting.

But you have to make sure to use the same column instance used for creating the CellTable / DataGrid.

**Comment by tbroyer** [comment]
So, it looks like you are somehow misusing `ColumnSortList`, and should instead copy state to a plain `List` instead to be able to restore it later.
