### ISSUE TITLE
How to use GWT with frida ?

### ISSUE THREAD

**Issue by eix128** [gwtproject/gwt#9676]
Hi , i have seen great framework named ; "Frida"
It injects Javascript and ( Google v8 javascript interpreter ) into native apps and making reverse engineer for the app.

There is some
https://medium.com/@ved_wayal/hail-frida-the-universal-ssl-pinning-bypass-for-android-e9e1d733d29

Some example for javascript
https://codeshare.frida.re/@pcipolloni/universal-android-ssl-pinning-bypass-with-frida/

is it possible to use frida with GWT as proxy layer for javascript ?
That would be more easy to use java.

**Comment by niloc132** [comment]
I'm curious about exactly what you had in mind for that. For example, there is this sample code from  your second link
```javascript
setTimeout(function(){
    Java.perform(function (){
    	console.log("");
	    console.log("[.] Cert Pinning Bypass/Re-Pinning");

	    var CertificateFactory = Java.use("java.security.cert.CertificateFactory");
	    var FileInputStream = Java.use("java.io.FileInputStream");
	    var BufferedInputStream = Java.use("java.io.BufferedInputStream");
	    var X509Certificate = Java.use("java.security.cert.X509Certificate");
	    var KeyStore = Java.use("java.security.KeyStore");
	    var TrustManagerFactory = Java.use("javax.net.ssl.TrustManagerFactory");
	    var SSLContext = Java.use("javax.net.ssl.SSLContext");

	    // Load CAs from an InputStream
	    console.log("[+] Loading our CA...")
	    var cf = CertificateFactory.getInstance("X.509");
	    
	    try {
	    	var fileInputStream = FileInputStream.$new("/data/local/tmp/cert-der.crt");
	    }
	    catch(err) {
	    	console.log("[o] " + err);
	    }
	    
	    var bufferedInputStream = BufferedInputStream.$new(fileInputStream);
	  	var ca = cf.generateCertificate(bufferedInputStream);
	    bufferedInputStream.close();
```

The Java class seems to come from https://github.com/frida/frida-java-bridge/blob/master/lib/class-factory.js - the export of that file is ClassFactory, which at least appears to be shaped like the `Java` instance in that code. It appears that the code assumes something like this, before the above snippet (assuming the ClassFactory is properly inherited:

```javascript
const Java = new ClassFactory();
```

Corresponding Java would look like
```java
ClassFactory f = new ClassFactory();
```
and then you could use it, sort of as expected - you would need some kind of GWT model for the JS classes... which model Java:

```java
FridaClass<FridaBufferedInputStream> bufferedInputStreamClass = f.use("java.io.BufferedInputStream");
FridaBufferedInputStream bufferedInputStream = bufferedInputStreamClass.$new(...);
//...
bufferedInputStream.close();
```

That said, you'd need to create a jsinterop type for each frida type, and for each Java type which you used _through frida_.

At first glance it seems like you could just write plain java code and have gwt/j2cl translate, including all of the frida source, so you could directly inject Java into Java, but I don't think this will be that simple - the goal of this frida JS code is to let you write real code which _doesn't_ run in the same environment as the rest of the platform, so GWT would have a hard time telling if you were making java code to run inside android, or to represent your own logic. As as example, consider something like the `console.log` lines - would you expect to be able to write `System.out.println()` or the like and would those lines print to your debugger, or inside Android's own logger (which might not be easily visible to you)? If you called `new ArrayList()`, would you expect it to give you a list you can iterate in your own env, or create a list that lives inside of android? 

---

I think the first version would make more sense, and depending on what kind of code you are writing, you'll have to find out how Frida's JS responds to method overloading (which makes sense in Java, but JS just treats all overloaded methods as if they were the same function). Take a look also at something like https://github.com/frida/frida-java-bridge/issues/104, showing the interesting JS that needs to be generated in order to call a superclass's version of a method being overridden - trying to change GWT to generate this sort of JS might be more trouble than it is worth, easier to just reimplement frida bindings in Java.

I also think this might be a better mailing list or stackoverflow topic than a issue on the GWT tracker. You could also consider creating an issue on frida's own tracker, asking about a Java API, since they also have python and c# bindings already.

**Comment by niloc132** [comment]
Closing from lack of response.
