### ISSUE TITLE
TypeError: Cannot read property 'T' of null

### ISSUE THREAD

**Issue by morten-holm** [gwtproject/gwt#9695]
**GWT version:2.9.0**
**Browser (with version):Chrome 83.0.4103.106 (doesn't matter)** 
**Operating System:macOS (also not important)** 

---

##### Description
Linked example works fine when served from gwt:codeserver, but not when compiled for production.

It is a simple cast of a native js object having named properties to on object of a private static class having @JsProperty annotated properties.

##### Steps to reproduce
I have produced an example here: https://github.com/morten-holm/gwtbug

$ mvn clean install 
$ mvn -pl *-server jetty:run

open browser on http://localhost:8080 and look in console.
##### Known workarounds
Serve from codeserver or enable '-draftCompile'.

**Comment by niloc132** [comment]
The error is because GWT is emitting a `null.T` expression, which is GWT's way of saying "this code will always fail, so instead of generating the full broken code, just generate a simple failure".

This doesn't happen in draft mode, since the compiler doesn't do the extra work of checking if the code doesn't make sense.

The bug however is not in the compiler, your code is incorrect:
```
public class Worker {

    public void work() {
        String json = "{ \"payload\": { \"property1\": 1.0, \"property2\": \"2.0\" }}";
        JsPropertyMap<?> obj = Js.uncheckedCast(JSON.parse(json));
        Object payload = obj.get("payload");
        Mapped mapped = Js.uncheckedCast(payload);

        DomGlobal.console.log("Hello World", mapped.property2, mapped.property1);
    }

    private static class Mapped {
        @JsProperty
        public double property1;

        @JsProperty
        public String property2;
    }

}
```
```
function ed() {
    var a;
//...
    a = $wnd.JSON.parse('{ "payload": { "property1": 1.0, "property2": "2.0" }}');
    $wnd.goog.global.console.log('Hello World', null.T, null.T)
}
```
The compiler has determined that a) `Mapped` is never created in Java, and b) `Mapped` is not a native JS type, so it can't be created outside of Java either (either from JS or from your JSON, etc). It is correct in this. In the optimized generated code, the compiler has figured out that the only legal instance of `Mapped` is the value `null` - it also removed the obj.get call and the extra fields for `payload` and `mapped` (I'm unsure why it didn't remove `obj`), since they are unnecessary now.

You must either mark it as a native type, or expose it to JS (both mark as JsType then also enable generating jsinterop exports), or find a different way to express this.

Note also that you must use Js.uncheckedCast here, since otherwise you would correctly get a runtime error since the Object payload is _not_ a Mapped instance. Marking Mapped as native and name=Object will solve that. Another option is to make Mapped a native interface (with getters, possibly setters instead of fields). Yet another option could be to cast payload to JsPropertyMap and read values out that way.

Suggest following up in a StackOverflow or mailing list post or chat in https://gitter.im/gwtproject/gwt to discuss this further.
