### ISSUE TITLE
GWT Signup flow with push state

### ISSUE THREAD

**Issue by jhonToni** [gwtproject/gwt#9710]
I developing a signup app for my project.
I want to split the form inputs into three pages with routes: 
1=> "`/signup/register?lang=en-US`";
2=> "`/signup/userdetails?lang=en-US`";
3=> "`/signup/welcome?lang=en-US`".
All paths mustn't have the '#'.

The user mustn't have access to route 2 if he hasn't completed the step 1.
Is possible implement this in my GWT application ?

Note: I use Spring boot and GTW 2.9.

**Comment by niloc132** [comment]
This is not the right place to ask a question like this - good ideas include the mailing list (where I see you started two threads already, and Frank Hossfeld replied with one option to one of them), stack overflow (the "gwt" tag will help), or gitter chat at https://gitter.im/gwtproject/gwt are some good options.

With that said, the client can use pushState to help watch the URL change without fetching content right away from the server, but the server does need to know how your routes work to a degree, so that it can always load the app properly, and let it see where the user is, what page should be rendered. Yes, this is possible to implement in GWT (with very few exceptions, anything you can do in plain JS can be done with GWT and Java), but try one of those other places to ask questions instead to discuss further.
