### ISSUE TITLE
CSP error on Chromium-based browsers

### ISSUE THREAD

**Issue by Zlika** [gwtproject/gwt#9725]
**GWT version:** 2.9.0
**Browser (with version):** Any Chromium-based browser (Chromium, Chrome, Chromium-based Edge)
**Operating System:** Tested on Linux and Windows

---

##### Description
The following error is triggered by the browser:

```
Some messages have been moved to the Issues panel.
VM11:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' 'unsafe-inline'".

    at <anonymous>:1:1
    at m (Geot.nocache.js:9)
    at Geot.nocache.js:10
    at HTMLDocument.d (Geot.nocache.js:6)
```

What is really strange with this error is that it disappears if the project is compiled with -Dgwt.style=PRETTY.
When this problem occurs (i.e. when gwt.style has its default value of OBFUSCATED), the following code is responsible for the error:
![chrome_csp_gwt](https://user-images.githubusercontent.com/1705407/108508582-52975680-72bc-11eb-845d-7e88246bf521.png)

In this obfuscated code, we can see that there is at line 203 a test to detect if we are using a Chrome-based user. If this is the case, the CSP error is triggered at line 214. At this line, we can see that the 'g' variable is a script tag containing a huge "eval(...)" function. This is this unsafe eval that triggers the CSP error.
On the other hand, if we use another browser (e.g. firefox), the other part of the "if/else" block is executed, and in this part the 'g' variable holds a script tag without any "eval()" function.

As I'm not using any "eval()" function in my code, and I don't even have some code that tests the name of the browser, I suppose that this function is directly generated by GWT and I don't have any control on it.

Is it a known problem and is there any workaround available (except lowering the CSP protection level by accepting unsafe eval functions?).
Thanks for your answers.

**Comment by niloc132** [comment]
This is part of the linker script, which is configurable. Two files have a snippet in them which look like this, but only one seems to actively be in use, `installScriptEarlyDownload.js`. That is part of the CrossSiteIframeLinker, when the `installCode` configuration property is set to true (or unset, in which case it will default to true for obfuscated JS). 

You can turn `installCode` off by setting it in a configuration property in your .gwt.xml, or can switch to the `direct_install` linker which defaults it to false instead.

Turn it off:
```
  <set-configuration-property name="installCode" value="false"/>
```
Switch to direct_install linker, a subclass of the default cross site iframe linker, and still SDM-compatible. From it's Javadoc:
```
/**
 * A linker that adds a script tag directly to the iframe rather than downloading the
 * JavaScript code as a list of strings and then installing it into the iframe.
 *
 * <p>(This linker is exactly like CrossSiteIframeLinker except that it defaults to
 * installCode=false.)
 */
public class DirectInstallLinker extends CrossSiteIframeLinker {
```
To turn this on, in your .gwt.xml:
```
  <add-linker name="direct_install"/>
```

--
The "Chrome" check is apparently because of a bug in chrome itself, filed by a googler and ignored until it staled out https://bugs.chromium.org/p/chromium/issues/detail?id=90707. The nature of the bug is that sourcemaps don't work in Chrome without eval, but SDM deliberately turns off `installCode` anyway, which avoids this situation. It seems like this could at least remove the chrome-specific workaround, but perhaps offer some other flag to reenable it, rather than it being the default.

**Comment by dcheung2** [comment]
![image](https://user-images.githubusercontent.com/30869873/134661349-ab2c5c33-8bdb-43a3-93de-eaf3d0ddbf86.png)

I guess the workaround doesn't need anymore since Chrome did fix the source map problem.
