### ISSUE TITLE
GWT frontend failed to load due to iframe sandbox restrictions

### ISSUE THREAD

**Issue by jeanbritz** [gwtproject/gwt#9729]
GWT version: 2.9.0 
Browser (with version): Chrome 90.0.4430.93
Operating System: Windows 10

---

##### Description
I have encountered an issue on one of our client sites, where they have a link (embedded in an iframe) to open our GWT web application. The iframe on client's site causes our GWT application not to load properly.

##### Steps to reproduce

Possible way to replicate it:
External webpage:
```
<html>
<iframe sandbox="allow-scripts allow-forms allow-same-origin allow-popups allow-modals allow-downloads" src="content-frame.html">
</iframe>
</html>
```

content-frame.html
```
<html>
<a href="https://example-gwt-app.com/gwt-app/" target="_blank">Click here to open GWT app</a>
</html>
```

Click on the link to open the GWT app.

Our GWT app uses the `xsiframe` linker because it is a split module project.
When the web page is trying to load, I think the iframe tries to change the address by appending a `#` after the root URL
and that causes a browser error.

Browser console error:
```
Unsafe attempt to initiate navigation for frame with URL 'https://example-gwt-app.com/gwt-app/' from frame with URL 'https://example-gwt-app.com/gwt-app/'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.
```

##### Known workarounds
Workaround for this is to edit `gwt-dev.jar!/com/google/gwt/core/ext/linker/impl/installLocationIframe.js`

And add the following:
```
var scriptFrame = $doc.createElement('iframe');
scriptFrame.id = '__MODULE_NAME__';
scriptFrame.setAttribute('sandbox', 'allow-scripts allow-forms allow-same-origin allow-popups allow-modals allow-downloads allow-top-navigation allow-top-navigation-by-user-activation');
```

##### Links to further discussions
* https://gitter.im/gwtproject/gwt

**Comment by tbroyer** [comment]
Because this is using `target="_blank"`, this is IMO not a problem with GWT proper.
If the client wants to authorize your app, the sandbox should have `allow-popups-to-escape-sandbox` so that the sandbox doesn't propagate to the opened window: https://html.spec.whatwg.org/multipage/origin.html#attr-iframe-sandbox-allow-popups-to-escape-sandbox

Because GWT doesn't really control what happens inside its iframe (apps could do anything), it would have to enable every single sandbox flag (and keep track of new ones that could be added later to add them too). I'm not sure we want to support that out of the box, knowing that there is a workaround.

Regarding your workaround, you don't need to patch GWT, you should rather extend `CrossSiteIframeLinker` and override `getJsInstallLocation` to return your own copy of the `installLocationIframe.js` with the changes. Then register your linker with `<define-linker>` and activate it with `<add-linker>`. Also, remove `allow-top-navigation-by-user-activation`as it's a subset of `allow-top-navigation` and it's an error to have both: https://html.spec.whatwg.org/multipage/origin.html#sandboxing:sandboxed-top-level-navigation-with-user-activation-browsing-context-flag-2

**Comment by jeanbritz** [comment]
Hi @tbroyer, 
Thanks for your response! I am not very knowledgeable on iframe sandbox attributes, therefore I thank you for providing more information regarding them.
The easiest fix would be is to ask the client to include `allow-popups-to-escape-sandbox` on their originating iframe, but that is not going to happen, unfortunately.
I think your approach to override the `CrossSiteIframeLinker` is _much_ better than trying to patch GWT. I have managed to get it to work in Development Mode, but I get the custom linker class not to be found when I compile the GWT project with Ant.

Regardless of the compilation issue, I am closing this issue.
