### ISSUE TITLE
Upgrade validation-api to jakarta.validation-api

### ISSUE THREAD

**Issue by Jos31fr** [gwtproject/gwt#9743]
**GWT version:**  2.9.0
**Browser (with version):** All
**Operating System:**  All

---

##### Description

Could you upgrade the validation api of GWT to jakarta api version 2 or version 3 ?
We cannot use the latest hibernate validators due to API incompatibility. Hibernate validator 4.1.0 is now 11 years old and have several security issues

Jakarta api version 3 could be a good candidate, because they have renamed the javax.validation package. It could help to provide at the same time version 1 and version 3 api support

**Comment by tbroyer** [comment]
Bean Validation in GWT has been deprecated since 2.8.0 (released in 2016) after being unmaintained for years.

If you properly split your client-side and server-side code to have clearly separate classpaths, there's no reason you couldn't use Jakarta Bean Validation on the server with a recent version of Hibernate (if you're using RequestFactory, then you're de-facto limited to the `javax.validation` namespace, so an older version of Hibernate, but not necessarily 4.1.0).

**Comment by Jos31fr** [comment]
Hi Thomas,

The purpose is indeed to have the same validation code either on client and server side. I use the same constraint objects on both side.
If validation is deprecated on gwt, what is the recommended way of validate on client side now?

**Comment by tbroyer** [comment]
https://gitlab.com/ManfredTremmel/gwt-bean-validators/-/tree/master/gwt-bean-validators-engine is Beans Validation 2.0 compatible (i.e. still `javax.validation`, based on Hibernate Validator 6.2.0.Final)

**Comment by Jos31fr** [comment]
Thanks for you answer, it's what I need. I have some ASM problems when I add this library but I will try to find why.

**Comment by Jos31fr** [comment]
OK I solved this problem by putting validation-api 1 / hibernate-validator 4 on provided and validation api 2 / hibernate validator 6 on compile scope
GWT is using validation api 1 to make his JS code, then validation api 2 is deployed on the war file
