### ISSUE TITLE
Long.toBinaryString is broken in GWT 2.10.0

### ISSUE THREAD

**Issue by step76** [gwtproject/gwt#9764]
**GWT version:**  2.10.0
**Browser (with version):** Chrome 103.0.5060.134
**Operating System:** Windows 10

---

##### Description

In previous GWT versions the method `Long.toBinaryString` was broken for negative values, but now seems to be broken for values higher than `Integer.MAX_VALUE`.

##### Steps to reproduce

Try to call `Long.toBinaryString(3218270003L)` and you get a **negative** binary number.

**Comment by niloc132** [comment]
Thanks for the bug report, I've reproduced it and added a couple of tests to help confirm the fix.

The bug appears to have been introduced by 7616ceb5fbfe693514116829aa7a5d33c22ef054. This patch assumed that if all high bits are zeros, then the number is a valid java `int`. This isn't correct however - a negative `int`, cast to a `long`, does not have the same low 32 bits (the "sign" bit is the highest bit).

It looks like a similar change was applied to j2cl: https://github.com/google/j2cl/blob/master/jre/java/java/lang/IntegralToString.java#L63-L66. There is an important distinction - instead of Integer.toString, there is an intToUnsignedString call, which doesn't exist on the GWT side. Fortunately, both commits came with tests to confirm their new changes, unfortunately it isn't possible to run j2cl tests in open source, so we're restricted to writing sample apps to test out various values. 

I've made a patch that creates a few tests that targets this case (positive longs that if truncated look like negative ints), and changes Integer.toString to instead Integer.toUnsignedString to fix that issue. It also has a speculative change to remove getHighBits in favor of just doing a range check of the number against two constants, but I'll confirm that performance is better with that before taking away "draft" status.
