### ISSUE TITLE
Gwt emulation issue with java 11

### ISSUE THREAD

**Issue by gwtdevlpr** [gwtproject/gwt#9803]
GWT version:2.9.0
Browser (with version):Chrome 110
Operating System:Windows 10 

---

##### Description
Earlier the versions were gwt 2.8.2 and java 1.8 and the gwt project has jre classes to be emulated for various reasons from different packages like java.io, java.net etc which was working fine. One such example is src/emul/java/net/URL.java which has package name java.net working fine till now. And i have gwt.xml file under src folder with <super-source path="emul"/>. 
**Problem:** While java version is upgraded to java 11, i see errors in eclipse stating that "The package java.net conflicts with a package accessible from another module: java.base" and i tried to patch the same in my ant build file using <compilerarg line="--patch-module java.base=${src.path}/emul/" >.  Ant build which was fine in earlier versions (gwt 2.8.2 and java 8), after upgrade is now throwing
projects\java-emulation\src\emul\java\net\URL.java:1: error: package exists in another module: java.base
    [javac] package java.net;

**Comment by gwtdevlpr** [comment]
@tbroyer I came across many solutions from you in stackoverflow etc, kindly help on this.

**Comment by jnehlmeier** [comment]
Your `Emul.gwt.xml` should either be in `src` and have content `<super-source path="emul"/>` or in `src/emul` and have content `<super-source path="."/>` or just `<super-source />`.

You should not use `<source path="...."/>` for emulated JRE classes.

Does that help?

**Comment by niloc132** [comment]
(This would probably be better as a StackOverflow question, or a quick discussion at https://gitter.im/gwtproject/gwt instead of a bug report.)

Without specific details of what you are doing and the contents of your project, almost certainly what you are doing isn't expected to work. Instead, JRE emulation (or other emulation of packages that aren't part of your project) should be written as "super source". That is, these aren't sources you want to give to the Java compiler itself (which is what is giving you the error here, not the GWT compiler). We got "lucky" that this might have worked before JPMS, but as of Java 9 it will definitely fail with the error you received.

At https://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModuleXml, check out the heading "Overriding one package implementation with another":

> The <super-source> tag instructs the compiler to “re-root” a source path. This is useful for cases where you want to re-use an existing Java API for a GWT project, but the original source is not available or not translatable. A common reason for this is to emulate part of the JRE not implemented by GWT.

Every .gwt.xml file implicitly has a `<super-source path="super" />` entry, which you can use to put your emulation in. For example, if your module was `com/example/project/Project.gwt.xml`, you would put `URL.java` at `com/example/project/super/java/net/URL.java`.

I can't know without more information from you what `src/emul` means for your project setup, but I would guess this is a source directory of only super source. Add this extra path, and mark this as only containing resources for your classpath, rather than java sources. Then the Java compiler won't attempt to compile it, and GWT will recognize it as part of your project's super-source, to be used instead of whatever other types can be found on the classpath.

**Comment by gwtdevlpr** [comment]
java-emulation.gwt.xml was earlier under src itself with <super-source path="emul"/> and was working fine till i upgraded. However i tried your suggestion too as shown in screenshot below. I am still facing the error from ant build.
   [javac] C:\projects\gwt-java-emulation\src\emul\java\awt\Color.java:1: error: package exists in another module: java.desktop
    [javac] package java.awt;
    [javac] ^
    [javac] C:\projects\gwt-java-emulation\src\emul\java\awt\Component.java:1: error: package exists in another module: java.desktop
    [javac] package java.awt;
    [javac] ^
    [javac] C:\projects\gwt-java-emulation\src\emul\java\awt\Dimension.java:1: error: package exists in another module: java.desktop
    [javac] package java.awt;
    [javac] ^
    [javac] C:\projects\gwt-java-emulation\src\emul\java\awt\Font.java:1: error: package exists in another module: java.desktop
    [javac] package java.awt;
    [javac] C:\projects\gwt-java-emulation\src\emul\java\net\URI.java:18: error: package exists in another module: java.base
    [javac] package java.net;

**Comment by gwtdevlpr** [comment]
@niloc132 Any inputs on the above error pls?

**Comment by niloc132** [comment]
The error is that you shouldn't be giving these sources to javac. If javac can't see them, it will stop giving the error.
