### ISSUE TITLE
Java 11 JRE emulation

### ISSUE THREAD

**Issue by rjeeb** [gwtproject/gwt#9831]
Methods to support:

[String](https://github.com/gwtproject/gwt/pull/9975):
- `lines()`
- `isBlank()`
- `format()` (will not implement, this is missing deliberately from earlier versions of String)
- `repeat()`
- `stripTrailing()`
- `stripLeading()`
- `strip()`

[Predicate](https://github.com/gwtproject/gwt/pull/9862) (done): 
- `not()`

[OptionalDouble](https://github.com/gwtproject/gwt/pull/9853) (done):
- `isEmpty()`

[OptionalDouble](https://github.com/gwtproject/gwt/pull/9853) (done):
- `isEmpty()`

[OptionalLong](https://github.com/gwtproject/gwt/pull/9853) (done):
- `isEmpty()`

CharSequence was split into https://github.com/gwtproject/gwt/issues/9991 so this could be closed as complete.

**Comment by niloc132** [comment]
`Predicate` and `Optional*` are all merged. 

`String.format()` is likely not feasible - it requires parsing the format string at runtime, and handling the various possible patterns. That sort of code can't be optimized by the compiler without knowing ahead of time what all format strings will be. 
https://github.com/gwtproject/gwt/blob/e981e97325e0bbf8b16b407143ac297d7f07be01/user/super/com/google/gwt/emul/java/lang/String.java#L71-L73

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Formatter.html#syntax

In theory we could require that the format param will be a string literal and pre-compile the formats so that unused formatting code can be pruned. In practice, that sort of change likely wouldn't be accepted to j2cl, so we should consider carefully if we want to introduce that incompatibility.

**Comment by zbynek** [comment]
Also CharSequence.chars is already implemented: https://github.com/gwtproject/gwt/blob/22ff07e00d2d0d9b224397cbfc2cb7e2e248bf7d/user/super/com/google/gwt/emul/java/lang/CharSequence.java#L41

**Comment by niloc132** [comment]
Closing as fixed, all emulation mentioned here is fixed (CharSequence methods split into 
https://github.com/gwtproject/gwt/issues/9991 for later followup).
