### ISSUE TITLE
Can't set UNNECESSARY roundingMode

### ISSUE THREAD

**Issue by hhlTer** [gwtproject/gwt#9926]
##### Description
When I try to compare two values with 2 numbers after dots I can't use UNNECESSARY RoundingMode. 
In the result I am receive the ArithmeticException according to the documentation: if roundingMode==UNNECESSARY and the specified scaling operation would require rounding.

It is a most confusing thing that I have ever seen. Why do I haven't possibility to receive numbers after dots without rounding? 
Why existing functionality throws exception?

##### Steps to reproduce
        BigDecimal b1 = new BigDecimal(91.0202).setScale(2, RoundingMode.UNNECESSARY);
        BigDecimal b2 = new BigDecimal(91.0202).setScale(2);

**Comment by niloc132** [comment]
I'm not understanding what you expect to happen here - when I run either line from a normal JVM (i.e. not GWT), I get an exception:

```
Exception java.lang.ArithmeticException: Rounding necessary
      at BigDecimal.commonNeedIncrement (BigDecimal.java:4653)
      at BigDecimal.needIncrement (BigDecimal.java:4860)
      at BigDecimal.divideAndRound (BigDecimal.java:4835)
      at BigDecimal.setScale (BigDecimal.java:2923)
      at BigDecimal.setScale (BigDecimal.java:2838)
```

Are you sure that this should work as you have it written? Or are you saying that GWT incorrectly does _not_ throw an exception here (though GWT's behavior appears to the same at a brief glance...)?

**Comment by jnehlmeier** [comment]
Well that's how Java has defined `BigDecimal`. If you want to reduce the scale you have to tell `BigDecimal` how to round the number in order to fit into the new scale.

Reducing the scale using `RoundingMode.UNNECESSARY` can only be successful if your `BigDecimal` has enough zeros at the end. If you want to truncate your `BigDecimal` to a given scale you should use `RoundingMode.DOWN/FLOOR`.

Also in your example you have used the constructor `BigDecimal(double)` which is kind of a beast as there are many double values that cannot be represented exactly in binary form. Given your example number `91.0202` one might think the scale is 4 but in reality it is 46 because `91.0202` cannot be represented exactly. The binary form of that number represents `91.0202000000000026602720026858150959014892578125`.

So it is advisable to use the constructor `BigDecimal(String)` instead.

Using the string based constructor something like below will work:
```java
new BigDecimal("92.0200").setScale(2, RoundingMode.UNNECESSARY);
new BigDecimal("92.0200").setScale(2);
```
It works because the number has two zeros at the end and thus fits into a scale of 2 without any rounding.

**Comment by jnehlmeier** [comment]
Closing the issue because the exception is expected based on the provided example.
